### ISSUE TITLE
errors in training get muffled and i cannot see them

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#10]
when trying to train a pipeline.

obviously i did something wrong but i cannot see what happened and just got a "dummy.model"

this is bad

**Comment by berndbischl** [comment]
also i dont get logging on the console for prints in the learner....?
this is really bad for trying out stuff and debugging...

**Comment by mllg** [comment]
Is https://github.com/mlr-org/mlr3/commit/d12faf4feb26a8bac89e190ffff20eb40c2e4534 sufficient for the start? I can also completely disable going into the future package, depending on a option.

**Comment by berndbischl** [comment]
> I can also completely disable going into the future package, depending on a option.

i would like to have that i guess. it simplifies debugging a lot

**Comment by pat-s** [comment]
Maybe this helps: https://www.jottr.org/2018/07/23/output-from-the-future/
However, stderr is not supported which is probably what we would need here.

**Comment by mllg** [comment]
Future is now completely optional.
