### ISSUE TITLE
Feature Request: Predict type `"ci"` in addition to `"se"`

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#1010]
cc @berndbischl

**Comment by mb706** [comment]
you mean "in addition to"? Otherwise this would break a lot of things I'd assume...

**Comment by berndbischl** [comment]
@sebffischer pls dont do issues without text.... that's not great

**Comment by sebffischer** [comment]
you suggested this, I just created this issue so we don’t forget this

**Comment by sebffischer** [comment]
fixed by quantiles
