### ISSUE TITLE
Consider making BLAS thread setting optional, RhpcBLASctl Suggests

### ISSUE THREAD

**Issue by MichaelChirico** [mlr-org/mlr3#1023]
Follow-up to 959c9d61bfbf442a4a1755b672733f4fa7d0ecfe.

{RhpcBLASctl} is AGPL-licensed -- that makes it unattractive for many reasons, e.g.

https://opencoreventures.com/blog/2023-10-agpl-license-is-a-non-starter-for-most-companies/
https://deavid.wordpress.com/2020/08/02/affero-gpl-is-toxic-avoid-it-like-the-plague/
https://opensource.google/documentation/reference/using/agpl-policy

By having {RhpcBLASctl} in `Imports`, that means {mlr3} also can't be used without patching to avoid the AGPL dependency.

Glancing at the codebase, I think we can reasonably move that code to set BLAS threads as optional, and thereby relegate {RhpcBLASctl} to a `Suggests` dependency. WDYT?

Happy to file the relevant PR.

**Comment by be-marc** [comment]
Thanks for pointing that out. Without the package, the user might have server performance issues when parallelizing. Okay but I will move it to suggest. #1056
