### ISSUE TITLE
some advice to mlr3 from a heavy user in China

### ISSUE THREAD

**Issue by anticmason** [mlr-org/mlr3#1027]
Hi,
  I'm the heavy user of this package from China。I just wonder if you can deal with some 
  issues I've encountered....
  1.time series modeling：since several years passed,the package still in progress,just suggest            
   taking a view on modeltime package (modeltime, 
   modeltime.ensemble,modeltime.resample),which is the core part of tidymodels to deal with ts...
  2.when dealing with cluster modeling, if data is a bigger size,result can't be assessed with 
  msr('clust.silhouette') or other methods, R session always indicates to keep waiting with no result..... ,could it be possible to optimize，ClusterR package?
  3.could it be possible to deal with large dataset with the integration of package:arrow（open_dataset function is  a nice try)?
  4.could it be possible to upgrade some pipelines  that can deal with imbalance data 
  except smote? refer to the package themis...
Looking forward to your reply~

**Comment by m-muecke** [comment]
Cheers for using mlr3, but try to open the issues in the related repos, i.e. clustering in mlr3cluster, pipelines in mlr3pipelines, etc. There is already some support for other data sources via the [mlr3db](https://github.com/mlr-org/mlr3db/) package.
