### ISSUE TITLE
set_col_roles has confusing error for user-defined roles

### ISSUE THREAD

**Issue by tdhock** [mlr-org/mlr3#1040]
related to https://github.com/mlr-org/mlr3/issues/770
Hi! For https://github.com/tdhock/mlr3resampling I needed to define a new column role "subset" which is possible via 
```r
> my_iris <- data.frame(iris, my_subset=1:3)
> itask <- mlr3::TaskClassif$new("iris", my_iris, target="Species")
> itask$set_col_roles("my_subset","subset")
Erreur dans task_set_roles(private$.col_roles, cols, roles, add_to, remove_from) : 
  Assertion on 'roles' failed: Must be a subset of {'feature','target','name','order','stratum','group','weight'}, but has additional elements {'subset'}.
> itask$col_roles$subset <- "my_subset"
> str(itask$col_roles)
List of 8
 $ feature: chr [1:5] "Petal.Length" "Petal.Width" "Sepal.Length" "Sepal.Width" ...
 $ target : chr "Species"
 $ name   : chr(0) 
 $ order  : chr(0) 
 $ stratum: chr(0) 
 $ group  : chr(0) 
 $ weight : chr(0) 
 $ subset : chr "my_subset"
```
To me the following error message implies that subset is not allowed as a role: "Assertion on 'roles' failed: Must be a subset of {'feature','target','name','order','stratum','group','weight'}, but has additional elements {'subset'}." But subset is actually allowed if created via `$` instead of `set_col_roles` which is confusing for me.

The ?Task docs below say that set_col_roles "is a convenient alternative" which I think means that it should work the same as "just modify the list" but in my example code above we see that set_col_roles has some additional checking, so is not actually the same.
```
          ‘col_roles’ is a named list whose elements are named by
          column role and each element is a ‘character()’ vector of
          column names. To alter the roles, just modify the list, e.g.
          with R's set functions (intersect(), setdiff(),
          union(), ...). The method $set_col_roles provides a
          convenient alternative to assign columns to roles.
```
To fix this issue, can you please turn off the role checking/error in set_col_roles? or document that set_col_roles checks for default roles but the user can assign additional roles using `$` etc?

**Comment by be-marc** [comment]
Hey, thanks for the bug report. Yes we don't allow custom col roles. We allowed this some time ago to fix https://github.com/mlr-org/mlr3/issues/558. We will discuss this in our next meeting. I think that was only meant as a temporary fix.

**Comment by tdhock** [comment]
I need the custom "subset" col role for my mlr3resampling package, so please continue supporting arbitrary role assignment using `$` (otherwise my package will no longer work)
Thanks

**Comment by tdhock** [comment]
great to hear that I can define new col roles, but where is that documented? I expected some mention on https://mlr3.mlr-org.com/reference/Task.html#method-set-col-roles- but I do not see any mention of custom/new col roles.

**Comment by be-marc** [comment]
Yes, we tend to have less documentation for developers. We still need to find the right place for this.

**Comment by be-marc** [comment]
Setting new column roles via `$col_roles` throws an error now. @tdhock Please adapt your package.

**Comment by tdhock** [comment]
can you please submit a PR with the required changes?
or kindly tell me where is the documentation for "define new col roles" ?

**Comment by tdhock** [comment]
ok, thanks for sharing the code.
But I'm not sure that is consistent with CRAN policies.
https://cran.r-project.org/web/packages/policies.html says "- A package must not tamper with the code already loaded into R: any attempt to change code in the standard and recommended packages which ship with R is prohibited. Altering the namespace of another package should only be done with the agreement of the maintainer of that package."
I guess we can interpret your comments in this issue as "agreement" but think it would be better if this was documented, and/or possible to edit in a way that does not involve `getFromNamespace`

**Comment by tdhock** [comment]
I see a comment https://github.com/mlr-org/mlr3/blob/e9abedda7df95d8cd5bf74efd675548b020d12c0/R/mlr_reflections.R#L8 "This environment be modified by third-party packages, e.g. by adding information about new task types or by extending the set of allowed feature types."
