### ISSUE TITLE
Members "properties" and "task_type" are missing in Task.R

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#105]
In the "Details" section.

**Comment by mllg** [comment]
There seem to be more pages where this is the case. I'll collect here. Fixing is now too tedious, as I'm currently on a train with only one monitor.

* [ ] Task
* [ ] BenchmarkResult

Also, we get warnings from rmarkdown. There seems to be some invalid roxygen somewhere.

**Comment by mllg** [comment]
Also: Do we want to keep the references to the HTML help page. This does not work in the console, and basically points to a page with exactly the same informtion.

**Comment by mllg** [comment]
Found the reason for the warnings: FIXMEs as roxygen :(

**Comment by pat-s** [comment]
> Also: Do we want to keep the references to the HTML help page. This does not work in the console, and basically points to a page with exactly the same informtion.

Hm, I see. I thought it could be an easy shortcut to the pkgdown reference as it is tedious to go there by hand. The URLs should be stable for the foreseeable future. Looks like it is only useful in RStudio (which most users might use). 

It is up to you :)

> Found the reason for the warnings: FIXMEs as roxygen :(

Ahh sorry, I just quickly inserted them before the wrap-up session to not get lost.

**Comment by pat-s** [comment]
File an issue and keep the newline?

**Comment by mllg** [comment]
Solved itself during documentation overhaul.
