### ISSUE TITLE
Licensing issue due to mlr3 dependnency RhpcBLASctl

### ISSUE THREAD

**Issue by tdEmpl064** [mlr-org/mlr3#1057]
HI,

The library mlr3 advertises that its licensing is governed under LGPL-3. However, one of its dependencies is https://cran.r-project.org/package=RhpcBLASctl which is licensed under the viral AGPL-3 license. As such, RhpcBLASctl (hence mlr3, too) is not allowed to be used in my organization due to the AGPL-3-licensed component that mlr3 depends on.

Observe that the addition of RhpcBLASctl as an mlr3 dependency is a relatively recent modification, and we faced no issues using mlr3 prior to this development. In light of the limitations posed by this dependency, the request is to make RhpcBLASctl an optional dependency of mlr3 (as not everyone needs to regulate the number of threads used by BLAS in the first place).

Best regards,
Alexander Kolovos, Ph.D.

**Comment by m-muecke** [comment]
This was already done, see the merged PR: https://github.com/mlr-org/mlr3/pull/1056/files

**Comment by tdEmpl064** [comment]
Ah, nice, thank you; I saw the ticket you pointed me to moves RhpcBLASctl to the "suggests" list.
The current mlr3 version 0.20.1 on CRAN (https://cran.r-project.org/web/packages/mlr3/index.html; published  	2024-07-22) still shows RhpcBLASctl under "imports". Any estimate when the next version with the "suggested" change will be published, please?

**Comment by be-marc** [comment]
Should be on CRAN in a few hours.
