### ISSUE TITLE
Unexpected Feature Inclusion in mlr3 Task Definition

### ISSUE THREAD

**Issue by manuelreif** [mlr-org/mlr3#1060]
Hi!

I am new to the mlr3 package and want to use it for a project.

To estimate a regression, such as  a∼b, I created a task based on the dataset dt as shown below. I define "a" as the target and "b" as the feature. However, when I inspect the feature_names, I see that "c" is also listed as a feature.

Is this the intended behavior? I explicitly defined the feature I need, yet the function seems to include additional features. Have I done something wrong?

```r
library(mlr3)

dt      = data.table(a = rnorm(10), b = rnorm(10), c = rnorm(10))
my_task = as_task_regr(dt, target = "a", feature = "b")
my_task$feature_names
[1] "b" "c"
```

Thank you for your help!

**Comment by be-marc** [comment]
Hey,

what makes you think that there is a parameter `feature`? `as_task_regr()` takes all columns as features except the target. You have to subset your data before passing it to  `as_task_regr()` .

**Comment by manuelreif** [comment]
Hi!

I assumed there must be a parameter "feature" since this section of the documentation: [Data and Basic Modeling](https://mlr3book.mlr-org.com/chapters/chapter2/data_and_basic_modeling.html#sec-row-col-roles) explains all possible variable roles but does not mention that all variables except the target are automatically defined as features.

I can think of situations where this behavior might be problematic. For instance, if I define a weight variable that should not be a feature, or a stratum variable that should be used to stratify during resampling but not included as a predictor.

How can I specify exactly which features I want to use for prediction in a specific model? I thought the task statement was the right place to define these kinds of specifications.

```
library(mlr3)

dt      = data.table(a = rnorm(10), b = rnorm(10), c = rnorm(10), d = rnorm(10))
my_task = as_task_regr(dt, target = "a", feature = "b", stratum = "c", weight = "d")
my_task$feature_names
# [1] "b" "c" "d"
# weight and stratum are automatically included. Why?
```

**Comment by be-marc** [comment]
```r
dt = data.table(a = rnorm(10), b = rnorm(10), c = rnorm(10), d = rnorm(10), e = rnorm(10))
my_task = as_task_regr(dt, target = "a")

my_task$set_col_roles("c", roles = "stratum")
my_task$set_col_roles("d", roles = "weight")
my_task$set_col_roles("e", remove_from = "feature") 
```

See https://mlr3.mlr-org.com/reference/Task.html#method-set-col-roles-

**Comment by manuelreif** [comment]
Thank you!! :-)
