### ISSUE TITLE
Allow Multiple Ratios in partition() for Creating Training, Testing, and Validation Sets

### ISSUE THREAD

**Issue by manuelreif** [mlr-org/mlr3#1061]
Hi!

I am new to the mlr3 package and want to use it for a project.

This might be more of a feature request, but I would find it very useful if one could pass a vector as the "ratio" in `partition()`, such as `c(0.65, 0.25, 0.1)`. This way, as many partitions in the specified sizes would be created as there are ratios provided. For my current project, I would like to split my dataset into training, testing, and validation sets. Unfortunately, this is not directly possible with the current partition() function.

Thank you for considering my request!

**Comment by berndbischl** [comment]
the docs should be corrected, we dont explain stratum and grouping, we should also say that  we basically do exactly the holdout operation

**Comment by berndbischl** [comment]
remove stratify option
