### ISSUE TITLE
Pass instantiated resampling objects to benchmark

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3#108]
Can we have a check if the resampling object is already instantiated? Otherwise, it is not possible to use a custom resampling object with `benchmark` since it is instantiated just with the task, the custom test sets are then overwritten and ignored. Suggestion: #107

**Comment by mllg** [comment]
I think we have to find a different solution here. In benchmark, I have to instantiate each resampling for each task. You basically need a different interface for benchmark - one which does not force you to compute the cross product, but where you can specify each experiment separately. This is on my todo, I'll look into it soon.

**Comment by berndbischl** [comment]
Can we keep the cross product please? Where is the problem?

**Comment by berndbischl** [comment]
and: can we please post full examples, when we are now discussing major API changes? 
it is currently very hard to see what exactly breaks

**Comment by berndbischl** [comment]
i the crossproduct interface now already removed or what? because it looks like this when i look at the code. this was a major improvement...

**Comment by mllg** [comment]
Nothing has been removed. The new interface will be an alternative, not a replacement.

**Comment by mllg** [comment]
The new interface will be more flexible, i.e. you just pass combinations of tasks, learners, resampling and measure as rows of a data.table. AFAIR you wanted to have something like this some weeks ago?

**Comment by berndbischl** [comment]
to make it less confusing, I will only answer in #111, this seems like a minor technical thing here

**Comment by mllg** [comment]
@schalkdaniel The new benchmark interface should solve your problems. Let me know if you are missing something else.
