### ISSUE TITLE
Set environment variables to disable parallelization

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#1081]
We are currently optionally using RhpcBLASctl to set threads to 1 by default so this does not conflict with parallelization via future. 
This packages was recently moved into suggests because of its AGPL license.
We have discussed that we should still try to set threads to 1 even when this package is not available via a "80% solution through environment variables. The alternative is to ask the packages authors to relicense their package so we can move it from Suggests into Imports again.

**Comment by berndbischl** [comment]
Why do we care about the license in terms of imports or suggest....?

**Comment by sebffischer** [comment]
people from google cannot use agpl so they could not use mlr3 when it was in Imports.

**Comment by mb706** [comment]
interesting environment variables:
```
OPENBLAS_NUM_THREADS
OMP_NUM_THREADS
OMP_THREAD_LIMIT
```

I only have limited experience with these; I believe they only take effect at the first instance when blas / omp are loaded or used (or right away when R is loaded?). It seems to be difficult to use these to change the behaviour of the current R session, but I believe it is possible to influence processes that are started from the current R session, e.g. by future or callr.

**Comment by be-marc** [comment]
We set "OPENBLAS_NUM_THREADS" and "MKL_NUM_THREADS" on the worker now. I think we should not change the OMP variables because the user might want to parallelize a learner with OMP.
