### ISSUE TITLE
test_learner should have a filter argument

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr3#110]
When debugging errors of a learner it's really annoying that I can only run the full test suite.

E.g. currently for `classif.logreg` a test with logical features seems to be broken

```
INFO [mlr3] Training learner 'classif.logreg' on task 'logical' ...
INFO [mlr3] Predicting with model of learner 'classif.logreg' on task 'logical' ...
Error in predictionclassif_initialize(self, task, response, prob) :
  Assertion on 'response' failed: Contains missing values (element 1).
```

But I cannot trigger this test directly and it's not even obvious which code to copy from test_learner to trigger it automatically

**Comment by mllg** [comment]
We have individual test files now, and also the possibility to exclude specific tests. @Coorsaa is working on a function which simplifies debugging.
