### ISSUE TITLE
benchmark should have "experiment table" interface - a bit like batchtools

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#111]
this was a major step forward from the old mlr, which now would allow arbitrary combinations of experinmental setting.

use cases:
- small task, large task: i need a different resamplings
- some tasks need to have different learners computed

etc.

I dont see a single case where this interface makes anything harder, it just enables more

**Comment by mllg** [comment]
You mean: should **not** have crossproduct interface?

**Comment by berndbischl** [comment]
you said in #108 

Michel : "The new interface will be more flexible, i.e. you just pass combinations of tasks, learners, resampling and measure as rows of a data.table. AFAIR you wanted to have something like this some weeks ago?"

This is EXACTLY what I want. And yes, we agreed upon this in Dortmund. I just thought we had it already, and I didn't want it to be removed. 
(I currently does not seem to be there).

The be precise:
What I would like to see is this:

```
benchmark = function(exptab, ctrl = list()) 
```

where
exptab is a datatable with list-cols
<Taks>, <Learner>, <Resampling>

The resampling could be instantiated or not.

AFTER we have that, we COULD add this:

```
benchmarkCJ(tasks, learners, resamplings) 
```

which would create such a table through a join, to add some convenience for users. 
So an often used call might look like:

```
exptab = benchmarkCJ(tasks, learners, resamplings) 
benchmark(exptab)
```

I still see some inconsistency in how we pass the measures, but I will open a clean issue for that

**Comment by berndbischl** [comment]
> You mean: should **not** have crossproduct interface?

yes, sorry, my title was bad, improved it

**Comment by mllg** [comment]
`benchmark()` now uses the new interface, you always have to pass a design table.
