### ISSUE TITLE
Measure$score has weird NaN producing code

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#1110]
```
  if (is.null(prediction) && length(measure$predict_sets)) {
    return(NaN)
  }
```

we have this above. this not documented and weird

**Comment by zhonghua723** [comment]
i have encountered the same question many times. please help me address it. thanks.

tab_rsmp
      nr task_id     learner_id resampling_id iters classif.auc classif.acc classif.tpr classif.tnr classif.ppv classif.npv
   <int>  <char>         <char>        <char> <int>       <num>       <num>       <num>       <num>       <num>       <num>
1:     1       1 classif.glmnet       holdout     1   0.9333333   0.9615385   0.9333333   1.0000000   1.0000000   0.9166667
2:     2       1 classif.glmnet   repeated_cv   100   0.9901825   0.9498611   0.9226667   0.9662500         NaN   0.9461071
3:     3       1 classif.glmnet   subsampling  1000   0.9899363   0.9455000   0.9289839   0.9604998   0.9529729   0.9413482
4:     4       1 classif.glmnet     bootstrap  1000   0.9868122   0.9397969   0.9250875   0.9536506   0.9440450   0.9381008
Hidden columns: resample_result

code:
resamplings <- list(
  holdout_70 = rsmp("holdout", ratio = 0.7),
  repeated_cv_10_10 = rsmp("repeated_cv", folds = 10, repeats = 10),
  subsampling_70 = rsmp("subsampling", ratio = 0.7, repeats = 1000),
  bootstrap_1000 = rsmp("bootstrap", repeats = 1000, ratio = 0.7)
)

design_rsmp <- benchmark_grid(
  tasks = task_model,             
  learners = lrns('classif.glmnet', predict_type = "prob"),          
  resamplings = resamplings      
)

bmr_rsmp <- benchmark(design_rsmp, store_models = T)
measures <- msrs(c("classif.auc", "classif.acc", "classif.tpr", "classif.tnr", "classif.ppv", "classif.npv"))
tab_rsmp <- bmr_rsmp$aggregate(measures)

**Comment by berndbischl** [comment]
@zhonghua723 what you posted is likely another issue. could you please open another issue and please (!)  post a fully reproducible example

**Comment by mb706** [comment]
(in particular, we would need the `task_model` dataset in this example, and make sure you run `set.seed()` as well.)

**Comment by berndbischl** [comment]
ok, lets add warning, docs and tests

**Comment by mllg** [comment]
Warnings where already in place in `assert_measure()` if `Measure$check_prerequisites` is set to `"warn"` (default). The warning will only be triggered once per `resample()`/`benchmark()` and measure (in contrast to what we agreed on here) which is IMHO the nicer behavior.

**Comment by mllg** [comment]
Note that this is documented in the field of Measure

```
    #' @field check_prerequisites (`character(1)`)\cr
    #' How to proceed if one of the following prerequisites is not met:
    #'
    #' * wrong predict type (e.g., probabilities required, but only labels available).
    #' * wrong predict set (e.g., learner predicted on training set, but predictions of test set required).
    #' * task properties not satisfied (e.g., binary classification measure on multiclass task).
    #'
    #' Possible values are `"ignore"` (just return `NaN`) and `"warn"` (default, raise a warning before returning `NaN`).
```
