### ISSUE TITLE
How do we pass measures

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#113]
This seems to be a bit inconsistent. Can you explain this please? 

a) I can set them in the task. I guess then all subsequent experiments would use and evaluate them? 
Question: Wouldnt that be enough? 

b) Experiment$score seems to take them. Why? 
(This is not that bad IMHO, but for a minimal interface it still seems redundant?)

c) Resample: Same question as for b). Redundant? Why needed?

d) benchmark: This really seems a bit problematic now.
It is still redundant to pass measures here, but: The really interesting usecase, which IMHO is: 
"Use different measures for different tasks" is not supported by just having a list of measures in the signature of benchmark. I guess these measure are then used for ALL tasks.
So I see 2 options:
a) Remove "measures"-argument in score, resample, and benchmark and just stick with option a).
(Seems best if you dont habe a counter-usecase)
b) Let resample and score be as they are, but add the measures to the rows in the table in issue #111

**Comment by mllg** [comment]
Arguments removed.
