### ISSUE TITLE
document the autotest system

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#1143]
doc it in this way:
1) doc the API in the src files
2) for complicated code parts, add block comments
3) either summarize the autotest procedure in the dev wiki,
or, as we don't really need redundant text, do a very BRIEF summary in the wiki and simply link to the API docs

**Comment by be-marc** [comment]
Did you see #1128 ?

**Comment by berndbischl** [comment]
ok, we now have 2 files. 
R/mlr_test_helpers.R
inst/testthat/autotest.R

in both files mention that the other exists
and: add 2 link in the dev wiki under "autotests"

**Comment by be-marc** [comment]
Done
