### ISSUE TITLE
check that we have unit tests for wrong data entry when col roles are set

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#1146]
make sure every col role has at least some basic tests that if wrong data is pointed to in the backend, we exit with a clean error msg.

**Comment by be-marc** [comment]
#1131 Already merged

**Comment by berndbischl** [comment]
one could maybe add 1-2 tests for neg weights, or NA weighst

**Comment by berndbischl** [comment]
are all these roles actually tested:

```
    #' * `"feature"`: Regular feature used in the model fitting process.
    #' * `"target"`: Target variable. Most tasks only accept a single target column.
    #' * `"name"`: Row names / observation labels. To be used in plots. Can be queried with `$row_names`.
    #'   Not more than a single column can be associated with this role.
    #' * `"order"`: Data returned by `$data()` is ordered by this column (or these columns).
    #'   Columns must be sortable with [order()].
    #' * `"group"`: During resampling, observations with the same value of the variable with role "group" are marked as "belonging together".
    #'   For each resampling iteration, observations of the same group will be exclusively assigned to be either in the training set or in the test set.
    #'   Not more than a single column can be associated with this role.
    #' * `"stratum"`: Stratification variables. Multiple discrete columns may have this role.
    #' * `"weight"`: Observation weights. Not more than one numeric column may have this role.
```

also note that docs say that e.g weights can only be assigned to ONE col. is that tested?

**Comment by be-marc** [comment]
> one could maybe add 1-2 tests for neg weights, or NA weighst

I think we test too much when we start testing our assertions. The case you are referring to is being tested.

https://github.com/mlr-org/mlr3/blob/57b6109355ae5219d735a89c188d1b987ae2ff41/R/Task.R#L1201

**Comment by be-marc** [comment]
Handling of targets is inconsistent. `TaskRegr` and `TaskClassif` check that target is of length 1 but `set_col_roles` allows to set more than target.
