### ISSUE TITLE
autotests: errorhandling seems weird, dont encapsulate

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#1147]
we seem to do a lot of extra encapsulation in the autotests.
this seems something that we actually DONT want. encapsulation would require / use a fallback learner

we don't want that in the autotests. we want to "stop" on errors.

now, I said "stop" with quotes as we want to kinda continue.... but ONLY in the sense that the error message is collected.
not fallback models, etc

**Comment by be-marc** [comment]
#1128 ?
