### ISSUE TITLE
collect global instructions

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#115]
General: 
We need to collect general instructions for all child projects of mlr3. This is important so that we unify and streamline our process and do not waste time. 

@mllg already collected some stuff in the mlr3 wiki, which is a step into the right direction
https://github.com/mlr-org/mlr3/wiki

In general, the wiki seems like the correct place to put this stuff. For quicker editing, we might link to google docs, if stuff is in a transition period and we work on docs during meetings.

PS: I still do not like putting things into a repo wiki if it belongs to the whole org. But yes, it's simply and quick. Easier than learning how to handle the website. 

# Documentation

* https://github.com/mlr-org/mlr3/wiki/Roxygen-Guide

# Style guide

We need one. It does not have to be super large, but we need to have the important stuff in there. 
We have the old one here, very outdated: 

* https://github.com/rdatsci/PackagesInfo/wiki/R-Style-Guide

PS: And a current PR in mlr that automatically reformats the code according to our defined style rules:

* https://github.com/mlr-org/mlr/pull/2498

# Travis setup

In mlr, travis become quickly very complex, and most people have problems with setting up the details. 

BB: We should not leave this to individual packages, we need a proper setup, at least documented. Better would be a well-documented submodule, so child packages can directly integrate the code

PS: We have somewhat up-to-date guide in the mlr-wiki: https://github.com/mlr-org/mlr/wiki/Travis
Not sure how submodules and Travis should work exactly, but a documented workflow that lists all the steps should do it (most of it is automatically handled nowaydays in the background by `tic`).

# Coding guide / Libary usage

I am unsure about the headinline here, but what I mean is that we use certain libs / ways or code and other not. This should also be defined.

R6, datatable, mlr3misc purrr compat functions, stringi, printers, etc

We shouldn't go go overboard here, but we very obviously have some standards for some stuff. If so, we need to communicate this.

PS: Shouldn't this be listed in one section together with the "style guide"? Whether its a "style guide" or "coding guide" - all list specific rules how coding should be done in the mlr-world.

**Comment by mllg** [comment]
Closed in favor of discussion on slack.

**Comment by berndbischl** [comment]
apparently the discussion on slack does not work, and slack is not for issues.

further stuff we need to collect globally: travis + github setup. not everyone should have to write this from scratch

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr3/wiki/Roxygen-Guide ?

**Comment by berndbischl** [comment]
> https://github.com/mlr-org/mlr3/wiki/Roxygen-Guide ?

it is a bit hard to understand what you mean if you post a lingle link?

**Comment by berndbischl** [comment]
i will iterate over the first post now, to collect what we have, and add some comments. please help, i think it is pretty urgent that we solve this

**Comment by pat-s** [comment]
> please help, i think it is pretty urgent that we solve this

I'll add my thoughts and contribute to the first post ASAP.

**Comment by pat-s** [comment]
Updated.

**Comment by mllg** [comment]
I could need some help here:

* Roxygen guide: Somebody needs to proof-read it. @mb706?
* Style guide: @pat-s has taught styler what we want the code to look like. We now just need to write it down for humans. Also, we might want to look into some very basic linting rules. I think I would like to have both running on a CI for PRs, but not pushing automatically into master. We might also need to write down how to use styler/lintr from RStudio?
* Travis: @pat-s What the state here? Also see #188 .
* Coding guide: I could start writing something down here, and maybe @berndbischl can then take over?

**Comment by pat-s** [comment]
**Style guide**: See https://www.notion.so/mlrorg/Style-Guide-740bc663207a4bbb9a457987bda6fd91

**CI:** https://www.notion.so/mlrorg/CI-setup-98e90e1eba044ff5ba576f2ffad768dc

**Coding guide:** What exactly do you mean here? I would not suggest putting anything related to "getting around on Github" there as we had previously. This just makes everything bloat and is not really our job in this project telling people how to get around with git/github/R pkg dev. An overview of the mlr3 ecosystem would be helpful and which functions should be used for tests/apply-calls etc. 

Please put the roxygen guide and the coding guide as new pages into the [mlr wiki](https://www.notion.so/mlrorg/mlr-Wiki-7eb88a684e6a4e3abc26208d05e03fa0).

**Comment by pat-s** [comment]
> I think I would like to have both running on a CI for PRs, but not pushing automatically into master.

This is possible for both. What about

1. Styling each pkg once with our mlr style
2. Running both non-invasive during the CI

If we keep the packages tidy, runtime increase should be acceptable.

**Comment by pat-s** [comment]
The [CI guide](https://www.notion.so/mlrorg/CI-setup-98e90e1eba044ff5ba576f2ffad768dc) has been updated.

More detailed instructions for the "dev/coding guide" should go into https://www.notion.so/mlrorg/Developer-Guide-65e60b651a2e44e89a36b72df92158ea. But I doubt that anyone really reads this...
@mllg 	

Coding guide: I really think pointing people to use/apply the "styler" style is way easier than teaching them every single rule of our style guide. 

Roxygen guide: Should probably into the [style guide](https://www.notion.so/mlrorg/Style-Guide-740bc663207a4bbb9a457987bda6fd91). @mllg 	Do you want to do this?

**Comment by mllg** [comment]
Everything is now in the wiki, and we have another issue opened by Bernd on the same topic.
