### ISSUE TITLE
have a nice function to create a default fallback -- and warn if it doesnt have enough properties

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#1150]
marc added some code in encapsulate to preconfigure a fallback.

maybe that should simply be a helper. so it can be called from the outside.

i also think: on setting the fallback you PROBABLY wanna warn the user if you fallback can do "less", 
e.g. doesn't have the same predict_type (error?) or can do no weights....

we don't have to be SUPER precise here or "block" actions. but at least warn about obvious problems?

**Comment by be-marc** [comment]
#1151
