### ISSUE TITLE
Error in private$.get_values() : when save learner in Linux, and load learner in Windows

### ISSUE THREAD

**Issue by lshddd** [mlr-org/mlr3#1156]
I created a learner in Linux OS, and save as rds :
lrn_ranger = lrn("classif.range")
saveRDS(lrn_ranger,"lrn_ranger.rds")

Whern I load this learner in Windows:
> library(mlr3)
> lrn_ranger = readRDS("lrn_ranger.rds")
> lrn_ranger 
<LearnerClassifRanger:classif.ranger>: Random Forest
* Model: -
* Error in private$.get_values()

-----------------------------------------------------------------------------------------------------------------------------------------------------
Linux session info :
R version 4.4.0 (2024-04-24)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] DALEXtra_2.3.0          DALEX_2.4.3             corrplot_0.92          
 [4] mlr3verse_0.3.0         mlr3_0.20.0             lubridate_1.9.3        
 [7] forcats_1.0.0           stringr_1.5.1           dplyr_1.1.4            
[10] purrr_1.0.2             readr_2.1.5             tidyr_1.3.1            
[13] tibble_3.2.1            ggplot2_3.5.1           tidyverse_2.0.0        
[16] mlr3extralearners_0.8.0 dlookr_0.6.3            bigrquery_1.5.1        
[19] httr_1.4.7 
--------------------------------------------------------------------------------------------------------------------------------------
windows session info:
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlr3_0.20.0
-----------------------------------------------------------------------------------------------------------------------------------------------

Can't   creat   learner in Linux, and use in Windows？

**Comment by be-marc** [comment]
Hey, that should work without any problems. You probably have an old version of `paradox` installed on one of the systems.

**Comment by lshddd** [comment]
> Hey, that should work without any problems. You probably have an old version of `paradox` installed on one of the systems.
@be-marc 
Thank you for your help!
But it still cannot be used under Windows 😂 
My linux env paradox version is 1.0.0, windows env paradox version is 1.0.1 .
I had tried to uninstalling Paradox 1.0.1 and then installing Paradox 1.0.0;but it still doesn't work.

My linux mlr3 package version
> packageVersion("paradox")
[1] ‘1.0.0’
> packageVersion("mlr3")
[1] ‘0.20.0’
> packageVersion("mlr3verse")
[1] ‘0.3.0’
> packageVersion("mlr3pipelines")
[1] ‘0.6.0’
> packageVersion("mlr3extralearners")
[1] ‘0.8.0’


==============================================================

My windows mlr3 package version
> packageVersion("paradox")
[1] ‘1.0.1’
> packageVersion("mlr3")
[1] ‘0.20.2’
> packageVersion("mlr3verse")
[1] ‘0.3.0’
> packageVersion("mlr3pipelines")
[1] ‘0.6.0’
> packageVersion("mlr3extralearners")
[1] ‘0.9.0’

I am also confused. In another virtual machine Linux environment, even mlr3 0.19.0.9000, can still load learner from RDS file

**Comment by lshddd** [comment]
@be-marc 
My windows have a old R env backup. i use the old version,it work.
the old versions is:
> packageVersion("paradox")
[1] ‘1.0.0’
> packageVersion("mlr3")
[1] ‘0.18.0’
> packageVersion("mlr3verse")
[1] ‘0.2.8’
> packageVersion("mlr3pipelines")
[1] ‘0.5.1’
> packageVersion("mlr3extralearners")
[1] ‘0.8.0.9000’

it can load learner,and predict task.
> lrn_catboost = readRDS("E:\\data\\kaggle\\playground-series-s4e8\\model\\lrn_catboost.rds")
> lrn_catboost$predict(task = task,row_ids = c(1:10))
<PredictionClassif> for 10 observations:
    row_ids truth response       prob.p      prob.e
          1     e        e 0.0015504637 0.998449536
          2     p        p 0.9953928794 0.004607121
          3     e        e 0.0006811367 0.999318863
---                                                
          8     p        p 0.9977463496 0.002253650
          9     p        p 0.9981687955 0.001831205
         10     e        p 0.5430306733 0.456969327
Warning messages:
1: Detected version mismatch: Learner 'lrn_catboost' has been trained with mlr3 version '0.20.0', not matching currently installed version '0.18.0' 

but cannot predict_newdata
> lrn_catboost$predict_newdata(test_data)
Error in .__Task__row_roles(self = self, private = private, super = super,  : 
  Assertion on 'names of row_roles' failed: Names must be a set equal to {'use','test','holdout'}, but is missing elements {'test','holdout'}.

maybe it's because the package version is not compatible.
Thanks again for your help !
