### ISSUE TITLE
Option to suppress printing INFO lines from resample()

### ISSUE THREAD

**Issue by baderstine** [mlr-org/mlr3#1167]
Calling `resample()` always prints one line per resample fold.  Sometimes (e.g., within .rmd) this output is undesireable.  

Please provide an option or method for suppressing this output (e.g., `resample(..., silent = TRUE)`)

**Comment by be-marc** [comment]
Hey, see logging in https://mlr3book.mlr-org.com/chapters/chapter10/advanced_technical_aspects_of_mlr3.html#sec-logging

**Comment by baderstine** [comment]
Ah, excellent I missed that part!  Apologies for the extraneous issue report.
