### ISSUE TITLE
mlr3 code failing in Geocomputation with R book 

### ISSUE THREAD

**Issue by Robinlovelace** [mlr-org/mlr3#1182]
We're seeing new error messages in our CI workflows that seem to be related to {mlr3}. I'm not sure what the exact cause is, @jannes-m plans to look into it, but I wanted to let the developer team know as I guess it's affecting others. See below links and some investigations by us that I hope is usefull:

- The section that is failing with the latest version (rendered with previous package versions, the failing code blocks can be found at the end of this section, specifically in the code chunks around `autotuner_rf$train(task)`: https://r.geocompx.org/eco#mlr3-building-blocks

Should we add `, store_backends = TRUE` during model fitting as suggested there?

```
! The backend of Task 'mongon' has been removed. Set `store_backends` to `TRUE` during model fitting to conserve it.
Backtrace:
  1. base::eval(...)
 27. mlr3 (local) `<fn>`()
 28. mlr3:::.__Task__groups(...)
 29. mlr3:::assert_has_backend(self)
 30. mlr3misc::stopf(...)
Warning messages:
1: In warn_deprecated("Task$data_formats") :
  Task$data_formats is deprecated and will be removed in the future.
2: In warn_deprecated("DataBackend$data_formats") :
  DataBackend$data_formats is deprecated and will be removed in the future.
3: In warn_deprecated("Learner$data_formats") :
  Learner$data_formats is deprecated and will be removed in the future.
Quitting from lines 519-520 [15-eco-26] (15-eco.Rmd)
```

- PR with changes aimed at fixing the issue and some comments: https://github.com/geocompx/geocompr/pull/1117

Apologies for not having a clearer report or more minimal reproducible example (although it is reproducible) and hope this is helpful.

**Comment by jannes-m** [comment]
I think we can close this, solved via https://github.com/geocompx/geocompr/pull/1124

**Comment by stainesa** [comment]
Still affects mlr3 when knitting, with the exact same set pf errr messages - - outside of geocompx - I think there's a wider problem.

**Comment by Robinlovelace** [comment]
Thoughts @jannes-m ?

**Comment by be-marc** [comment]
We encounter this issue when using quarto.  Usually it helps to deactivate caching (`#| cache: false`) for chunks that create a task. Somehow the caching removes the backend of the task.

**Comment by Robinlovelace** [comment]
That's useful and matches my experience: sometimes caches cause issues.

**Comment by stainesa** [comment]
Thanks for the very helpful comments!

Following on your suggestion, I found what I think this is the fix - in a post from @mllg  

"Try disabling the lazy cache if you encounter problems with knitr:"

`knitr::opts_chunk$set(cache = FALSE, cache.lazy = FALSE)`
