### ISSUE TITLE
Time constraints gallery update with new mlr3 v0.21.0 encapsulation

### ISSUE THREAD

**Issue by iLivius** [mlr-org/mlr3#1185]
Hi Marc,

I was just going through your [time constraints](https://mlr-org.com/gallery/technical/2023-12-21-time-constraints/) article in the gallery and noticed that users might encounter an error with the latest `mlr3` v0.21.0 due to changes in how encapsulation is handled.

Perhaps suggesting an updated encapsulation strategy would be helpful, such as:
```r
learner$encapsulate("callr", fallback = lrn("classif.featureless", predict_type = "prob"))
```
Thank you and the entire `mlr3` team for your incredible work!

**Comment by be-marc** [comment]
Hey, thanks for reporting. Fixed in https://github.com/mlr-org/mlr3website/pull/171
