### ISSUE TITLE
Assertion on 'predict_types' failed

### ISSUE THREAD

**Issue by invain1218** [mlr-org/mlr3#1187]
I am getting an error when printing` as.data.table(lrn())`.
Error: assert_ordered_set(predict_types, names(mlr_reflections$learner_predict_types[[task_type]]), : 
  Assertion on 'predict_types' failed: Must be a subset of {'response','se','distr'}, but has additional elements {'quantiles'}.
Before that I installed mlr3proba and mlr3extralearner.
How do I fix it? Thank you very much!

**Comment by larskotthoff** [comment]
Did you update all mlr3 packages to the latest version?

**Comment by invain1218** [comment]
Oh! Thanks!!!
When I update all mlr3 packages, the problem is solved!
