### ISSUE TITLE
Add support for downloading openml data sets

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#119]
Would be great for examples.

Better suited for the openml package, but you would get sooo much with just these lines:

```r
  id = 13
  j = jsonlite::fromJSON(sprintf("https://www.openml.org/d/%i/json", id))
  fn = tempfile()
  download.file(j$url, fn)
  data = farff::readARFF(fn)
  target = j$default_target_attribute
```

**Comment by berndbischl** [comment]
+1
but we need to discuss this a bit

**Comment by berndbischl** [comment]
OTOH: if its just a few lines of code, it might be a good idea to just go for it and play around with it and see what happens?

**Comment by berndbischl** [comment]
i really dont think this should be in mlr3. close?

**Comment by pat-s** [comment]
I also do not think that this should live in {mlr3}.
The issue here is {farff} with what it would pull in ({stringi}, {readr}).
{jsonlite} is for free.

How about putting this code as an example into a code chunk within a section of the help page of `Task`?

**Comment by berndbischl** [comment]
IMHO this should simply be closed.

**Comment by pat-s** [comment]
Probably. Presumably this code might break in the future and having it read-only in a help page might result in undetected dead code.
