### ISSUE TITLE
How do I use the predict_newdata()?

### ISSUE THREAD

**Issue by invain1218** [mlr-org/mlr3#1216]
Hello, mlr3 team,

I am confused about the` predict_newdata()`. After training a model, I need it to make predictions on new data. However, I am uncertain whether I should process the new data in the same way as I did with the training data. For example, should I apply the same preprocessing steps to the new data as I did to the training data? Additionally, do I need to include the train_task during the training phase when predicting on new data?

I have the impression that preprocessing the new data may not be necessary, but I could be mistaken. Thanks for help!!! 😊

As an example
```
library(mlr3)
library(mlr3tuning)
library(mlr3pipelines)
rm(list=ls())
set.seed(123)
n=200
data = data.frame(
  f1 = rnorm(n, mean=2,sd=1),
  f2 = rbinom(n, size=1,prob=0.5),
  f3 = rgamma(n,shape = 0.2,rate=1),
  f4 = rpois(n,0.6),
  f5 = factor(sample(c("A","B","C"),size=n, replace = TRUE, prob=c(0.3,0.3,0.4))),
  f6 = rnorm(n,mean = 4,sd=3),
  f7 = rnorm(n, mean=5, sd=5),
  f8 = rnorm(n, mean=20, sd=5)
)
newdata = data[150:200,]
mdata = data[1:149,]
tsk_wd = TaskClassif$new(id="tsk",backend = mdata, target = "f5")
pro_tsk = po("pca",rank. = 3)$train(list(tsk_wd))[[1]]

model = lrn("classif.rpart",predict_type="prob")
resampling = rsmp("holdout", ratio=0.8)
model_rr = resample(
  task = pro_tsk,
  learner = model,
  resampling = resampling,
  store_models = TRUE,
  store_backends = TRUE
)
l3 = model_rr$learners[[1]]
```

When I use the predict_newdata()

```
l3$predict_newdata(newdata = newdata)
```
Error: No task stored, and no task provided

```
l3$predict_newdata(newdata = newdata,task=pro_tsk)
```
Error in .__Learner__predict_newdata(self = self, private = private, super = super,  : 
  Assertion on 'newdata$colnames' failed: Names must include the elements {'PC1','PC2','PC3'}, but is missing elements {'PC1','PC2','PC3'}.

```
l3$model$learner$predict_newdata(newdata = newdata)
```
Error: Not applicable to non-functions

**Comment by be-marc** [comment]
Why don't you make the preprocessing part of the learner? 

```r
library(mlr3)
library(mlr3tuning)
library(mlr3pipelines)
rm(list=ls())
set.seed(123)
n=200
data = data.frame(
  f1 = rnorm(n, mean=2,sd=1),
  f2 = rbinom(n, size=1,prob=0.5),
  f3 = rgamma(n,shape = 0.2,rate=1),
  f4 = rpois(n,0.6),
  f5 = factor(sample(c("A","B","C"),size=n, replace = TRUE, prob=c(0.3,0.3,0.4))),
  f6 = rnorm(n,mean = 4,sd=3),
  f7 = rnorm(n, mean=5, sd=5),
  f8 = rnorm(n, mean=20, sd=5)
)
newdata = data[150:200,]
mdata = data[1:149,]
tsk_wd = TaskClassif$new(id="tsk",backend = mdata, target = "f5")

model = po("pca",rank. = 3) %>>% lrn("classif.rpart", predict_type = "prob")

resampling = rsmp("holdout", ratio=0.8)
model_rr = resample(
  task = tsk_wd,
  learner = model,
  resampling = resampling,
  store_models = TRUE,
  store_backends = TRUE
)
l3 = model_rr$learners[[1]]

l3$predict_newdata(newdata = newdata, task = tsk_wd)
```

**Comment by invain1218** [comment]
use the %>>% operator to connect the preprocessing pipeline and the model, by doing this, the model retain the preprocessing steps from earlier in its workflow? Ok! I will use this! Thank you very much!

**Comment by be-marc** [comment]
You can read more about it in the [book](https://mlr3book.mlr-org.com/chapters/chapter7/sequential_pipelines.html)

**Comment by invain1218** [comment]
Like this:
```
tsk = TaskClassif$new(id="test",backend = test)
```
Error in assert_string(target) : 
  argument "target" is missing, with no default

```
tsk = TaskClassif$new(id="test",backend = test, target = "")
```
Error in .__TaskSupervised__initialize(self = self, private = private,  : 
  Assertion on 'target' failed: Must be a subset of {'f1','f2','f3','f4','f6','f7','f8'}, but has additional elements {''}.
 
 But the test.csv don't have target column.

**Comment by be-marc** [comment]
Okay just store the task. 

I would recommend that you read through the Fundamentals chapter in the book. What you are doing there looks a bit questionable.

**Comment by invain1218** [comment]
Ok, I will definitely do that! And thank you so much~😊
