### ISSUE TITLE
`col_roles` documentation out of sync?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#123]
`$col_roles` doc in `?Task` lists 'feature', 'target', 'ignore', and 'primary_key', while e.g. `mlr_tasks$get("iris")$col_roles` has members 'feature', 'target', 'order', 'groups', 'weights'.

**Comment by mllg** [comment]
The deployment is broken. The html files are empty and pkgdown refuses to update them.

https://travis-ci.org/mlr-org/mlr3/builds/476302166

@pat-s Is there a flag to force-overwrite the HTML files?

**Comment by mllg** [comment]
Seems to work again (for now)
