### ISSUE TITLE
Task$cbind error about name collision that should not be after Task$select

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#125]
```r
task = mlr_tasks$get("iris")
newcols = cbind(data.table(Sepal.Length = 1:150), task$row_ids)
task$select(character(0))$cbind(newcols)
```
gives
```r
Error: Cannot cbind task: Duplicated column names: Sepal.Length
```
even though `Sepal.Length` should have been removed by the `$select()` call.

**Comment by mllg** [comment]
Try `task$replace_columns(newcols)`. We should discuss the backends tomorrow.

**Comment by mb706** [comment]
`$replace_columns` complains when column types differ, is that deliberate?
```r
> task = mlr_tasks$get("iris")
> newcols = cbind(data.table(Sepal.Length = as.character(1:150)), task$row_ids)
> task$replace_columns(newcols)
Error: Cannot rbind task: Types do not match for column: Sepal.Length (numeric != character)
```

**Comment by mllg** [comment]
Nope, I've removed the check. Leaving this issue open as a reminder to write some more tests.

**Comment by mllg** [comment]
This has been refactored. You should now be able to replace the data with `task$replace_data()`.
