### ISSUE TITLE
why does resample / training need access to par_vals slot?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#14]
this came up when i resampled pipelines
maybe this goes away when we make the learner interface a bit more minimal?

**Comment by berndbischl** [comment]
(because that is exactly what i need to know so i can write a pipeline...)

**Comment by jakob-r** [comment]
@mllg Do you know what @berndbischl means?

@berndbischl Can you maybe link to the code that you mean?

**Comment by mllg** [comment]
Solved via hangout.

**Comment by berndbischl** [comment]
was it really solved? it is documented now somewhere? we really need this to move forward with the piplines
