### ISSUE TITLE
Why are some Measures cloneable, others not?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#142]
The base classes Measure, MeasureClassif, etc. all have `cloneable = FALSE` set, while the concrete measures such as MeasureClassifMMCE are clone-able. Is this on purpose?

If any measure is supposed to be cloneable or mutable in principle, then `Task$clone(deep = TRUE)` should take care to make a deep copy of its `measures` list.

**Comment by mllg** [comment]
Now all measures are not cloneable.
