### ISSUE TITLE
Admit Learners in mlr_learners that have constructor args without default(?)

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#177]
`mlr3pipelines::GraphLearner` could be added to the `mlr_learners` dictionary if there was a way to set the constructor argument `graph` during `$get()`.

**Comment by mllg** [comment]
As discussed, now possible by overloading the `get()` method of the dictionary. See https://github.com/mlr-org/mlr3/blob/master/R/mlr_learners.R#L26 for an example.

Ugly, but working 😟

**Comment by mb706** [comment]
Are you suggesting mlr3pipelines should overwrite the `mlr_learners` dict with its own class to get this to work?

**Comment by mllg** [comment]
Nope. Create a class DictionaryPipeops inheriting from Dictionary where you overload the get method.

**Comment by mllg** [comment]
Just like in the linked file, but s/learner/pipeop.

**Comment by mb706** [comment]
It would be more fitting if `GraphLearner` were in `mlr_learners` imho
