### ISSUE TITLE
Preserve `data.table` levels

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#179]
Sometimes presence of empty levels in a `data.table` is important, but somewhere in the course of `as_data_backend` and `Task$new` some information seems to get lost; similarly `$cbind` has the same problem:
```r
tbl <- data.table(
  x1 = factor(letters[1:5], levels = letters[5:1]),
  x2 = factor(letters[1:5], levels = letters),
  x3 = letters[1:5],
  target = 1:5)
task = TaskRegr$new("tbl", as_data_backend(tbl), "target")
task$levels("x2")
```
result:
```r
[1] "a" "b" "c" "d" "e"
```
desired:
```r
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"
```
Also, `cbind`:
```r
tbl2 = tbl[, c("x1", "x2", "x3"), with = FALSE]
colnames(tbl2) = c("y1", "y2", "y3")
task$cbind(tbl2)
task$levels("y2")
```
(same as above).

**Comment by mllg** [comment]
Technically, the levels are still there:

```r
private = function(x) {
  x$.__enclos_env__[["private"]]
}

private(task$backend)$.data$x2
```

The question is how to deal with this. This problem gets worse if you consider data bases as backend, where you basically have to restore the factor levels after fetching the data.

We might need to discuss this in a larger group soon.
