### ISSUE TITLE
CRAN release date

### ISSUE THREAD

**Issue by jangorecki** [mlr-org/mlr3#181]
mlr3 package looks very promising. Use of data.table from inside R6 is something I was exploring in some of my packages and found it very convenient. Although none of those packages is on CRAN, and having mlr3 on CRAN would be useful for our reverse dependencies checks. Is the date of submission to CRAN known already? I could be worth to even release "beta version", making clear that till 1.0 version API might change.

**Comment by mllg** [comment]
I'm also quite amazed how well R6 and `data.table` work together. It really changed the way how we construct objects and think about operations on them. 

We are aiming to get a release out before the UseR in July. In the meantime be assured that we will report any problems with `data.table()` upstream ASAP.

**Comment by mllg** [comment]
Uploaded to CRAN (still in the incoming queue though).
