### ISSUE TITLE
Assert row_ids to be integer?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#19]
This allows auto-incrementation. Rownames can still be saved as extra column. Still unsure about this...

**Comment by jakob-r** [comment]
Pros and cons? Didn't we already discussed it?

**Comment by berndbischl** [comment]
@mllg do whatever is simpler and CLEANS up the api. oi rather have one, welldefined type for this.

**Comment by mllg** [comment]
Works well without a specific type and makes stuff easier with data bases.
