### ISSUE TITLE
$cbind drops data.table key of $feature_types

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#193]
This seems to happen when `$cbind()` adds a column that was removed before using `select()`.
```r
> haskey(mlr_tasks$get("iris")$feature_types)
[1] TRUE
> haskey(mlr_tasks$get("iris")$select(character(0))$cbind(iris[1:4])$feature_types)
[1] FALSE
```

**Comment by mllg** [comment]
Has nothing to do with `cbind()` or `select()`, key is dropped while subsetting in https://github.com/mlr-org/mlr3/blob/master/R/Task.R#L324.
