### ISSUE TITLE
learner default ids

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#194]
the class of a learner is regr.rpart

this is all fine

but should the default id of a learner not maybe only be "rpart"? because in 99% of cases 
"rpart" seems to be enough and "regr.rpart" is overly verbose and long and the user can always set / change this?

**Comment by larskotthoff** [comment]
I actually like it this way. There are many learners that have classif and regr variants (and you might even want to use both variants in a particular context) and it's easier to distinguish between them this way.

**Comment by berndbischl** [comment]
> nd you might even want to use both variants in a particular context) and it's easier to distinguish between them this way.

that last point i really dont see? can you name 1 example? 
and like i said, in that case you could still set ids manually

this is not my most important issue, but currently it seems that you get the verbose ids, and then in plots and tables names are totally redundant, and you have to make them manually shorter again

**Comment by larskotthoff** [comment]
Hmm, I see your point. Well, I don't have a particularly strong opinion either way.

**Comment by mllg** [comment]
> but should the default id of a learner not maybe only be "rpart"? because in 99% of cases
> "rpart" seems to be enough and "regr.rpart" is overly verbose and long and the user can always set / change this?

The id already is only "rpart":
```r
mlr_learners$get("classif.rpart")$id
```

1. `mlr3learners` still uses "[class].[name]". I'll change that.
2. I assume we do not want to have multiple dictionaries (`mlr_classif_learners`, `mlr_regr_learners`) so that we could drop the prefix completely, right?

**Comment by berndbischl** [comment]
> The id already is only "rpart":

great

> 2\. I assume we do not want to have multiple dictionaries (`mlr_classif_learners`, `mlr_regr_learners`) so that we could drop the prefix completely, right?

if that simplies things, i could also live with multiple dicts. because otherwise it becomes weird.
we have then 
- the classname LearnerClassifRpart 
- the id with prefix (used to access the dict)
- the id without prefix, set in the learner

i would rather not have the last 2 things in parallel, seems confusing

**Comment by mllg** [comment]
Ok, here are our options:

1. We stick to one dictionary per base class (i.e., `mlr_learners`, `mlr_tasks`, `mlr_measures`, ...). Dictionary key and id of object: `[task_type].[name]`. 
Drawback: need to rename for plots / aggregations.

2. We have one dictionary per task type (`mlr_learners_classif`, `mlr_learners_regr`, ..., `mlr_measures_classif`, `mlr_measures_regr`, ...). Dictionary key and id of object: `[name]`.
Drawback: unclear to me what to do with objects that work on all tasks, e.g. the `time_train` measure.

**Comment by berndbischl** [comment]
i can totally live with LONG EXPLICIT names/ids. if our system becomes confusing, we should not simplify. so maybe just take classif.rpart.
