### ISSUE TITLE
Task:filter method

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#195]
a) this seems a little bit underdocumented. 

it does not really delete data, but only sets an index set, correct? i would like to read that

b) how do I undo that operation? so I filter a task to the first 10 rows, now I want to have the complete task again? isnt that usefulß

**Comment by mllg** [comment]
a) This was documented in a separate section, I've added references to make this more clear.

b) Currently, you cannot undo this. I struggled to come up with a realistic setting where this is useful. However, if needed, I could also implement a `split()` operation for tasks. Also note that you can always clone your task before filtering it.

**Comment by berndbischl** [comment]
b) read this issue and read the README of pipelines
https://github.com/mlr-org/mlr3pipelines/issues/147

this was @mb706 first example. it looks very "complex" for what is being done: simple definition of train test sets. 
is there a better way to achieve this? i dislike how complex the code looks there.

**Comment by berndbischl** [comment]
and structurally i kinda dislike that i cannot take back an operation.... 
isnt that in general bad design? i mean it seems obvious that i often want to be able to access again the full data?

**Comment by mllg** [comment]
> isnt that in general bad design? i mean it seems obvious that i often want to be able to access again the full data?

Well, it depends. Imagine a task would be a simple data.frame, then the filter operation would we something like 
```r
i = 1:10
task = task[i, ]
```
There also is no way to undo this operation other than assigning to a different variable.


> it looks very "complex" for what is being done: simple definition of train test sets.
> is there a better way to achieve this? i dislike how complex the code looks there.

I agree that this looks quite complex. However, if you directly compare to data.frame tasks the differences are not that dramatic:
```r
task_train = task$clone()$filter(holdout$train_set(1))
task_train = task[holdout$train_set(1), ]

task_test = task$clone()$filter(holdout$test_set(1))
task_test = task[holdout$test_set(1), ]
```
It would of course be possible to provide a sugar function which clones and subsets a task in one go. Or am I missing a more elegant way of doing this operation?

**Comment by mllg** [comment]
I was wrong that you cannot undo the operation:

```r
task$set_row_roles(task$backend$rownames, "use")
```
This is only possible because we only have one relevant row role. Undoing a `select` is not that easy.

**Comment by berndbischl** [comment]
> > 
> 
> Well, it depends. Imagine a task would be a simple data.frame, then the filter operation would we something like
> 
> ```r
> i = 1:10
> task = task[i, ]
> ```

but thats kinda my point... i thought you are NOT throwing away data is in the code above, but bookkeeping the indexset inside of the object? is that wrong? 
and *if* thats true, i find it "strange" that i have to copy the object before?

**Comment by berndbischl** [comment]
> It would of course be possible to provide a sugar function which clones and subsets a task in one go. Or am I missing a more elegant way of doing this operation?


well you should know whats most elegant here as the author :)
i guess if we do a sugar function "split_task" might be best?
maybe we should discuss this 5 secs in a call i need to ask some stuff here
