### ISSUE TITLE
mlr3keras

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr3#200]
Deep learning is getting more and more important. Somewhere I read that you plan to integrate keras/tensorflow into mlr3. Now I don't see anything of "deep learning" in your list of planned extensions of pure mlr3. What do you think about that?

Kind regards,
Markus

**Comment by mllg** [comment]
We definitely want to support deep learning in the future via an extension package. I'll add this to the list of planned extensions.

**Comment by mllg** [comment]
Create the repository here: https://github.com/mlr-org/mlr3keras

**Comment by mareichhoff** [comment]
Super!

 


Gesendet: Mittwoch, 20. März 2019 um 13:52 Uhr
Von: "Michel Lang" <notifications@github.com>
An: mlr-org/mlr3 <mlr3@noreply.github.com>
Cc: "Markus Eichhoff" <e_markus@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [mlr-org/mlr3] mlr3keras (#200)


Create the repository here: https://github.com/mlr-org/mlr3keras
