### ISSUE TITLE
implement `predict()` function for Learner

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#212]
It might be beneficial to implement the `predict.Learner` function in mlr3 so that trained models can be used in packages that are learning algorithm agnostic but expect this standard interface (I believe  https://github.com/christophM/iml is one example?)

**Comment by berndbischl** [comment]
Why is that exactly needed? Iml could implement a mini wrapper. It already does this for mlr2...

**Comment by mb706** [comment]
Maybe other packages rely on the `predict()` interface as well. It is also nice to be consistent with established interfaces.

**Comment by berndbischl** [comment]
But "maybe" is not enough for us to provide a 2nd api? And like I said: if packages really need this, THEY can provide a local wrapper?

**Comment by jakob-r** [comment]
Well it's not about the package (dev) that would need it but maybe an end user that wants to use eg. iml with an mlr3 learner. Of course the user can write the local mini wrapper. Or somebody just writes a mlr3sugar pakage with such things (or a minimal mlr3train package :smile: )

**Comment by berndbischl** [comment]
> that would need it but maybe an end user that wants to use eg. iml with an mlr3 learner. Of course the user can write the local mini wrapper

but the iml developer would and should write that wrapper?

**Comment by RaphaelS1** [comment]
Perhaps some self-promotion here, but you could do this in one line with [R62S3](https://github.com/RaphaelS1/R62S3)
```R
R62S3::R62Fun(Learner, assignEnvir = topenv(), mask = T)
````

Which would create:
`predict.Learner()`
`predict_newdata.Learner()`
`train.Learner()`
`format.Learner()`

**Comment by mb706** [comment]
We may want to be able to handle plain `data.frame`s in the S3 predict function for consistency with everyone else, so I don't believe `predict.Learner` should just call `Learner$predict()`.

**Comment by mllg** [comment]
By popular demand, we now have a predict function. 

@christophM Is there anything else needed to connect IML?

```r
devtools::install_github("mlr-org/mlr3")

library(mlr3)
task = tsk("spam")

learner = lrn("classif.rpart", predict_type = "prob")
learner$train(task)

predict(learner, task$data(1:3), predict_type = "response")
predict(learner, task$data(1:3), predict_type = "prob")
predict(learner, task$data(1:3), predict_type = "<Prediction>")
```

**Comment by christophM** [comment]
I will have to check whether it already works with the generic predict function. Otherwise I will write a small wrapper, as already done for mlr.
