### ISSUE TITLE
Choosing the parallelization level

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#229]
Looks like this is not yet supported, right?

Which way do you prefer?
- a call to `options()`
- a standalone `setParallelLevel()` function
- something else?

I guess based on the set level we should add an if statement altering `future::plan()` inside the package and resetting it afterwards? As suggested in `?future::plan()`

**Comment by mllg** [comment]
1. Currently, there is need for a parallelization level: the `benchmark()` function rolls out the individual jobs of the individual resamplings (unlike mlr2). You don't have to decide whether to parallelize the exhaustive grid of tasks/learners or the resampling. `mlr3tuning` just calls benchmark with multiple learners. 
2. It is possible to `plan()` nested parallelization, see https://github.com/HenrikBengtsson/future#nested-futures-and-evaluation-topologies.
3. If really required, the support for levels should go into `future`.

**Comment by pat-s** [comment]
You mean "no need", right?

So in summary, each action (tuning, resample, FS, train, predict) is one "job" on the same hierarchy level and all will be parallelized?

I think we should mention this new behavior clearly in the manual. I'll do it.
