### ISSUE TITLE
Measures: Better help support

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#231]
If I take a look at a measure I would like to see the full name of the measure:

```r
mlr_measures$get("classif.ce")
<MeasureClassifCE:classif.ce>
Packages: Metrics
Range: [0, 1]
Minimize: TRUE
Predict type: response
```

If we create a measures table like in _mlr_, it would be helpful to have a direct link in the output and in `?mlr_measures`.

Alternatively provide a redirection to `?Metrics::<measure name>` if the user calls `?<measure name>`, i.e. `?classif.ce` should redirect to `Metrics::ce`.

**Comment by mllg** [comment]
> If we create a measures table like in _mlr_, it would be helpful to have a direct link in the output and in `?mlr_measures`.

I'm not fond of the idea of storing "links" in the objects. We have a clear naming scheme for the measure help pages, if you want more info, you should go there, this is the dedicated place.

However, I can see that the complete name of the measures (unabbreviated) would be helpful.
@berndbischl We open that can of worms in mlr, do we want to do that again? :worried: 

> Alternatively provide a redirection to `?Metrics::<measure name>` if the user calls `?<measure name>`, i.e. `?classif.ce` should redirect to `Metrics::ce`.

The documentation should already have a link to `Metrics:ce`. A redirect would be kind of confusing.

**Comment by berndbischl** [comment]
> I'm not fond of the idea of storing "links" in the objects. We have a clear naming scheme for the measure help pages, if you want more info, you should go there, this is the dedicated place.
> 
> However, I can see that the complete name of the measures (unabbreviated) would be helpful.
> @berndbischl We open that can of worms in mlr, do we want to do that again?

no, michel is totally correct. we made basically 2 mistake in mlr2 IMHO

a) storing doc info in objects. looked like a nice idea, but was terrible
b) have 5 different slots for names. this was confusing to the user and made the code (and APIs!) bloated and inconsitent

lets pls neither (!) repeat a) or b).

**Comment by berndbischl** [comment]
code can be written to autogen tables, but that code should probably not in mlr3, but the docs pages itself.
but we also do not have to overdo thus. 
if the doc tables in the beginning are manually created, i think thats also absolutely acceptable.

**Comment by berndbischl** [comment]
i would probably implement simple overview tables, where rows then link to individual doc pages, which in turn contain the detail info on a regular R doc page.

i guess at some point one could extract the title from the doc page for the table - but we dont need trhis now if you can read it by simply clicking a link?

**Comment by pat-s** [comment]
> i would probably implement simple overview tables, where rows then link to individual doc pages, which in turn contain the detail info on a regular R doc page.

I do not really know what you mean in detail here.
Overview tables should live in _mlr3book_ and accessible via a link from the R help page of `?Measure`? 

Maybe we should be clear about the workflow of getting help for measures.

@berndbischl 	What would exactly happen if I type `?classif.ce` for example?

Or in other words: How would you query information about a measure currently? `mlr_measures$get("<measure>")` does not have all information and is not intuitive.

**Comment by berndbischl** [comment]
> Overview tables should live in _mlr3book_ and accessible via a link from the R help page of `?Measure`?

sure. why not. 


> @berndbischl What would exactly happen if I type `?classif.ce` for example?

we display a dedicated help page for that measure? or an overview page for all measures

**Comment by berndbischl** [comment]
> Or in other words: How would you query information about a measure currently? `mlr_measures$get("<measure>")` does not have all information and is not intuitive.

you query the docs by ?classif.ce. as always. an either that directly displays an overview table for all measures on one page or links to one.
that basicailly depends on how much info we want to write about each individual measure

**Comment by berndbischl** [comment]
actually.... shouldnt we simply link to the metrics docs? i mean they have all of that info already...?

**Comment by pat-s** [comment]
> actually.... shouldnt we simply link to the metrics docs? i mean they have all of that info already...?

I suggested that in the first post. I am not sure if you can have a direct redirection but a page including the link to the overview table of mlr3book and the link to the documentation of the metrics package when calling `?classif.ce` sounds good.

**Comment by mllg** [comment]
This thread is confusing. Let me try to sum it up ...

What we already had in place:
* a dedicated help page for each measure (`?mlr_measures_classif.ce` - as document in `mlr_measures`)
* A link to the metrics package, if applicable. This link can be found on the individual man pages

What's missing: 

A nice overview table with more information than `as.data.table(mlr_measures)` provides.

**Comment by pat-s** [comment]
> Each measure has an associated help page, see mlr_measures_[id]

Ah I did not see that line.
Should we link some examples in "See also"?

> A nice overview table with more information than as.data.table(mlr_measures) provides.

This should go into mlr3book then, similar to the filter table (and possible others).

Question: Should we put the shortcut `?mlr_measures_classif.ce` into the output of `mlr_measures$get("classif.ce")`?

**Comment by mllg** [comment]
I'll add some links to the respective man pages. Unsure about the printer.

**Comment by pat-s** [comment]
> Unsure about the printer.

The thinking behind this is that up to now I always used `mlr_measures$get(<measure>)` to query information about a measure. 
Would be convenient to have a direct print out of the respective help page shortcut there without the need to search the related measures help pages to find the final call.

**Comment by mllg** [comment]
We would need to tag all measures which have a man page (in comparison to measures which the user implemented). Removing this tags after cloning / inheriting is unfortunately not straight forward.

As the help page is both accessible via `mlr_measures_<id>` and `MeasureClassif[Id]`, is find this sufficiently easy to find.
