### ISSUE TITLE
mlr3::assert_param_set() and paradox::assert_paramset()

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3#232]
It's a bit weird to have both.

```r
assert_paramset(param_set, cl = "Param", no_untyped = FALSE,
  must_bounded = FALSE, no_deps = FALSE)

assert_param_set(param_set, .var.name = vname(param_set))
```

**Comment by berndbischl** [comment]
Agree. Simply remove the mlr3 function?

**Comment by mllg** [comment]
Removed from mlr3 in  c023da2, but shouldn't we rename the paradox function?

**Comment by berndbischl** [comment]
> but shouldn't we rename the paradox function?

i can do that, or you, simply open an issue.
BUT i am not a big fan of adding underscores too much to names....
but i also dont want to drag on the discussion now. if you want it renamed, fine, see above

**Comment by jakob-r** [comment]
renamed to `assert_param_set` in mlr3 and paradox. did not find other occurances so far.
