### ISSUE TITLE
Do we want a mlr3verse package?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3#233]
A single package that has all mlr3 packages as imports so you do not have to load all of them manually and you can install them more easily.
 
...similar to https://github.com/tidyverse/tidyverse ?

If we have this we should probably link it prominently.

**Comment by pat-s** [comment]
I also thought about this some days ago. People also like these kind of wrapper packages...

**Comment by mllg** [comment]
* Would this package also pull in all suggests of the packages? 
* Some packages can be imported (like mlr3learners), but you would need to depend on most packages to attach the namespace.

**Comment by pat-s** [comment]
> Some packages can be imported (like mlr3learners), but you would need to depend on most packages to attach the namespace.

Importing seems enough when looking at the [tidyverse](https://github.com/tidyverse/tidyverse/blob/31e82ced71452e6b96d640d06fdd06ac2148984e/DESCRIPTION) package.

**Comment by pat-s** [comment]
Implemented: https://github.com/mlr-org/mlr3verse
Structure is 90% based on the _tidyverse_ pkg structure.
