### ISSUE TITLE
Handling of missings (in train + predict)

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#238]
Discussed several times in _mlr_:

- https://github.com/mlr-org/mlr/issues/2204
- https://github.com/mlr-org/mlr/issues/1515

AFAICS the current behavior in _mlr_ is the one of this PR: https://github.com/mlr-org/mlr/pull/2099

**Comment by mllg** [comment]
Missings are now handled, with the following policy:

* If a learner is capable of handling missing values during `train()`, it should get the `missings` property.
* Learners which cannot handle missing values in the test set should predict `NA` for these observations.
* Predicting `NA` results in an exception unless you have a fallback learner defined. All rows with `NA` observations are imputed with the predictions of the fallback learner.


I know that this is not perfect, and that there might be some rare occasions where you need more flexibility. However, I believe that this is a statistically sound approach (unlike `na.rm = TRUE` stuff during performance assessment). Additionally, you can always impute missing values with a PipeOp.
