### ISSUE TITLE
Store measures as part of experiment, not as part of task?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#24]
Storing measures as part of the task looked like a good idea first, but complicates things for benchmarks where there are different tasks and different measures. Could be caught at the start of `benchmark()`, but we generally want to be able to fuse rather arbitrary experiments into a BenchmarkResult. Possible next steps:

1. Measures stay as-is, part of the task. Determine the union of all measures in a BenchmarkResult, and calculate missing scores on-demand.
2. Measures are stored as part of experiment, defaulting to the measures of the task. When experiments are combined, update experiments and calculate missing scores.

I currently tend to prefer (2). With (1), there is no natural location to store the measure object, except altering the task which is awkward.

**Comment by jakob-r** [comment]
1) If somebody wants to benchmark over multiple measures it's his fault. The result just contain missing values. Plots and tables should work fine nonetheless:

(e.g.)
```r
library(ggplot2)
set.seed(1)
res = data.frame(perf = runif(50), task = sample(c("a","b"), 50, TRUE), learner = sample(c("A","B"), 50, TRUE), measure = sample(paste0("measure", 1:10), 50, TRUE))
ggplot(res, aes(x = learner, y = perf)) + geom_boxplot() + facet_grid(task~measure)

library(dplyr)
res %>% group_by(learner, task, measure) %>% summarise(perf_mean = mean(perf))
```

**Comment by berndbischl** [comment]
@mllg shall we define what happens now (after hamgout call) an close here?

**Comment by mllg** [comment]
Each experiment now additionally stores the measures (as an extra slot/column). You can now optionally provide a list of measures to `e$score()`, `resample()` and `benchmark()`, with a fallback to `task$measures` to keep the API simple. Note that this can lead to benchmark results with different performance measures (and as a result, missing values in the performance aggregation). Still todo: Add methods to calculate performance values for missing or additional measures.
