### ISSUE TITLE
`mlr_control()`: Specify defaults in help page

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#241]

**Comment by jakob-r** [comment]
Hint: Just parse the `mlr3:::default_mlr_control` object?

**Comment by pat-s** [comment]
My idea was to put a list in the "details" section. What do you mean exactly with "just parse" here?

**Comment by jakob-r** [comment]
parse was the wrong word. I means something like `print(mlr3:::default_mlr_control)`
