### ISSUE TITLE
Typo in MeasureClassifF1.R

### ISSUE THREAD

**Issue by camsique** [mlr-org/mlr3#246]
There is a wrong id in the class definition for the "F1" measure.
Instead of "classif.auc" there should be something else.

MeasureClassifF1 = R6Class("MeasureClassifF1",
  inherit = MeasureClassif,
  public = list(
    initialize = function() {
      super$initialize(
        id = "classif.auc",
        range = 0:1,
        minimize = FALSE,
        predict_type = "prob",
        task_properties = "twoclass",
        packages = "Metrics"
      )
    },

    calculate = function(experiment = NULL, prediction = experiment$prediction) {
      Metrics::f1(actual = prediction$truth, predicted = prediction$response)
    }
  )
)

**Comment by mllg** [comment]
Thanks!
