### ISSUE TITLE
Resampling: Train set, Test set and their performance

### ISSUE THREAD

**Issue by camsique** [mlr-org/mlr3#249]
Mlr supported the predict="both" in resampling (train+test set). And it was also somehow possible to get the measures for both sets.

It would be very useful in my opinion to have this option in mlr3 as well with an explicit choice of train and test set measures. At this the documentation does not explicitly state that the measures returned for resampling are for the test set. That could be confusing.

**Comment by mllg** [comment]
We have an ongoing internal discussion about the final structure of the prediction object and how to support calculating measures after the experiments have been conducted.
As soon as the final structure has crystallized out, several test sets will also be supported.

**Comment by berndbischl** [comment]
@mllg what was our conclusion here? this seems pretty important?

**Comment by mllg** [comment]
Now possible by setting `predict_sets` in learner and measures.
