### ISSUE TITLE
`task$select()` it not consistent about subsetting

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#252]
``` r
library(mlr3)

task = mlr3::mlr_tasks$get("iris")

task$select(task$target_names)
# task modified
task$data()
#>        Species
#>   1:    setosa
#>   2:    setosa
#>   3:    setosa
#>   4:    setosa
#>   5:    setosa
#>  ---          
#> 146: virginica
#> 147: virginica
#> 148: virginica
#> 149: virginica
#> 150: virginica

task = mlr3::mlr_tasks$get("iris")

task$select(task$feature_names)
# task not modified (expect only features, not the "Species" col)
task$data()
#>        Species Petal.Length Petal.Width Sepal.Length Sepal.Width
#>   1:    setosa          1.4         0.2          5.1         3.5
#>   2:    setosa          1.4         0.2          4.9         3.0
#>   3:    setosa          1.3         0.2          4.7         3.2
#>   4:    setosa          1.5         0.2          4.6         3.1
#>   5:    setosa          1.4         0.2          5.0         3.6
#>  ---                                                            
#> 146: virginica          5.2         2.3          6.7         3.0
#> 147: virginica          5.0         1.9          6.3         2.5
#> 148: virginica          5.2         2.0          6.5         3.0
#> 149: virginica          5.4         2.3          6.2         3.4
#> 150: virginica          5.1         1.8          5.9         3.0
```

<sup>Created on 2019-06-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mllg** [comment]
You cannot deselect the target column, which is good?

Do you suggest that mlr3 should raise an exception?

**Comment by mllg** [comment]
ping @pat-s

**Comment by pat-s** [comment]
Yes, just silently doing nothing is not optimal.

I think users will do this often with the aim of printing something without being in the habit that `$select()` subsets the tasks and writes it back in place.

**Comment by mb706** [comment]
I think the current behaviour is fine, but "clone+select" and "clone+filter" functions (i.e. subsetting without modifying the original) could be useful.

**Comment by mllg** [comment]
I've added an assertion and improved the manual. You still have to clone the task yourself, but this is clearly documented.

**Comment by pat-s** [comment]
We will have lots of "fun" with people doing

```
task$select()
task2 = task
```

instead of 

```
task2 = task$clone(deep = TRUE)
task2$select()
```

For a moment I was thinking about removing the target column from the printer of `task$data()` but this is also not elegant...

**Comment by pat-s** [comment]
@mllg 	The new assertions causes internal issues in `mlr3featsel` when using columns named differently than features: https://travis-ci.org/mlr-org/mlr3book/builds/550972917

Maybe the assertion should not check for feature names but raise an error if the target name appears within the columns of `select()`?

**Comment by mllg** [comment]
Tracked down together in a video call, everything should be fine now.
