### ISSUE TITLE
Subset data.table using class fields of tasks

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#253]
Is there something we can do about this?
In its current state `task$target_names` and `task$feature_names` can only be used as printers?

``` r
library("mlr3")
task = mlr3::mlr_tasks$get("iris")
data = as.data.table(task)

# works
names = task$feature_names
data[, ..names]
#>      Petal.Length Petal.Width Sepal.Length Sepal.Width
#>   1:          1.4         0.2          5.1         3.5
#>   2:          1.4         0.2          4.9         3.0
#>   3:          1.3         0.2          4.7         3.2
#>   4:          1.5         0.2          4.6         3.1
#>   5:          1.4         0.2          5.0         3.6
#>  ---                                                  
#> 146:          5.2         2.3          6.7         3.0
#> 147:          5.0         1.9          6.3         2.5
#> 148:          5.2         2.0          6.5         3.0
#> 149:          5.4         2.3          6.2         3.4
#> 150:          5.1         1.8          5.9         3.0

# does not work
data[, ..task$feature_names]
#> [1] "Petal.Length" "Petal.Width"  "Sepal.Length" "Sepal.Width"
```

<sup>Created on 2019-06-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mllg** [comment]
AFAICT there is nothing we can do. We could report the problem upstream though.

**Comment by pat-s** [comment]
Even worse that 2) does not even throw an error but just prints the supplied subset object :eyes:

**Comment by mb706** [comment]
```r
data[, task$feature_names, with = FALSE]
```
?

**Comment by mllg** [comment]
Yes, I personally also prefer `with` instead of the `..` notation. However, as far as I understood it, `with` may disappear from data.table in the future. :cry:

**Comment by pat-s** [comment]
I did not play with `data.table` so far, thanks for the help :+1: 	

> Yes, I personally also prefer with instead of the .. notation. However, as far as I understood it, with may disappear from data.table in the future. cry

Then let's hope that the `..` notation gets fixed until then :D Need to report upstream...
