### ISSUE TITLE
Handle training on featureless task gracefully

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#259]
```r
> Experiment$new(mlr_tasks$get("iris")$select(character(0)), "classif.rpart")$train()
INFO  [18:18:17.658] Training learner 'classif.rpart' on task 'iris' ... 
Error in 1:numclass : result would be too long a vector
In addition: Warning message:
In max(y[!is.na(y)]) : no non-missing arguments to max; returning -Inf
```
don't know to what degree this should be supported; this may go into "backup learner" territory, but is not entirely the same as backup predictions.

**Comment by mllg** [comment]
There are some models which work without features (`lm(x  ~ 1)`), but obviously not all. If the model crashes, the backup/fallback would be triggered. And this is a good thing, I guess.

What would you propose?

**Comment by berndbischl** [comment]
Answer seems very clear to me. The same fallback should happen as in model failure. So we fit a constant learner. If you have customized this to a general fallback learner, also fine.

But this should NOT be a further special case with different behavior. 
And I don't think we should go into the basic learning algorithm down below

**Comment by mllg** [comment]
Should be covered by backup/fallback.
