### ISSUE TITLE
Feature request: `getBMRModels()`

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#261]
From the `BenchmarkResult` object. 

Currently one has to do `BenchmarkResult$data$learner[[1]]$model` which is way too long.

**Comment by berndbischl** [comment]
Actually I think this is absolutely fine for now. What important now is that we show this in one line in the docs or examples

**Comment by berndbischl** [comment]
Well l think a simple getter doesn't hurt he. But that is Michels choice

**Comment by mllg** [comment]
```r
tab = as.data.table(bmr)
tab = tab[task.id == "iris" & learner.id == "classif.rpart"]
map(tab$learner, "model")
```

... I think this is really expressive and flexible. Note that you should not access the `$data` slot directly.

**Comment by berndbischl** [comment]
please note for the record that after thinking about this, I do think that patricks request here can be considered reasonable.

your last 3 lines are actually quite lengthy / verbose for such a standard operation....

its not extremely important / pressing but i guess i am more for adding a getter here, than against it. 
i think

**Comment by pat-s** [comment]
Not pressing, just came across this while doing the transition table.

I think the notation above is quite ok if you use it more often / are used to _mlr3_.
However, think about all the "standard" users and ones that do not use _mlr3_ on a daily basis.
Even if its only the `map()` call - that's why getters exist in the end right? To not have to figure out/remember how to write these two line above.
