### ISSUE TITLE
Feature request: `getBMRTuneResults()`

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#262]
For the `BenchmarkResult` container.

**Comment by berndbischl** [comment]
Obviously this also does not work? As mlr3 cannot know about mlr3tune. Otherwise we introduce a cyclical depency structure

**Comment by berndbischl** [comment]
Close imho

**Comment by pat-s** [comment]
Can't we just require the mlr3tuning NS and error if its not available? If a user calls this getter _mlr3tuning_ is most likely loaded anyways.

**Comment by berndbischl** [comment]
Technically we could. Designwise I still this is probably bad...

**Comment by berndbischl** [comment]
This is definitely an issue for mlr3tuning. it would also help to show the currently necessary code there

**Comment by pat-s** [comment]
What would you propose?

1. Leaving out all such getters because "extension packages" are not known to mlr3
2. No getters at all, just use data.table syntax
3. ???

This is a general discussion and should not discussed here -> added it to the workshop document.

**Comment by berndbischl** [comment]
Ideally 2. Would work. But I am not sure short and simple the code become there. Maybe not enough.

Let's discuss in Toulouse
