### ISSUE TITLE
Feature request: `getResamplingIndices()`

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#264]
From the help page of the mlr fun:

"After you resampled a tuning or feature selection wrapper (see makeTuneWrapper) with resample(..., extract = getTuneResult) or resample(..., extract = getFeatSelResult) this helper returns a list with the resampling indices used for the respective method."

**Comment by mllg** [comment]
Accessing the indices of the outer resampling is now already pretty easy. Do you need indices of the inner resampling also?
