### ISSUE TITLE
Renaming features: task$rename_features

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#268]
Use case: I want to rename features in a task.
I currently see no other option than to extract the data and use replace_features.
In this case the type of the new column is dropped.
Is this intentional?

```r
  tsk = mlr_tasks$get("iris")
  dt = tsk$data(1:150, tsk$feature_names)
  colnames(dt)[1] = "a"
  tsk$replace_features(dt)
  tsk
```

> <TaskClassif:iris> (150 x 5)
Target: Species
Properties: multiclass
Features (4):
>* dbl (3): Petal.Width, Sepal.Length, Sepal.Width
>* NA (1): a

**Comment by mllg** [comment]
Is this necessary for programming, e.g. in pipelines, or just for convenience during your every day data analysis?

**Comment by mllg** [comment]
I've remove `task$replace_features` and will implement a method to rename features.

**Comment by mllg** [comment]
I don't want to do this just for convenience, at least not at the current state of the project. If you come up with a good use case, please reopen.

**Comment by berndbischl** [comment]
@pfistfl can you please still explain why you wanted this

**Comment by mllg** [comment]
This is now implemented as `task$rename()`.

**Comment by ZackBarry** [comment]
Is it possible to use the `task$rename()` method within a pipeline?  One use case that I haven't been able to find any solutions for is to union the results of two PCA branches.  When I've tried this with `gunion` and `mlr_pipeops_featureunion`, only one set of `PCX` columns remains at the end of the graph.  I'd like to be able to rename the output columns from the left PCA branch as "left_PCX" and the right branch as "right_PCX".

Toy example:
`library(mlr3)
library(mlr3pipelines)
library(dplyr)

toy_df <- data.frame(
    homeWins = c(1, 0, 1, 0),
    homeHits = c(13,10,12,11),
    homeHomeRuns = c(0,2,0,0),
    awayHits = c(10,11,14,8),
    awayHomeRuns = c(1,0,1,1)
) %>%
  mutate(homeWins = as.factor(homeWins))

task = TaskClassif$new("toy_task", backend = toy_df, target = "homeWins", positive = "1")

pca_home = po("select", id = "home_cols", param_vals = list(selector = selector_grep("home"))) %>>%
  po("pca", id = "home_pca", param_vals = list(center = TRUE, scale. = TRUE))

pca_away = po("select", id = "away_cols", param_vals = list(selector = selector_grep("away"))) %>>%
  po("pca", id = "away_pca", param_vals = list(center = TRUE, scale. = TRUE))

graph <- gunion(list(pca_home, pca_away)) %>>%
  po("featureunion", id = "all_together") 

graph$keep_results <- TRUE

graph$train(task)
#> $all_together.output
#> <TaskClassif:toy_task> (4 x 3)
#> * Target: homeWins
#> * Properties: twoclass
#> * Features (2):
#>   - dbl (2): PC1, PC2`

**Comment by berndbischl** [comment]
can you please move this to the mlr3pipelines tracker. it fits much better there. and yes, we will make sure that this works, this is an important usecase

**Comment by berndbischl** [comment]
moved 
https://github.com/mlr-org/mlr3pipelines/issues/420
