### ISSUE TITLE
packages for measures

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#27]
currently we seem to say that we want to use the new "measures" package.
do we really want that? during the last call we said we wanted to rather use Metrics

https://cran.r-project.org/web/packages/Metrics/

note that on cran there is also this

https://cran.r-project.org/web/packages/hmeasure/

**Comment by mllg** [comment]
Oh, I mixed them up. Should we prefer `Metrics` over `measures`?

`hmeasure` does not seem to cover a lot of measures.

**Comment by berndbischl** [comment]
https://cran.r-project.org/web/packages/MLmetrics/MLmetrics.pdf

**Comment by berndbischl** [comment]
https://github.com/mlr-org/measures/

**Comment by mllg** [comment]
Metrics it is.
