### ISSUE TITLE
parallelization of learners

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#270]
we would like to have seamless integration of parallel training of learners.

what we should do

- create a property whether a learner can be parallelized
- have a method in learner API "set_parallel(on = TRUE / FALSE)", or a parameter / AB.
but code seems better here. AB? learner$set_parallel = T?
- we could try to have our own futures backend, so mlr3 can switch on parallel training if we are in that backend. then the user only has to specify a futures plan for this

the last seems very nice

**Comment by mllg** [comment]
We have `set_threads()` since some months.
