### ISSUE TITLE
learner API interface: update_internal

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#272]
allow an online update function. the contract should be that
the model slot is set, and n new data points are passed. 

an online trainable model should now have a (fast) update function available

we also need a property "online_update" 

another option would be to handle this in train_internal, and implement a case that the model should be updated if the model slot is set and not NULL. but these might be confusing and error prone

**Comment by jakob-r** [comment]
We can list learners here which learners have such a thing available
- `DiceKriging::update`

**Comment by mllg** [comment]
Duplicate of #622
