### ISSUE TITLE
Possible new backend: disk.frame

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#274]
Sounds interesting: https://github.com/xiaodaigh/disk.frame

**Comment by jakob-r** [comment]
I think @mllg did not see any advantage over dplyr and SQLite.

**Comment by mllg** [comment]
Yep, thats right. Unless there are some convincing benchmarks, I would recommend to stick to SQLite via mlr3db.

**Comment by xiaodaigh** [comment]
> Yep, thats right. Unless there are some convincing benchmarks, I would recommend to stick to SQLite via mlr3db.

What kind of benchmark would you like to see? Speed? Although SQLite is quite nice and before I developed disk.frame I used it for medium data. But the advantage of disk.frame is also that you can use native R functions and not limited by what sqlite provides.

**Comment by jakob-r** [comment]
> But the advantage of disk.frame is also that you can use native R functions and not limited by what sqlite provides.

This does not matter so much as soon as everything is behind a backend, right?
What matters most is access speed. How fast can we get a subset of tabular data into R memory. The queries are not complicated. Just imagine random numeric row index values and maybe sometimes subset of columns. Do you have a benchmark against SQLite?
