### ISSUE TITLE
define logging now

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#28]
we really need thus, pushing that issue back even further is going to hurt us

how about futile.logging?

https://github.com/zatonovo/futile.logger

**Comment by mllg** [comment]
I don't like the dependencies here. I don't see a problem sticking to the very simplistic `info()` and `debug()` for now.

**Comment by dselivanov** [comment]
Check simple logging in [RestRserve](https://github.com/dselivanov/RestRserve/blob/master/R/logging.R) - no extra dependecies. Would be happy to contribute it here.

**Comment by berndbischl** [comment]
shall we put this into a simple extra package? so we can use it elsewhere? "SimpleLogger"?
PS:
thx!

**Comment by mllg** [comment]
https://github.com/daroczig/logger looks good.

**Comment by dselivanov** [comment]
agree, looks nice!

**Comment by mllg** [comment]
We use `logger` for now. An alternative which also popped up lately is yog: https://github.com/s-fleck/yog.
