### ISSUE TITLE
Reflection: How do I convert from task.type to task.type 

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#284]
- mlr3 should provide a task converter *Regr* -> *Classif* via Binning. 
  This is mainly for testing purposes.

- Converters should be obtainable via a reflection mechanism

- mlr3ordinal can then implement ordinal -> regr; ordinal -> classif;
- mlr3xyz can implement other relevant converters

- mlr3pipelines will implement a `PipeOpConvertTask(to = ...)` that uses the respective converter

Same nature as #283 #277

**Comment by berndbischl** [comment]
> * mlr3 should provide a task converter _Regr_ -> _Classif_ via Binning.
>   This is mainly for testing purposes.

really? shouldnt this be in pipelines? i dont see a reason why this should be a feature of mlr3?

**Comment by pfistfl** [comment]
We can also place it in pipelines.
My reasoning was that if the lookup-dictionary lives in mlr3, all packages that implement a conversion can write into this table when loading.

Otherwise, all converters would have to also import mlr3pipelines I guess (Which most of them might anyways)

**Comment by berndbischl** [comment]
i would rather put this in pipelines as this might also involve (more complex) tasks that live "below" mlr3 in the extension structure. so like amultilabel task. mlr3 cannot "talk" about such things as it does not know them

**Comment by pfistfl** [comment]
This is the thing: mlr3 does not need to know about those things.
The respective packages just insert stuff into a dictionary when loaded. 

In case we put the lookup into pipelines, all packages that introduce a converter need to depend on pipelines. 
I feel pipelines is a quite big dependency. 

Should I put it into pipelines for now? I think we can still move this at a later point.

**Comment by mllg** [comment]
I agree with @pfistfl. This should go into `mlr_reflections`.

**Comment by berndbischl** [comment]
I think we should mark this for discussion

**Comment by berndbischl** [comment]
But go ahead now with a proposal

**Comment by mllg** [comment]
Implemented in f9b5b22a72e646f8341378c814bffa7107acec84.
