### ISSUE TITLE
We need coding doc and style guidelines

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#295]
It is imperative that we publicly document this for all of our own team but especially external people who would like to help.

We seem to have:

https://github.com/mlr-org/mlr3/wiki/Roxygen-Guide
https://www.notion.so/Style-Guide-740bc663207a4bbb9a457987bda6fd91
https://www.notion.so/Developer-Guide-65e60b651a2e44e89a36b72df92158ea
https://github.com/rdatsci/PackagesInfo/wiki/R-Style-Guide

All of this need to be unified and to live in the mlr3 wiki @pat-s

**Comment by pat-s** [comment]
Done.

**Comment by berndbischl** [comment]
its not done we also need to review this a bit

**Comment by berndbischl** [comment]
(but thx for moving it to the wiki already!)
just want to discuss it a bit during the sprint

**Comment by berndbischl** [comment]
we are reviewing them now, i think the issue can go
