### ISSUE TITLE
ci guide and devel team in wiki are still on notion

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#297]
should be transferred

**Comment by pat-s** [comment]
I would at least leave the "devel team" there because we cannot create a similar visual appealing list of team members in the wiki.

**Comment by pat-s** [comment]
CI Guide now in the wiki. mlr wiki also links to the mlr3 CI guide page.

**Comment by berndbischl** [comment]
No not multiple systems just for that

**Comment by berndbischl** [comment]
@pat-s can you copy the team over too pls? so we can close here.
curremtly it is simply a list of names and pcis

**Comment by pat-s** [comment]
done

**Comment by berndbischl** [comment]
THANKS
