### ISSUE TITLE
Transparently switch task columns off and on

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#301]
mlr3pipelines has the `affect_columns` functionality which lets a user choose that a PipeOp should only affect a certain subset of available feature columns in a task.

Internally this works by switching the "col_role" of all features that are not to be affected to `character(0)`, performing the operation, and switching the role back to `"feature"`:
```r
task$set_col_role( not_affected_cols , character(0))`
do_pipeop_operation()
task$set_col_role( not_affected_cols, "feature")
```

However, this does not seem to work if `do_pipeop_operatio()` uses the task's `$cbind()` operation. Example code:
```r
task = mlr_tasks$get("iris")$
  set_col_role("Sepal.Length", character(0))$
  cbind(data.table(x = 1:150))$
  set_col_role("Sepal.Length", "feature")
task$data()
```
this gives an error on the `task$data()` line:
```r
Error: DataBackend did not return the cols correctly: 6 requested, 5 received
```
Expected output:
```r
       Species Petal.Length Petal.Width Sepal.Length Sepal.Width   x
  1:    setosa          1.4         0.2          5.1         3.5   1
  2:    setosa          1.4         0.2          4.9         3.0   2
  3:    setosa          1.3         0.2          4.7         3.2   3
```
(maybe with columns in different order)

The information about switched-off columns seems to survive *somehow*, because `$set_col_role` would fail if the task didn't know about the column at all:
```r
> task = mlr_tasks$get("iris")$
+   set_col_role("Sepal.Length", character(0))$
+   cbind(data.table(x = 1:150))$
+   set_col_role("Sepal.Length.xxx", "feature")
Error in task_set_col_role(self, cols, new_roles, exclusive) : 
  Assertion on 'cols' failed: Must be a subset of {'..row_id','Petal.Length','Petal.Width','Sepal.Length','Sepal.Width','Species','x'}, but is {'Sepal.Length.xxx'}.
```

**Comment by mllg** [comment]
Fixed in 5219a7f25e7cb3d7c8f84e5bd7bdcf4a9cbbc778, test in 52d5e61.
