### ISSUE TITLE
Preprocessing within mlr3

### ISSUE THREAD

**Issue by konradsemsch** [mlr-org/mlr3#304]
I checked the list of mlr3 extensions and mlr3 itself and I couldn't find a package that would be responsible for data preprocessing (something that ```recipes``` offers) - did I miss such or how is it eventually intended to be done in the mlr3 framework?

**Comment by pat-s** [comment]
Hi,

[mlr3pipelines](https://github.com/mlr-org/mlr3pipelines) is the pkg for preprocessing (and everything related to dataflow/worklflow management). 
I'll add a note to the page to make it more clear. Thanks!

**Comment by konradsemsch** [comment]
My bad then and thanks for clarifying!
