### ISSUE TITLE
Get rid of `mlr_control()`?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#306]
After the learners have been refactored, there is only one option currently left in `mlr_control()`: `store_models`. If we move this into the learner,  we

1. have a more fine grained control over which models to store, and
2. we can completely get rid of the control object.

Any objections?

@berndbischl @pat-s @mb706

**Comment by pat-s** [comment]
> have a more fine grained control over which models to store

Sounds nice but in practice one would either store all models or none I guess. But this point is neither positive nor negative for the overall discussion imo.

> we can completely get rid of the control object.

The question is: Do we want to have an overall object storing controls/global settings? The other way would be directly via `options()`. I assume you discussed this already previously?

In mlr we had

```r
getMlrOptions()
## $show.info
## [1] FALSE
## 
## $on.learner.error
## [1] "stop"
## 
## $on.learner.warning
## [1] "warn"
## 
## $on.par.without.desc
## [1] "stop"
## 
## $on.par.out.of.bounds
## [1] "stop"
## 
## $on.measure.not.applicable
## [1] "stop"
## 
## $show.learner.output
## [1] FALSE
## 
## $on.error.dump
## [1] FALSE
```

While all the "par" options are gone, we could still support passing verbosity options and things like "on.learner.error" and others?

**Comment by mb706** [comment]
For Graphs in mlr3pipelines the control object given to e.g. `resample()` would only ever control the outer-most learner, but it might give the expectation that it controls the learners *inside* the Graph. It may make sense to have things that change common learner behaviour under a `$control` slot, so the user can do things like
```r
learner1 = LearnerXY$new()
learner1$control = mlr_control(store_models = FALSE, other_option = TRUE)
```
as well as
```r
learner2 = LearnerXY$new()
learner2$control$store_models = TRUE
learner2$control$another_option_entirely = -1
learner3 = LearnerXY$new()
learner3$control = learner2$control
```
