### ISSUE TITLE
Graph support in assert_learner?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#311]
Maybe we want `assert_learner()` to automatically convert a `Graph` to a `Learner`? In that case I would suggest the `assert_learner` should be an S3 method, and then I would implement `assert_learner.Graph` in mlr3pipelines.

**Comment by mllg** [comment]
Sugar and S3 do not mix well here. E.g., for `benchmark()`, you provide a list of objects to convert... Any ideas?

**Comment by berndbischl** [comment]
it seems like client packages must be able to overwrite code here / register in dicts.
how do we do that for other tasks like survival? they register in the mlr_learner dict, right? then everything works automatically

**Comment by berndbischl** [comment]
the dict needs a configurable piece of code so I can say / register in a subpackage:
if an object of class X comes in, here is the piece of code to tranform it into a learner?

**Comment by mb706** [comment]
How about there is an S3 method `as_learner()` that just converts / throws an error if not possible (and that other packages can extend), and an `assert_learner()` that calls `as_learner()` and does further checking for properties, task type etc. `assert_learners()` could just `lapply` its arguments and collect errors using `tryCatch` to sjow info about the failed conversions / checks.

**Comment by berndbischl** [comment]
i dont know, if this does not fit in, live with one extra line of converter code for now?

**Comment by mllg** [comment]
We have now `as_learner` as S3 method.

**Comment by mb706** [comment]
[already implemented](https://github.com/mlr-org/mlr3pipelines/blob/630ea4a669262905f169eff80cabec748798bd51/R/GraphLearner.R#L105); I thought it would be neat to have `GraphLearner` also shown in `as.data.table(mlr_learners)`.
