### ISSUE TITLE
reference to constructors for different task types in reflections

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#313]
[This](https://github.com/mlr-org/mlr3pipelines/blob/c2b5c5b677513a58dad98e5d9085fee7bfc3f920/R/zzz.R#L16-L20) is something I use for GraphLearner task type inference, maybe it could go into mlr3? In theory it could also just contain the class names of each constructor, but I worry that at some point I would need the constructors for some reasons. (In that case there should at least be a column "package")

**Comment by mllg** [comment]
I'd strongly favor to put strings in here. As you suggested, together with the package name. Then you can always just use `get(..., envir = pkg)` to get the constructor.

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr3/commit/f9b5b22a72e646f8341378c814bffa7107acec84#diff-2395f7bc067e512fd820136b063099d8R21

Ok for you?

**Comment by berndbischl** [comment]
i read michels new version, i think this is a very useful features.
just to make sure: extensions packages CAN write into that table? correct?
(eg survival)

and please make sure to document the reflection now

**Comment by mb706** [comment]
Ok with me
