### ISSUE TITLE
how to upcast RR to BMR

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#314]
i see that an ResampleResult can be combined with a 2nd RR to a BMR - which is good.
but how do I upcast a single object? 

isnt THAT the relevant operation? and thats missing? (and the BMR already has a "combine" method)

how about as_BenchmarkResult(rr)?

**Comment by mllg** [comment]
I never needed to convert a single RR into a BMR. Do you have a use case?

**Comment by berndbischl** [comment]
it is a type-completeness argument foremost? 
it is simply "logical?"
and the natural usecase is a loop, where you start with an initial 
whats your usecase where you need to combine 2 RRs? 

you have type A, which can be upcast to type B.
this is your system.
b = c-upcast(a1, a2)

this is mine
b = c((B) a1,  (B) a2)

the latter seems much more natural? one operation for one purpose.
you implement a conflation: c-upcast

**Comment by mllg** [comment]
Removed `rr$combine()`, added S3 `as_benchmark_result()`.
