### ISSUE TITLE
BMR: hashes and unique RR-rows / blocks

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#315]
hashes in the BMR seem to be PRETTY important as they define which rows belong together to form one RR in a BMR

a) at least it seems under-documented how exactly the has is formed. that should be fixed

b) i am not sure if we have a problem here.
what happens if I tun the SAME experiment twice? same task, same learner, same resampling.
that can happen e.g. at least in tuning. now this is treated (wrongly) as one BMR and not 2? that seems bad

**Comment by berndbischl** [comment]
further thoughts:
- how can i even ask about the contained hashes in a BMR? yes i can do unique(bmr$data$hash) but that seems such a central operation for programming that an AB might be in order?

**Comment by berndbischl** [comment]
it seems to be pretty bad, that i am allowed to apparently bind RRs with the same hashes and then create an "illegal" object. 

I can do this here:
```
task = mlr_tasks$get("iris")
lrn = mlr_learners$get("classif.rpart")
measure = mlr_measures$mget("classif.ce")
rs = mlr_resamplings$get("cv", param_vals = list(folds = 2))


rs$instantiate(task)
lrn$param_set$values = list(cp = 0.7)
r1 = resample(task, learner, rs)
print(r1$hash)
lrn$param_set$values = list(cp = 0.7)
r2 = resample(task, learner, rs)
print(r2$hash)
b = r1$combine(r2)
```

yes this creates a warning, but after that i seem to be pretty screwed:

```
h = b$data$hash[1]
rr = b$resample_result(h)
```

the "b" object seems to be broken now, accessing this retrieves a CV object, where parts of it tell me it has 4 folds, other parts tell me it has 2, and so on

**Comment by berndbischl** [comment]
i have also written this here in mlr3tuning, and i am pretty sure being able to ask for number of different RR experiments should live in mlr

```
  active = list(
    n_evals = function() {
      if (is.null(self$bmr)) 0L else self$bmr$data[, data.table::uniqueN(get("hash"))]
    }
  )
```

**Comment by mllg** [comment]
> it seems that unique hashes seem to be a precondition for the operation, then this should result in an error not a broken state

So turn the warning into an error? No problem.

**Comment by mllg** [comment]
> i have also written this here in mlr3tuning, and i am pretty sure being able to ask for number of different RR experiments should live in mlr

This is the same as `uniqueN(bmr$data$hash)` or `nrow(bmr$aggregate())`... I don't see how this helps here, but you get an AB: `bmr$hashes` -> `length(bmr$hashes)`.

**Comment by mllg** [comment]
See a66aa31.

**Comment by berndbischl** [comment]
> So turn the warning into an error? No problem.

sure, but now you conceptually and obviously break mlr3tuning

**Comment by berndbischl** [comment]
> See [a66aa31](https://github.com/mlr-org/mlr3/commit/a66aa314f9af26826c1b4b0572a2b1bc2422dc4d).

that already helps. good.

**Comment by mllg** [comment]
Conclusions after discussion:

* This is now an error, not a warning.
* I exported a helper function to calculate the hash based on a task, learner and resampling object: `hash_resampling_result()`.
