### ISSUE TITLE
BMR: in tuning i need to be able to talk about the order of RRs contained in the BMR

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#316]
but that seems to be impossible? i would like to access the 1st, 2nd RR in the BMR

**Comment by mllg** [comment]
For tuning, at some point we just added extra columns to the BMR (date of birth). IDK how to order resample results otherwise, especially if the BMR is created by `benchmark()`.

**Comment by mllg** [comment]
Yu can now access RRs via their position: `bmr$resample_result(<int>)`. The hash is now mostly hidden from the user. Instead you get an integer column in the results (`"nr"`). To translate this into hashes, just call `bmr$hashes[data$nr]`, but this should not be required often.

**Comment by berndbischl** [comment]
1. you didnt update the docs of resumple_result
2. if hashes are now mainly hidden from the user (which is guess is good), it seems weird for a function with a positional arg not to be able to ask about the length / size of the container directly. i would suggest an active binding for this
