### ISSUE TITLE
RR: should have AB "learner"

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#317]
the RR only refers to a single learner. 
it seems weird to force the user to do this
  
rr$data$learner[[1L]]

**Comment by mllg** [comment]
NB: There already is `rr$learners`.

**Comment by mllg** [comment]
Options:

* `rr$learner` returns an untrained learner. As we do not store the untrained learner, we would have select one, clone it and then overwrite its state. If the stored model is large, this operation is quite expensive, which might be surprising for users (and developers).
* `rr$learner` returns the first trained learner. But then we are just blowing up the API to avoid writing `[[1]]`?

**Comment by mllg** [comment]
Closed after discussion.

**Comment by berndbischl** [comment]
i am actaully unsure whether this should not maybe be provided.

> * `rr$learner` returns an untrained learner. As we do not store the untrained learner, we would have select one, clone it and then overwrite its state. If the stored model is large, this operation is quite expensive, which might be surprising for users (and developers).

i think there might be arguments for doing this.
 
well, maybe not now. if this comes up again, i will reopen this
