### ISSUE TITLE
BMR:best seems misspecified

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#320]
it doest really make sense to select the "best" run across tasks?
IMHO if this unclear, this should be removed. 
in mlr3tuning this function might make sense.

the other option is to return a table of best results per task

**Comment by berndbischl** [comment]
also: what happens in case of ties? thats not even documented, and I dont think you want to sample here (= in mlr3 / BMR). in tuning i might want this, but i would delegate to this method if it exists.

seems further evidence to remove this here

**Comment by mllg** [comment]
Removed the previously for tuning request method `best()` from mlr3 again ( f8f3bceecf367f0b5665b8bf72cc07f43398e4d2).
