### ISSUE TITLE
inconsonsistent docs about where sugar-string can be passed

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#322]
Often you write this:

from resample.R
```
#' @param task :: [Task]\cr
#'   See also [mlr_sugar].
#' @param learner :: [Learner]\cr
#'   See also [mlr_sugar].
#' @param resampling :: [Resampling]\cr
#'   See also [mlr_sugar].
```

In other places the reference to "sugar" is forgotten.
this needs to be consistent.
shouldnt we remove the reference in the indiviual places? and explain this once globally?
because this will never stop. this link must now ALSO be provided in ALL client packages.
will we really make sure that this is correct?

**Comment by berndbischl** [comment]
example where its missing:
BMR: performances, but probably more places

**Comment by mllg** [comment]
I don't see how it would help to not provide the link at the relevant places. Without the additional link, the type specification is just plain wrong.

**Comment by berndbischl** [comment]
Option a) make it consistent then at least in mlr3, lets option issues in the other packages

Option b) Linking to something else instead of [Task]? I guess thats not woth the effort? 

a?

**Comment by berndbischl** [comment]
I guess its option "a". but your docs are still wrong.
if you follow the mlr_sugar link from any function that also allows a string, nowhere on ?mlr_sugar
do you explain this. you talk about dictionaries. which are (for the user) completely unconnected to passing an a string to an arg

**Comment by berndbischl** [comment]
ok the info can potentially be guessed from the doc page, but its too short IMHO and needs to be clarified there
