### ISSUE TITLE
BMR: resample_results

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#323]
sorry for being a dick about this  but i want to rather say this now

the name seems (quite) bad.
nearly all other similar names imply I get a list of objects of that type ($hashes, $measures, etc, 1000 more)

this give me a size-number

call it n_resample_results or similar pls

**Comment by berndbischl** [comment]
also: can you please ensure, maybe also thru a test that this returns 0 and not NULL for an empty BMR?

**Comment by mllg** [comment]
Renamed to `$size` in fdd60d2. Okay for you?

**Comment by berndbischl** [comment]
> Renamed to `$size` in [fdd60d2](https://github.com/mlr-org/mlr3/commit/fdd60d2a949d32795ec36d870597d0628a9b8d32). Okay for you?

well.......... not really? maybe? n_resample_results seems to be much clearer....
"size" is now easily confusable with "number of rows".....

sorry....

i could live with size, but i guess the comments above still stand...

**Comment by berndbischl** [comment]
> maybe also thru a test that this returns 0 and not NULL for an empty BMR?

and please really do this, too
