### ISSUE TITLE
mini request benchmark iteration info logger

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#324]
INFO  [22:10:15.416] Applying learner 'classif.rpart' on task 'iris' (iter 1/1)

Could you display (with as_short_string?) the param_set$values too pls?
this might cost an extra line but i thinks its worthwhile - and would help in tuning

**Comment by berndbischl** [comment]
@mllg finish soon?

**Comment by mllg** [comment]
We use a hierarchical logger.
