### ISSUE TITLE
mlr_learners$add(required_args = ) prevents as.data.table(mlr_learners)

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#328]
Related to #177

Adding the `mlr3pipelines` `GraphLearner` to `mlr_learners` (which requires a `"graph"` argument) prevents `as.data.table()` to work on `mlr_learners`:
```r
> mlr_learners$add("graph", GraphLearner, required_args = "graph")
> as.data.table(mlr_learners)
Error: Need argument 'graph' to construct 'graph'
```

**Comment by mllg** [comment]
Two possibilities to solve this:

1. Let `as.data.table()` skip those objects where requirements are not met.
2. Try to find a stupid default for Graph, and pass it as `mlr_learners$add("graph", GraphLearner, graph = DummyGraph())`.

**Comment by mb706** [comment]
I like 2, it is basically what I am also doing in mlr3pipelines, but to some degree it may make sense to have 1. in a way: fill the fields except the key with NA (because really the `predict_types` of a `GraphLearner` could be anything). If you say you would not really want `GraphLearner` in `mlr_learners` I could also take it out again.

**Comment by mllg** [comment]
Option 2. is already implemented. What is the issue exactly?

**Comment by mb706** [comment]
That would be very close to just giving the `Graph` constructor a default argument. I would want the user to get an error for `mlr_learners$get("graph")`.

**Comment by berndbischl** [comment]
should the graphlearner really be in the dict AT ALL? 
my feeling is: no?

**Comment by berndbischl** [comment]
you seem to have dicussed this in #177 but i guess i am against this
the GL is semantically something completely different than the basic learners in there?

**Comment by mllg** [comment]
Have we agreed to not add the GraphLearner to the dict?

**Comment by berndbischl** [comment]
like i said, i wouldnt do this

**Comment by mllg** [comment]
Then lets just not do it.
