### ISSUE TITLE
Add all the hidden files to .Rbuildignore

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#33]
Clutters the Appveyor builds: https://ci.appveyor.com/project/mllg/mlr3/build/1.0.83#L470

**Comment by mllg** [comment]
The files are already in the Rbuildignore. Is R CMD check called on the directory, not the tarball?

**Comment by pat-s** [comment]
> Is R CMD check called on the directory, not the tarball?

Yes, on the directory.

**Comment by mllg** [comment]
Well, this does not work. ^^

**Comment by pat-s** [comment]
But we do exactly the same on travis and there are no complains about all these files?

I am aware of the 

R CMD build mlr3
R CMD INSTALL mlr3_*.tar.gz
R CMD check mlr3_*.tar.gz

scheme. *tic* is just using *rcmdcheck* for checking which calls by default "R CMD check" on the directory (or am I wrong here??): 


```
rcmdcheck(path = ".", quiet = FALSE, args = character(),
  build_args = character(), check_dir = NULL, libpath = .libPaths(),
  repos = getOption("repos"), timeout = Inf, error_on = c("never",
  "error", "warning", "note"))

path | Path to a package tarball or a directory.

```

but also calls a R cmd build visibly in the builds before the R cmd check? This would not be necessary then. I am confused.

**Comment by mllg** [comment]
Appveyor now seems to work (unless pandoc crashes).
