### ISSUE TITLE
missing description/explanation for predict_types/learner_properties

### ISSUE THREAD

**Issue by mboecker** [mlr-org/mlr3#331]
Although there is material on which predict_types exist, there is almost no documentation on what the different predict_types (response, prob, se) mean. While response and prob are probably clear to most users, I can't find any information on what SE is supposed to mean. Therefore I'd like to request that some descriptions on that are added to, for example, https://mlr3.mlr-org.com/reference/mlr_reflections.html.

This is also true for some learner_properties: twoclass/multiclass and missings being clear to most users, and importance/oob_error needing some explanation.

**Comment by pat-s** [comment]
I do not think that it is our responsibility here to document these types. This is rather general R knowledge on modeling terms that are used in every package. 
Users should know upfront what they want to do and what the respective types mean. 

Let's see what @berndbischl and @mllg 	think about this.

**Comment by mboecker** [comment]
yeah it's possible that my experience here doesn't reflect that of a typical new user. if you all agree please disregard this issue. I just want to note that I dont want a lot of text about each option but rather a short, one sentence explanation or a pointer on what to google for.

**Comment by pat-s** [comment]
No problem, always good to ask :+1:

**Comment by berndbischl** [comment]
> I do not think that it is our responsibility here to document these types. This is rather general R knowledge on modeling terms that are used in every package.

huh? no of course we need to doc this? also is this covered in the book?

**Comment by berndbischl** [comment]
i mean we dont have to explain what a probability is, or what a "posterior probability" is.
a user needs to know that from ML
(in the book we could add 2-3 more brief sentences about the context)

but we do have to explain what comes back technically and so on?
where are the relevant part of the docs currently and whats in the book. then i will check

**Comment by mboecker** [comment]
https://mlr3book.mlr-org.com/learners.html has one sentence each about predict_types and learner_properties.

https://mlr3.mlr-org.com/reference/Learner.html links to https://mlr3.mlr-org.com/reference/mlr_reflections.html where a list of the available options is given.
I would add an explanation of the different types here.
I would also add a link in the book to that page for users who want/need more information.

**Comment by mllg** [comment]
2d3f08a3fc3fd1948d50552e0a01c6a7fc92a88e has added some explainations to the docs. @mboecker can you add some info to the book?

**Comment by mllg** [comment]
There is now a PR for mlr3book, closing here.
