### ISSUE TITLE
param_set and param_values

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#337]
the contructor of many objects (learner, and so on) now contains args
"param_set" and "param_values"

this is inconsistent as "param_values" is already a member of "param_set"

this is hopefully (?) only internal code, but we should adress this very quickly as this will change will maybe break other packages....

can we pls discuss this soon?

**Comment by berndbischl** [comment]
i guess we could do the internal change, leave the 2nd argument in the constructor for downstream packages, then fix the downstream packages and remove it fully?

this would then not break cran.

its mildly annoying but doable?

**Comment by mllg** [comment]
I don't know if this is currently worth the hassle without knowing what happens with paradox.

**Comment by berndbischl** [comment]
I don't think that this feature will ever be removed. Raphael had the same approach in his code too. He stored the values inside of his data table for the set.
