### ISSUE TITLE
performance methods in  RR and BMR

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#338]
i find this a bit inconvenient that you always get the full table back, with all involved objects in cols.

this is especially true for an RR where I already know usually what is in the RR.

and removing this to only the relevant performance cols seems a bit tedious.

see this here for example, a simple RR, I only want the vector of perf values

rr : ResampleResult
ms : list of measures

rr$performance(measures = ms)
mids = map_chr(measures, "id")
rr[, mids, with = FALSE]

like this? not so great?

can we at least add an option to the functions so this is done internally?

i guess this also concerns BMR$aggregate?

**Comment by berndbischl** [comment]
actually in the code snippet above i must also do "as.numeric" to transform it into a vector?

**Comment by berndbischl** [comment]
i arrived at this here :(

      set_names(as.numeric(rr$performance(self$measures)[, mids, with = FALSE]), mids)

**Comment by mllg** [comment]
>   set_names(as.numeric(rr$performance(self$measures)[, mids, with = FALSE]), mids)

IDK what you are doing.

* `rr$performance(self$measures)[, mids, with = FALSE]` returns a data.table. If you want a vector, just access the column with `[[`?

* `as.numeric()` gives me an error. AFAICT `is.numeric.data.table()` is not possible. Do you mean to call `as.matrix()`?

* `set_names()` is getting a vector (or matrix?) and the measure ids. Unsure what you are trying to do, but you should provide as many names as there are elements in the vector, or use `colnames()` instead for a matrix.

**Comment by mllg** [comment]
Closing here, lets resume this on slack if required.

**Comment by berndbischl** [comment]
i woud like to keep this open for the call tomorrow we can close then pls, but i need to see this
