### ISSUE TITLE
why are we still allwoing conversions from string in public method API

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#340]
in nearly all mlr3 function i see this:

```
resample = function(task, learner, resampling, store_models = FALSE) {
  task = assert_task(as_task(task, clone = TRUE))
  learner = assert_learner(as_learner(learner, clone = TRUE), task = task, properties = task$properties)
  resampling = assert_resampling(as_resampling(resampling))
  assert_flag(store_models)

```

shouldnt the as_* function calls be very quickly removed? as they are illegal now?
i see its deprecated, but we dont we fix our own code then?

**Comment by berndbischl** [comment]
this also confuses and block me in mlr3tuning...

**Comment by berndbischl** [comment]
i also think that a function like assert_measures needs an upscale option from a single object to a list? this is unfortunately really blocking now....

see 
https://github.com/mlr-org/mlr3tuning/issues/181

**Comment by mllg** [comment]
The upscale method from single object to list is `as_[obj]()`. See https://github.com/mlr-org/mlr3/blob/master/R/mlr_coercions.R for all `as_[obj]()` methods + https://github.com/mlr-org/mlr3/blob/master/R/deprecated.R for the deprecated string converters which will be removed as soon as mlr3pipelines made the transition.

The `as_[obj]()` methods are also intended to convert a graph to a GraphLearner, or to make a filter a POFilter.

Some `as_[obj]()` calls are admittedly not really helpful at the moment. However, I think that distinguishing between assertion and coercion is a clean approach here, and S3 makes it flexible and future proof.

**Comment by berndbischl** [comment]
0. this is certainly not a "question" but critical API.

1.
currently mlr3 allows this.
resample("iris", "classif.rpart", "holdout")
we aggreed that this is NOT OK.
(yes, its deprecated, but see below. and why do we support deprecated stuff in our own code currently)

2. problem 1. happens because the code in mlr3 is wrong. problem is:
this code if often copied to downstream packages. and it is unclear how this is now to be written.
as this is absolute essential code, this blocks development now.

3. why are we waiting for the (yet unfinished) pipelines to clean this up?

**Comment by berndbischl** [comment]
the point is: 
how am i to write the assert for this function?
f = function(learner)
and for this here
g = function(measures)

**Comment by berndbischl** [comment]
my guess would be

f: assert_learner(learner)
--> here is nothing to do, there are no converters. i can do this, its just that this is NOT how the current code in mlr3 looks like, and also not the beginning code in tuning, and probably other places, too. so this needs to be cleaned up,

g:
i guess:
assert_measures(as_measures(measures)) 
because i need the upscaling to the list?

**Comment by mllg** [comment]
> currently mlr3 allows this.
> resample("iris", "classif.rpart", "holdout")
> we aggreed that this is NOT OK.

Yes, it works **with a warning**. Some packages are already on CRAN, hence I have to deprecate stuff before removing it.


> 1. problem 1. happens because the code in mlr3 is wrong. problem is:
>    this code if often copied to downstream packages. and it is unclear how this

From my perspective, everything is fine with the code.

> 2\. why are we waiting for the (yet unfinished) pipelines to clean this up?

I'm not waiting, it is deprecated. If you see a warning, better fix the code.

**Comment by mllg** [comment]
> f: assert_learner(learner)
> --> here is nothing to do, there are no converters. i can do this, its just that this is NOT how the current code in mlr3 looks like, and also not the beginning code in tuning, and probably other places, too. so this needs to be cleaned up,


> g:
> i guess:
> assert_measures(as_measures(measures))
> because i need the upscaling to the list?


For an internal function, use `f`. For an exported function, use `g`. If in doubt, use `g`.

**Comment by berndbischl** [comment]
also you didnt answer the most relevant post above.....

**Comment by berndbischl** [comment]
> If in doubt, use `g`.

can we PLEASE talk about this? this sound weird....

**Comment by berndbischl** [comment]
> Some packages are already on CRAN, hence I have to deprecate stuff before removing it.

whats the list of stuff that uses the deprecated API? have issues been opened for this? because its for sure not pipelines

**Comment by mllg** [comment]
> whats the list of stuff that uses the deprecated API? have issues been opened for this? because its for sure not pipelines

No issues, directly fixed all warnings in all packages. First mlr3 was updated with the deprecated warnings (17 days ago), then mlr3db + mlr3learners have been uploaded with the respective fixes 16 days ago.

There might be some string conversions left in the book, I was unable to fix there as tuning + pipelines were broken at that time.

**Comment by mllg** [comment]
> I just now quickly scanned all of the sources on CRAN. _none_ of mlr3's reverse dependencies seem to use the "direct string-conversion API". yes a technical reverse check should still be run (after removal of the deprecated stuff), but i still fail to see what we are waiting for then?

See comment above. Additionally, it is also nice for the user to get a warning if the API changes, especially if we can provide it as easily as in this case.

**Comment by berndbischl** [comment]
> . Additionally, it is also nice for the user to get a warning if the API changes, especially if we can provide it as easily as in this case.

i dont know. i kinda disagree. in general: 100% yes. but in a version 0.1? where we explicitly say that API can change?  and we have been on cran for very weeks? 
and we have 0 dependencies that rely on this feature?

this seems to have lead "to busy-body work" to me, and also to confusion - evidence: this thread.
also i think we need to communicate and document these things better

**Comment by mllg** [comment]
>  and we have been on cran for very weeks?
> and we have 0 dependencies that rely on this feature?

I cannot track if someone already started to toy around with our packages, or even started to write a package which is not yet released. 

Wouldn't it be nice to get an informative warning instead of a cryptic error message if something this fundamental changes? How would it help to immediately remove the deprecated functions?

**Comment by berndbischl** [comment]
> I cannot track if someone already started to toy around with our packages, or even started to write a package which is not yet released.

i already answered wrt that point (you just conveniently removed it in your partial quote)



> Wouldn't it be nice to get an informative warning instead of a cryptic error message if something this fundamental changes?

see above




> How would it help to immediately remove the deprecated functions?

i already explained this too. it would have save me this thread and some time and confusion when working on mlr3tuning. it now depends how you value that

**Comment by berndbischl** [comment]
----------> 
we should IMHO remove the deprecated stuff soon. and make sure the CORRECT api is documented
