### ISSUE TITLE
Feature Request: List/vector multiple arguments to sugar construction

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#351]
Hi, I couldn't see any open or closed issues about this (here or in mlr3misc), nor any documentation relating to why the current design decision was made. 

It would be really nice to see

```R
lapply(c("classif.featureless","classif.rpart"), lrn, predict_type = "prob")
```
simplified to
```R
lrn(c("classif.featureless","classif.rpart"), predict_type = "prob")
```

Currently the latter only returns the first provider learner. Let me know if you'd rather I open this issue in the mlr3misc repo.
Thanks!

**Comment by pat-s** [comment]
We decided against "automatic creation of objects from strings" in mlr3 v0.1.2

> "Deprecated support of automatically creating objects from strings.
Instead, mlr3 provides the following helper functions intended to ease the
creation of objects stored in dictionaries:
tsk(), tgen(), lrn(), rsmp(), msr()."

So you need to explicitly pass one of the above, in this case `lrn()`.

**Comment by berndbischl** [comment]
@pat-s you are not really answering @RaphaelS1 request.
he is basically asking about vectorizing the sugar function. 
A request I also made and can understand.

**Comment by pat-s** [comment]
Oh, yes. Sorry - my bad! I was lazy in reading the issue.

We discussed this in one of the meeting in the last weeks (I think I was even initiating the request but did not open an issue). So thanks - and yes, we should definitely do this!

**Comment by RaphaelS1** [comment]
Great I look forward to seeing it!

**Comment by mllg** [comment]
I also thought about vectorization here, and I'm still unsure if this will come back to bite us.

You are requesting a change which makes the class of the return value depend on the length of the input (obj or list of obj). This is not unusual for R (`sapply()`, `simplify`/`drop`) and great for interactive data analysis, but cumbersome to program on.

Maybe we can discus this tomorrow in the scheduled call?

**Comment by berndbischl** [comment]
Let's discuss this as suggested.
Briefly here: these convenience functions are more for scripts? So you could always ignore them?
A second option would be to create a new, additional only list-returning function? 
So lrns on top of lrn, or lrn_s, or lrn_list, the name is debatable? Then the return type is clear from code and syntax and does not depend on args?

**Comment by RaphaelS1** [comment]
My thinking was based on mlr(2)'s difference between `makeLearner` and `makeLearners` hence I had naturally assumed that `lrn` constructs a single learner whereas `lrns` can return a list

**Comment by mb706** [comment]
`lrns`, `msrs`, `rsmps`, `pos`, `flts`

**Comment by mllg** [comment]
tsks
