### ISSUE TITLE
F1 classification measure using wrong Metrics::f1 function

### ISSUE THREAD

**Issue by 001ben** [mlr-org/mlr3#353]
https://github.com/mlr-org/mlr3/blob/070bb5b7f9ac73e3138c98e0a6ef21910e3cfb03/R/MeasureClassifF1.R#L26

The Metrics definition of f1 is actually defined for information retrieval problems, for binary classification f1, the correct function to use is `Metrics::fbeta_score(actual, predicted, beta=1)`.
See this closed Github issue on metrics: https://github.com/mfrasco/Metrics/issues/34

Could also extend this with f0.5 and f2 scores as common variants to the F-score. Potentially a function for allowing custom fbeta_score to be specified via MLR at runtime would be useful?

**Comment by mllg** [comment]
Thanks for reporting, replaced with `MeasureClassifFScore` to support arbitrary values of `beta`.

**Comment by 001ben** [comment]
Wow that was a quick response, thanks so much!
