### ISSUE TITLE
Easier access to learner object's help page

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#354]
If I have a learner object LRN, how do I access its help page? Best I can think of is
```r
help(class(LRN)[1])
```
Maybe this should be made easier for R novices. If the key name `"xxx"` in the `mlr_learners` dict is known we can at least do `?mlr_learners_xxx` but maybe we want something simpler and more general.

**Comment by mllg** [comment]
Any suggestions?

Best I came up with is this:
```r
hlp = function(obj) {
	help(class(obj)[1])
}
```
Or, alternatively, `obj$help(...)`.

**Comment by berndbischl** [comment]
i would make the name more specific. also it might be better to have this as a pure function not an R6 method. usually you want to read the help before you create the object

help_learner?
