### ISSUE TITLE
Serve pkgdown from docs/ master instead of gh-pages branch

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#36]
Similar as we do it in `mlr`.

- per branch docs
- PR previews (netlify)

**Comment by mllg** [comment]
Do we really want this? Do we then get one extra commit message per commit?

**Comment by pat-s** [comment]
Similar as we do it in mlr currently: Build it (to check if everything is ok) but don't deploy. Update changed docs directly in the PR and merge silently. 

I recently had a long discussion with Bernd and Jakob before about the best approach. Currently, there is no option that has no drawback.

The problem is that `pkgdown::build_site()` updates all .png files and the seed is not respected. This then sets the files to "changed" in git and we get a new commit deployed. Once they have resolved this issue we can again auto-deploy.

Big advantage of master/docs to gh-pages: PR preview of the changed site which is a very important feature.

As long as the site is minimal, we can serve through the gh-pages branch.

**Comment by pat-s** [comment]
To have the pkgdown site as a subdomain mlr3.mlr-org.com, we need to have it in `master/docs`  because the deployment to `gh-pages` deletes the `CNAME` file on every push because its doing an `orphan = T` push.
