### ISSUE TITLE
predict_newdata seems ill-designed, user cannot be forced to provide task (including data and backend))

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#360]
looking at the current options for predict functions we have these 2:

```
#' * `predict(task, row_ids = NULL)`\cr
#'   ([Task], `integer()` | `character()`) -> [Prediction]\cr
#'   Uses the data stored during `$train()` in `$state` to create a new [Prediction] based on the provided `row_ids`
#'   of the `task`.
#'
#' * `predict_newdata(task, newdata)`\cr
#'   ([Task], `data.frame()`) -> [Prediction]\cr
#'   Uses the data stored during `$train()` in `$state` to create a new [Prediction] based on the new data in `newdata`.
#'   Object `task` is the task used during `$train()` and required for conversions of `newdata`.
```

I want to talk about the later, and have also mentioned this multiple times during meeting how crucial this is. The current docs make it sound that the Task used during training is needed during predict time. Of course this does not work, if this means that the user has to store the whole task after training (in mem, or disk) to be able to predict on a new portion of data.

Now it MIGHT be that a user can delete the data from the Task, by "nulling" the backend. 
a) Is this possible?
b) Is this tested?
c) This would also needed to be documented VERY VISIBLY
d) If this is all true, it still seeem a bit tedious from a user perspektive

I HIGHLY suggest that we discuss this VERY SOON, as this a fundemental part of the interface and without this feature mlr3 is partially incomplete

**Comment by mb706** [comment]
The learner should store all required info for inference internally, e.g. some kind of header of the task. inference on new data should be as simple as `$predict(new_data_frame)`. I would not even call it `predict_newdata()`, but if you want to avoid polymorphism maybe.

**Comment by mb706** [comment]
Also related, `predict_newdata` messes up the row IDs.
![predict](https://user-images.githubusercontent.com/15801081/65539396-a2c48a80-df09-11e9-8971-b775b1a4eb61.png)

**Comment by mllg** [comment]
We need a call on this. I thought about it a bit, and came to the following conclusions:

* We can (relatively easy) drop the `task` argument from `predict_newdata()`.
* We need something which was a `TaskDescription` in mlr. We can make our lives easy here and just store the task w/o the `DataBackend`, but this needs some testing
* We might need to address the general problem that we currently cannot define how R6 objects are serialized (to disc, or for parallelization). We should probably provide S3 functions to condense objects to something smaller for archival purposes or for complete reconstruction of the object.

**Comment by berndbischl** [comment]
> We need a call on this.

agreed. answer about the timing in slack pls.

and i agree that we need to store SOME info about the data. i just had hoped that the task is already that....

**Comment by mllg** [comment]
#375 now stores an empty task during `learner$train()`. This allows you to call `learner$predict_newdata()` without a task.

For learners trained via `resample()` or `benchmark()` I currently do not store the information, but the task is still present in the respective RR or BMR and can be passed to `$predict_newdata()`.

Next, I will look into some sort of "condense" method to reduce the size for RRs and BMRs so that you can store them efficiently without the data.

**Comment by mllg** [comment]
I'll open a new issue for this.
