### ISSUE TITLE
use withCallingHandlers instead of tryCatch

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#362]
is that possible? debugging an error thrown by a learner$train_internal or $predict_internal is a PITA because `tryCatch` messes up the call stack. Or is there a way to prevent `tryCatch` from being used, or a way to make it not remove the call stack that I am not aware of?

**Comment by mllg** [comment]
IDK, I guess you have to try yourself what works best for you.

**Comment by berndbischl** [comment]
is ist possible to comletely switch off he encapsulation and try-catch? so that the error is directly produced? IMHO that would be enough?

**Comment by mb706** [comment]
@ "what works best for you" --- I mean the question as in, could this be used instead of tryCatch inside functions like `train_wrapper()` and `predict_wrapper()`

**Comment by mllg** [comment]
Yes, you could replace with `withCallingHandlers()` or a `try()`. I don't know what exactly is going on with the call stack that you dislike, so you probably need to try it yourself.

**Comment by mb706** [comment]
Maybe I just don't know how to debug properly. If my `Learner` throws an error, how do I get the full stack trace? E.g. if I do
```r
options(error=recover)
lrn("classif.debug", error_train = 1)$train(tsk("iris"))
```
I get
```
Error in learner$train_internal(task = task) : 
  Learner 'classif.debug' on task 'iris' failed to fit: Error from classif.debug->train()

Enter a frame number, or 0 to exit   

 1: lrn("classif.debug", error_train = 1)$train(tsk("iris"))
 2: Learner.R#234: learner_train(self, task, row_ids)
 3: worker.R#68: encapsulate(learner$encapsulate["train"], .f = train_wrapper, 
 4: invoke(.f, .args = .args, .opts = .opts, .seed = .seed)
 5: eval.parent(expr, n = 1)
 6: eval(expr, p)
 7: eval(expr, p)
 8: .f(learner = <environment>, task = <environment>)
 9: worker.R#6: tryCatch({
    model = learner$train_internal(task = task)
}, e
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatchOne(expr, names, parentenv, handlers[[1]])
12: value[[3]](cond)
```
Ideally I would want to inspect the state inside the `train_internal()` function.

**Comment by berndbischl** [comment]
i get exactly the same, and have the same problem. this is why i asked whether i can simply switch the encapsulation off....?

**Comment by mllg** [comment]
Removed `tryCatch()`. `withCallingHandlers()` made it better, but for now we can probably work with the raw error message from the learner (because we have a log).

Encapsulation is still active, this only adds 1-2 steps in the call stack.
