### ISSUE TITLE
Should "stratify" be a column role?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#364]
... should "groups" (blocking) be a hyperparameter of a Resampling? Right now it does not seem very consistent.

**Comment by mllg** [comment]
Grouping and stratification both only affect the resampling. But I'm unsure if these two should be a property of the task (i.e., these columns should always be used for stratification, and this one should be always used for blocking), or if these two should be a parameter of the Resampling.

@berndbischl ... your 2 cents?

**Comment by jakob-r** [comment]
Even though not directly asked: Having it as a parameter has many drawbacks:
* For Benchmarking you would have to modify each Resampling Object
* Spelling mistakes can only be caught once these objects are combined
* if you do nested resampling you have to specify the params twice for inner and outer resampling (or do I ever want to treat them differently in inner/outer resampling? --> Then a Param would be better maybe, or another solution has to be found)

**Comment by mllg** [comment]
> * if you do nested resampling you have to specify the params twice for inner and outer resampling (or do I ever want to treat them differently in inner/outer resampling? --> Then a Param would be better maybe, or another solution has to be found)

That's an excellent point I haven't thought of. I cannot imagine why you would stratify on the outer resampling, but not on the inner resampling. I'n not sure about grouping though.

**Comment by berndbischl** [comment]
we discussed this in the core call. my initial feeling has not changed. 
grouping, stratification, weighting all belong to the task and refer to observations. 
i think this should be handled in the task through column roles, i like that approach

**Comment by mllg** [comment]
Is now a column role.
