### ISSUE TITLE
How do factor features differ from character features, and how does Task$levels() work?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#369]
I understand that a `Task` should abstract away the ugliness of underlying backends, and therefore that feature types should have a semantic meaning and not only reflect the datatype of the underlying data.table, database or whatever. So "character" features probably mean something different than "factor" features --- was this discussed somewhere?

My suggestion:
 - factors are from a limited set of possibilities, the learner can trust that the factor levels during training and prediction match (so we may have to use `PipeOpFixFactors`) and we can one-hot encode them
 - characters are from an unlimited set of possibilities, unless we have a learner that does NLP (e.g. character level NNs) most learners will not be able to handle it, but there may be a PipeOp that creates a bag-of-words representation or extracts other kinds of features. character features should not be one-hot-encoded.

It would make a few `PipeOp`s much simpler if the `levels(Task$data()$feature)` equals `Task$levels()$feature` if `feature` is a factorial column. Is that currently enforced? Especially with `Task$droplevels()` --- what effect does this have (or *should* this have) on a `Learner` using the task?

@mllg

**Comment by mb706** [comment]
Also: Do we ever want to have "logical" features, and treat them differently from binary factor features or integer features with values 0 and 1? They do add complexity to mlr3pipelines because in principle every PipeOp should know what it is supposed to do with it.

**Comment by mllg** [comment]
We can discuss this in the next call. Character features are currently mostly handled like factors. The reasoning behind this is that many external data sources such as SQL backends don't have support a factor-ish type (or this info is lost during transmission).

This is a general problem, and I'm considering to extend tasks or backends with some auto-converters to solve this. As soon as this is implemented it makes sense to treat characters and factors differently.

**Comment by mllg** [comment]
mlr3db can now convert characters to factors.

**Comment by mllg** [comment]
I've started to treat factors and characters differently in 650b95eab9fcc835cc76c5e4cecea087ec41c6b2.
