### ISSUE TITLE
Task$set_col_role -> Task$add_col_role + Task$rm_col_role?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#370]
Changing the interface here would make it more straight forward to work with column and row roles.

@mb706 this would require a change in mlr3pipelines :worried:

**Comment by mllg** [comment]
Otherwise we would have to instruct the user to write stuff like this:
`task$set_col_role(task$target_names, "stratify", exclusive = FALSE)`

**Comment by mllg** [comment]
Or maybe we just document how to work directly the list `col_roles`?

**Comment by mb706** [comment]
How about making `col_roles` an active binding. It contains a named list of character vectors; names are data column names, content is the column roles.
* setting column role
    ```r
    task$col_roles$featx = "feature"
   ```
* adding col role
    ```r
    task$col_roles$featx = c("feature", task$col_roles$featx)
    ```
* removing col role
    ```r
    task$col_roles$featx = setdiff(task$col_roles$featx, "feature")
    ```

This is a bit verbose, but is intuitive and you immediately know what do do

**Comment by mb706** [comment]
this means that
```r
> task$col_roles
$a
[1] "feature" "weights"

$b
[1] "target"
```
assignment `task$col_roles$a <- ...` happens just as it works in `param_set$values`

**Comment by mllg** [comment]
Hm, I don't know. This would make the most frequent query "give me all the columns with role 'X'" pretty inefficient. Or do you want to keep the current data type and just offer this interface via an active binding?

**Comment by berndbischl** [comment]
> Or maybe we just document how to work directly the list `col_roles`?

why not do this?

**Comment by berndbischl** [comment]
how would a usual assignment then look for a user?

**Comment by mllg** [comment]
set stratification variable:

`task$col_roles$stratify = task$target_names`

remove a feature:

`task$col_roles$feautes = setdiff(task$col_roles$feautes, "myfeat")`

**Comment by mb706** [comment]
> This would make the most frequent query "give me all the columns with role 'X'" pretty inefficient.

Maybe leave `$col_roles` as it is and make my suggestion an active binding. I guess the most intuitive naming scheme would be that `$col_roles$COLNAME` gives all the roles of that col, and `$role_cols$ROLE` gives all columns with that role, which is exactly the opposite of how at least `$col_roles` currently behaves.

If you don't want to have ABs that map to the same information in different views you could also just use the functions. Why not have three functions `set_`, `add_`, and `rm_`?

**Comment by mllg** [comment]
#376 takes the follwoing approach:

* Deprecate `$set_row_role()` and `$set_col_role()`.
* Make `col_roles` and `row_roles` active bindings so that we can do some assertions.
* Additionally provide `col_roles_by_name` which provides an inverted  `$col_roles` (list names are column names, list elements are roles). You can also assign to this list.

So you can now do stuff like this:
```r
task = tsk("iris")

task$col_roles$stratify = task$target_names # stratify on target
task$col_roles_by_name$Sepal.Length = character() # disable col
task$col_roles_by_name$Species = c("target", "label") # use as target and label
```

Todo: Maybe rename `$col_roles` to `col_roles_by_role`?

Okay for everyone?

**Comment by berndbischl** [comment]
> Todo: Maybe rename `$col_roles` to `col_roles_by_role`?

probably better. 

but i dont understand all of your example code. and please really make sure to doc all of this....
(and link the doc page in this thread at the end)




> task$col_roles_by_name$Sepal.Length = character() # disable col

what is "disable"?  ignoring a column? and what does this mean exactly?
its not returned by data() cols? it is not considered when any task properties are computed?







> task$col_roles_by_name$Species = c("target", "label") # use as target and label

arent target and label the same....?

**Comment by mllg** [comment]
> what is "disable"? ignoring a column? and what does this mean exactly?
> its not returned by data() cols? it is not considered when any task properties are computed?

Same as before. If the column has no role, it is just ignored.

> arent target and label the same....?

No. `"label"` is a role which is intended to be used for plot labels (as doced in ?Task).

**Comment by berndbischl** [comment]
> Same as before. If the column has no role, it is just ignored.

of, confirmed.

> No. `"label"` is a role which is intended to be used for plot labels (as doced in ?Task).

can we please speak a bit about these names before we introdue them - and potentially have to change them later.
 you have to admit that (even though this might be explained in docs) is the super-most confusing name in ML ever? maybe "plotlabel"? "id-label"?

**Comment by mllg** [comment]
I need to revert the `col_roles_by_name` binding again. It reorders `col_roles` on assignment which breaks stuff in various places.

It is still possible to directly work with the list `col_roles`.
