### ISSUE TITLE
Resampling results don't appear in the console

### ISSUE THREAD

**Issue by kadyb** [mlr-org/mlr3#372]
I created R Notebook file and I noticed that the model parameters and resampling results do not appear in the console output in this case compared to the simple R file:
````{r}
library("mlr3")
library("paradox")
library("data.table")
library("mlr3tuning")
library("mlr3learners")

data = data.table(
   x = 1:10,
   y = seq(2, 20, 2)
)

task = TaskRegr$new("task", backend = data, target = "y")

lrn_xgb = mlr_learners$get("regr.xgboost")

ps = ParamSet$new(
   params = list(
      ParamDbl$new(id = "eta", lower = 0.1, upper = 0.4),
      ParamInt$new(id = "max_depth", lower = 4, upper = 10)
   ))

at = AutoTuner$new(learner = lrn_xgb, 
                   resampling = rsmp("cv", folds = 2),
                   measures = msr("regr.rmse"), 
                   tune_ps = ps,
                   terminator = term("evals", n_evals = 1),
                   tuner = tnr("random_search"))

resampling_outer = rsmp("cv", folds = 2)

rr = resample(task = task, learner = at, resampling = resampling_outer)
````

<details>
<summary>R Notebook output:</summary>

> INFO  [21:49:17.289] Applying learner 'regr.xgboost.tuned' on task 'task' (iter 1/2) 
> INFO  [21:49:17.363] Starting to tune 2 parameters with '<TunerRandomSearch>' and '<TerminatorEvals>' 
> INFO  [21:49:17.370] Terminator settings: n_evals=1 
> INFO  [21:49:17.405] Evaluating 1 configurations 
> INFO  [21:49:17.429]  
> INFO  [21:49:17.501] Benchmark with 2 resampling iterations 
> INFO  [21:49:17.507] Applying learner 'regr.xgboost' on task 'task' (iter 1/2) 
> INFO  [21:49:17.535] Applying learner 'regr.xgboost' on task 'task' (iter 2/2) 
> INFO  [21:49:17.582] Finished benchmark 
> INFO  [21:49:17.601] Result: 
> INFO  [21:49:17.616]  
> INFO  [21:49:17.621] Finished tuning after 1 evals 
> INFO  [21:49:17.684] Applying learner 'regr.xgboost.tuned' on task 'task' (iter 2/2) 
> INFO  [21:49:17.775] Starting to tune 2 parameters with '<TunerRandomSearch>' and '<TerminatorEvals>' 
> INFO  [21:49:17.781] Terminator settings: n_evals=1 
> INFO  [21:49:17.817] Evaluating 1 configurations 
> INFO  [21:49:17.835]  
> INFO  [21:49:17.907] Benchmark with 2 resampling iterations 
> INFO  [21:49:17.912] Applying learner 'regr.xgboost' on task 'task' (iter 1/2) 
> INFO  [21:49:17.948] Applying learner 'regr.xgboost' on task 'task' (iter 2/2) 
> INFO  [21:49:17.990] Finished benchmark 
> INFO  [21:49:18.014] Result: 
> INFO  [21:49:18.034]  
> INFO  [21:49:18.060] Finished tuning after 1 evals
</details>

<details>
<summary>R file output:</summary>

> INFO  [21:51:11.880] Applying learner 'regr.xgboost.tuned' on task 'task' (iter 1/2) 
> INFO  [21:51:11.972] Starting to tune 2 parameters with '<TunerRandomSearch>' and '<TerminatorEvals>' 
> INFO  [21:51:11.978] Terminator settings: n_evals=1 
> INFO  [21:51:12.016] Evaluating 1 configurations 
> INFO  [21:51:12.025]       eta max_depth 
> INFO  [21:51:12.025]  0.109227        10 
> INFO  [21:51:12.085] Benchmark with 2 resampling iterations 
> INFO  [21:51:12.087] Applying learner 'regr.xgboost' on task 'task' (iter 1/2) 
> INFO  [21:51:12.111] Applying learner 'regr.xgboost' on task 'task' (iter 2/2) 
> INFO  [21:51:12.171] Finished benchmark 
> INFO  [21:51:12.190] Result: 
> INFO  [21:51:12.197]       eta max_depth regr.rmse 
> INFO  [21:51:12.197]  0.109227        10  6.681414 
> INFO  [21:51:12.201] Finished tuning after 1 evals 
> INFO  [21:51:12.250] Applying learner 'regr.xgboost.tuned' on task 'task' (iter 2/2) 
> INFO  [21:51:12.325] Starting to tune 2 parameters with '<TunerRandomSearch>' and '<TerminatorEvals>' 
> INFO  [21:51:12.331] Terminator settings: n_evals=1 
> INFO  [21:51:12.359] Evaluating 1 configurations 
> INFO  [21:51:12.363]        eta max_depth 
> INFO  [21:51:12.363]  0.3396444         4 
> INFO  [21:51:12.442] Benchmark with 2 resampling iterations 
> INFO  [21:51:12.446] Applying learner 'regr.xgboost' on task 'task' (iter 1/2) 
> INFO  [21:51:12.468] Applying learner 'regr.xgboost' on task 'task' (iter 2/2) 
> INFO  [21:51:12.507] Finished benchmark 
> INFO  [21:51:12.525] Result: 
> INFO  [21:51:12.537]        eta max_depth regr.rmse 
> INFO  [21:51:12.537]  0.3396444         4  11.65291 
> INFO  [21:51:12.544] Finished tuning after 1 evals
</details>

**Comment by kadyb** [comment]
[Here](https://gofile.io/?c=VmCytb) I uploaded an example RMD file with the above code. It works after knitting (you can see tunned parametrs in report) but in my project I don't need to knit whole R Notebook and I run some chunks by 'Run Current Chunk' (in some chunks I have option 'include=FALSE').

**Comment by mllg** [comment]
I've tested a Rmd, I don't see any problems anymore.
