### ISSUE TITLE
Apply favicon to all pkgdown sites + blog

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#373]
Following the approach from mlr3: 

- https://github.com/mlr-org/mlr3/commit/455409ddb707a2f29a1b9827052be74b60adbe54
- https://github.com/mlr-org/mlr3/commit/4a6e5139c7bab68fd270c0d9711a9b760a81a2bd

We should do this as a template repo, see https://github.com/mlr-org/mlr3pkgdowntemplate.
This repo should then be the base for all mlr3 pkgs so that we can easily scale small changes.

**Comment by mllg** [comment]
I'm already on it!

**Comment by mllg** [comment]
Favicons do not work yet with orphan branches (https://github.com/r-lib/pkgdown/pull/1156). Other stuff should hopefully work.

**Comment by pat-s** [comment]
We got a favicon in https://mlr3.mlr-org.com/?
