### ISSUE TITLE
Please don't create 3 different functions for same thing

### ISSUE THREAD

**Issue by vikram-rawat** [mlr-org/mlr3#379]
I was reading through the book today and it took me a while to understand that

Taskregr
Mlr_task
Tsk

All do almost exactly the same thing. Most of the r users are not familiar with r6 syntax and to top it off providing 3 functions for each task, learner, resample etc... Make it very hard to grasp and it would be harder for you to implement as well.

Please create only one function which could be optimized rather than 3 functions to do exactly the same thing.

And yes if possible think about this scenario if I have regression-task which could only be used by regression-learner should not these 2 go together in some sense. Why write 2 different functions for these things when it's clear that a regression task could use only a couple of regression learners

I am just trying to understand the system a little better I could be wrong but please do reply me once you read it.

**Comment by mllg** [comment]
The book is not very accurate here, but we have good reasons to provide multiple "functions" here:

1. We have an object "TaskRegr" for regression tasks. This gives us an interface to  work with tasks.
2. We have a dictionary/collection/hash of all tasks, this is `mlr_tasks`. We have registered all objects in the respective dictionary to be able to (a) query for all tasks and (b) to retrieve these tasks again. We also have objects for most all other building blocks (learners, measures, resamplings, ...).
3. Retrieving objects from dictionaries (and directly settings some parameters) is such a frequent operation that we decided we want something more concise. This is why we have `tsk()`.

We just created the functions in (3) just some weeks ago and the book was not updated to promote them properly. @jakob-r just merged a PR (https://github.com/mlr-org/mlr3book/pull/65) which should clarify the usage of the objects. I'll do another iteration now.
