### ISSUE TITLE
Learner$state$train_task not cloned 

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#382]
`Learner$clone(deep = TRUE)` should result in an object with no environments in common with the original object, but `Learner$state$train_task` is not cloned.
```r
> lr = lrn("classif.rpart")$train(tsk("iris"))
> data.table::address(lr$state$train_task)
[1] "0x5598f3fe1bc0"
> data.table::address(lr$clone(deep = TRUE)$state$train_task)
[1] "0x5598f3fe1bc0"
```

**Comment by mllg** [comment]
Do we really need to clone it? `train_task` != input task, and it can be considered as read-only.

**Comment by mb706** [comment]
I'd rather be more careful here and let `$clone(deep = TRUE)` satisfy its contract. I would assume at some point people lose sight what things are considered read-only. If someone writes a transformation that changes a trained learner and modifies its associated task there could be weird bugs that are hard to catch.

Case in Point:
```r
> lr = lrn("classif.rpart")$train(tsk("iris"))
> lrc = lr$clone(deep = TRUE)
> lr$predict_newdata(iris[1:3, 1:4])
<PredictionClassif> for 3 observations:
 row_id truth response
      1  <NA>   setosa
      2  <NA>   setosa
      3  <NA>   setosa
> lr$predict_newdata(iris[1:3, 1:4])
<PredictionClassif> for 6 observations:
 row_id truth response
      1  <NA>   setosa
      2  <NA>   setosa
      3  <NA>   setosa
      4  <NA>   setosa
      5  <NA>   setosa
      6  <NA>   setosa
> lrc$predict_newdata(iris[1:3, 1:4])
<PredictionClassif> for 9 observations:
    row_id truth response
         1  <NA>   setosa
         2  <NA>   setosa
         3  <NA>   setosa
---                      
         7  <NA>   setosa
         8  <NA>   setosa
         9  <NA>   setosa
```
(I am opening a separate report for this)
