### ISSUE TITLE
Automatically use featureless model if no features are present

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#390]
Slightly contrived example:
```r
> (po("select", selector = selector_none()) %>>% lrn("classif.ranger"))$train(tsk("iris"))
Error in ranger::ranger(dependent.variable.name = task$target_names, data = task$data(),  : 
  Error: No covariates found.
```

this may happen in some cases with PipeOpRemoveConstants or PipeOpFilter and would be nice if it could be avoided automatically.

**Comment by mllg** [comment]
I'm not sure how the mechanism for this should look like. This must be transparent to the user, and should not conflict with the fallback learner.

The cleanest solution I can think of:

* tag learners that they need features
* allow multiple fallback learners, all are tried in a specified order until one succeeds

On a related note, what do you do with PipeOps that require features?

@berndbischl Any comments on how happy you were with the `NoFeaturesModel` in mlr?

**Comment by berndbischl** [comment]
I don't get this? This should directly delegate to the normal fallback learner?

**Comment by berndbischl** [comment]
Ah wait. That usually needs features too?

**Comment by berndbischl** [comment]
What happens in the example above if you set featureless as the fallback learner?

**Comment by mllg** [comment]
Featureless should work in this case, but this is a case where you probably want to have multiple fallbacks, right?

**Comment by mllg** [comment]
This is doable, would this solve your issues @mb706?

**Comment by mb706** [comment]
Would it make sense to have the featureless learner be the default fallback in this case, as it works in old mlr?

**Comment by berndbischl** [comment]
can we somehow avoid multiple fallbacks pls? how about we let the user make the choice of a single fallback. featureless always works. and in cases like this, also the fallback fails if is not "featureless". thats a user problem them and a robust alternative is available as a choice.

?

**Comment by mb706** [comment]
Another issue: maybe one wants to use the featureless learner whenever the data has no features (e.g. during pipeline tuning when a filter happens to remove all features), but *not* use a fallback learner whenever the learner *actually* fails.

**Comment by berndbischl** [comment]
OTOH we would love to have a cleary documented and understandable principle. we need something "simple" here. i would like to have this solved pretty soon, but i think we need to discuss this @mllg

**Comment by berndbischl** [comment]
we agreed that using the featureless learner is always an option here, so this is not top prio
