### ISSUE TITLE
resampling: instantiate twice gives improper error message

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#398]
consider this user-error, which already happened in this issue:

https://github.com/mlr-org/mlr3/issues/397

1) we instantiate customly, then again
```
resampling = rsmp("custom")
train_sets = list(1:300 , 332:632, 633:738)
test_sets = list(301:331, 633:663, 739:768)
resampling$instantiate(task, train_sets, test_sets)
resampling$instantiate(task)
```
this gives message:
  Assertion on 'train_sets' failed: Must be of type 'list', not 'N
ULL'.

2) do we want that? 
- it its fine to re-instantiate a resmpling, is that correct?
- in the case above the resampling is "custom" so the user needs to input the train_set.
so the error msg is actually fine? the problem in then simply in mlr3tuning?

**Comment by mllg** [comment]
1. I've improved the error message
2. It is fine to re-instantiate
3. Problems seems to be in tuning, yes.
