### ISSUE TITLE
R6 roxygen documentation

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3#406]
@mboecker will do this for all Learner classes now (in the beginning)

**Comment by mboecker** [comment]
Problems that I've encountered:
- the function signature / field type is not automatically documented
- additional information (that is, additional sections) are now rendered above the field/method section

**Comment by jakob-r** [comment]
> the function signature / field type is not automatically documented

has never been -- how should that work in R where we are not type specific?

**Comment by mboecker** [comment]
> the function signature / field type is not automatically documented

yes but there is also no (documented) syntax to do this by hand (other than plainly writing it in the description of a field/method). I have updated my comment above to reflect that.

what was your opinion regarding the duplicated parameter / field descriptions? I think we agreed that they should be documented **once**. The three options regarding this are
1. we document them as a field
2. we document them as a constructor parameter
3. we use templates to document them as both a field and a parameter

do you wanna discuss this in the call or did we already decide on 3?

**Comment by jakob-r** [comment]
Con you find out if 3) works? We don't want to have copy pasta in the code but the end result i.e. the documentation can have duplications.

**Comment by mllg** [comment]
Closing here, the documentation has been migrated to new style.
