### ISSUE TITLE
Measures Roxygen Documentation

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#407]
I've read [this](https://github.com/mlr-org/mlr3/issues/231) but it doesn't seem to answer my questions below.

There appears to be some inconsistencies in how `Measures` are documented. For example:
* In `mlr3measures` the documentation includes things like `predict_type`, which seems strange as this affects the `Measure` object but not the scoring function.
* There are some measures like `MeasureClassifCosts`, which do not call an external package but define the scoring function in `score_internal` but there's no separate documentation describing how this functions, or required `predict_type`. 
* Finally parameters are in constructor but not using `paradox`, which is different from other `mlr3` objects.

As I’m currently finalising documentation for the `mlr3proba 0.1`  release I want to make sure I am consistent with the current practice, but it is unclear to me what that is, are there any guidelines or general advice about your plans for this?

**Comment by mllg** [comment]
This is indeed inconsistent. I'll refactor the docs and come back to you here.

**Comment by mllg** [comment]
1. `mlr3measures` still has the predict type as annotation. This describes what kind of predictions you can pass to the individual functions. Wording could be improved here to make this more clear.
2. The docs are improved now. Each measure in mlr3 now has a dedicated help page.
3. This was a longer discussion. We decided to only use parameter sets if the parameters are intended to be tuned. This also excludes most technical parameters / fields.

**Comment by RaphaelS1** [comment]
Thanks! One final question about this, for measures implemented in mlr3 (e.g. classif costs) do you want two separate help pages, one for the measure object and one for the score, or just one for the object?

**Comment by mllg** [comment]
Just one for the measure is enough. The reason we had put the scores in an extra package is that we are able to better unit test them and also use them in other projects. We are thinking about switching mlr2 to some of these measures.

**Comment by RaphaelS1** [comment]
Thanks, that's what I'll do!
