### ISSUE TITLE
broken og image in pkgdown website

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#410]
The pkgdown page has the tag
```html
<meta property="og:image" content="https://mlr3.mlr-org.com/logo.png">
```
but the image url 404s. It should probably be `https://mlr3.mlr-org.com/reference/figures/logo.png`.

**Comment by pat-s** [comment]
Where exactly? I can see the logo on both versions.

**Comment by mllg** [comment]
This is a hint which image to use for preview thumbnails, e.g. on twitter.

**Comment by mllg** [comment]
https://github.com/r-lib/pkgdown/pull/1201

**Comment by mllg** [comment]
Fixed upstream so this should automatically fix itself after pkgdown is released.

**Comment by mb706** [comment]
nice work!
