### ISSUE TITLE
predict_type defaults and usage

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#411]
This issue is to track the various discussions about `predict_type` and `predict_types`. I'll summarise everything discussed on Mattermost below. If I've copied anything wrong please edit.

___

Raphael: Why can't all return types be returned by default?
Bernd: Some return types require extra hyper-parameters and could cause unnecessary overhead 

Raphael: Can we change `predict_type` default in `LearnerClassif` to `prob`?
Bernd: This crashes if a learner cannot return `prob`, whereas all classif learners return `response`
Michel: I also find it annoying that you are often forced to change the predict_type to prob in classif

Raphael: Can we allow `predict_type` to be a vector to increase user flexibility over returns?
Michel: This is possible

Raphael: Does every learner need the same default `predict_type` or can we allow this to be changed in a learner definition?

Franz: A problem with always returning prob and response is less flexibility in determining how to perform the reduction from prob to response (e.g. default threshold value). Proposed solution: `predict_types` is a class property (trait) and `predict_type` is a mutable object property; `predict_type` can be a vector; if a default for one pt to another isn't obvious (e.g. threshold value) then this should be done via pipelines (see https://github.com/mlr-org/mlr3proba/blob/master/R/PipeOpCrankCompositor.R for example)

**Comment by berndbischl** [comment]
we agreed that nothing is serverly broken here and changing this would result in too many downstream changes in our own codebases and existing usercode
