### ISSUE TITLE
why can I train on tasks with NAs in features, although learners do not support this?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#413]
why does this run?

```
task = tsk("pima")
learner = lrn("classif.svm")
learner$train(task)
```

**Comment by berndbischl** [comment]
pls note that 

p = learner$predict(task)

now produces this very unintuitive error

Error in .subset2(public_bind_env, "initialize")(...) :
  Assertion on 'as_factor(response, levels = lvls)' failed: Must h
ave length 768, but has length 392.

the reason is - for the SVM here - that we produce only prediction on the observations where there are no NAs in features.

shouldnt mlr3 simply refuse to train here?

**Comment by mllg** [comment]
Related: https://github.com/mlr-org/mlr3/issues/436

**Comment by berndbischl** [comment]
situation now is:

* this is resolved, training now throws an error - as it should. SVM cannot handle smissings, but PIMA has them
* michel has added a unit test


in general: learners have to be able to handle missings BOTH in train and predict, to receive the missing property.

maybe at some point we can also allow to disable these data / learner property asserts to receive more speed and flexibility of users do not want this to be checked

**Comment by mllg** [comment]
Unit tested, closing.
