### ISSUE TITLE
Error: C stack usage is too close to the limit

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#414]
No idea currently where this error might come from. CI builds look fine, probably an OS related issue?

Came across this while compiling the mlr3book locally in chunk 02-basics-064.

```r
library('mlr3')
design = benchmark_grid(
  tasks = tsk("iris"),
  learners = list(lrn("classif.rpart"), lrn("classif.featureless")),
  resamplings = rsmp("holdout")
)
bmr = benchmark(design)
measures = list(
  msr("classif.auc", id = "auc_train", predict_sets = "train"),
  msr("classif.auc", id = "auc_test")
)
bmr$aggregate(measures)

Error: C stack usage  7971152 is too close to the limit
```

**Comment by mllg** [comment]
Cannot reproduce the C stack usage error.

I guess what you wanted to do is this:

```r
design = benchmark_grid(
  # need binary classif task
  tasks = tsk("sonar"),
  # need to set predcit_type and 
  learners = lrns(c("classif.rpart", "classif.featureless"), predict_type = "prob", predict_sets = c("train", "test")), predict_sets
  resamplings = rsmp("holdout")
)
bmr = benchmark(design)
measures = list(
  msr("classif.auc", id = "auc_train", predict_sets = "train"),
  msr("classif.auc", id = "auc_test")
)

bmr$aggregate(measures)
```

**Comment by pat-s** [comment]
Getting the same error with your example. Both with dev and and CRAN vers. Idk, need to inspect in more detail. Haven't changed anything in the setup lately - strange.

**Comment by mllg** [comment]
Just double-checked, code in the book is right. You just forgot to copy some lines.

**Comment by pat-s** [comment]
Error comes from data.table dev. You can try if you also get it and if so, we might want to report upstream.

**Comment by mllg** [comment]
https://github.com/Rdatatable/data.table/issues/4173

**Comment by drag05** [comment]
I am getting similar error on Windows 10, R.v. 4.0.2 while running the example from _https://mlr3book.mlr-org.com/benchmarking.html_ using R Studio Version 1.3.959:

```
 > bmr <- benchmark(design)
```
INFO  [13:29:19.828] Benchmark with 24 resampling iterations 
INFO  [13:29:20.023] Applying learner 'classif.ranger' on task 'sonar' (iter 1/3) 
INFO  [13:29:20.867] Applying learner 'classif.ranger' on task 'german_credit' (iter 1/3) 
INFO  [13:29:20.992] Applying learner 'classif.featureless' on task 'german_credit' (iter 2/3) 
INFO  [13:29:21.023] Applying learner 'classif.featureless' on task 'sonar' (iter 1/3) 
INFO  [13:29:21.044] Applying learner 'classif.kknn' on task 'sonar' (iter 2/3) 
INFO  [13:29:21.182] Applying learner 'classif.kknn' on task 'sonar' (iter 1/3) 
INFO  [13:29:21.255] Applying learner 'classif.rpart' on task 'german_credit' (iter 2/3) 
INFO  [13:29:21.316] Applying learner 'classif.ranger' on task 'german_credit' (iter 2/3) 
INFO  [13:29:21.447] Applying learner 'classif.rpart' on task 'german_credit' (iter 1/3) 
INFO  [13:29:21.486] Applying learner 'classif.ranger' on task 'sonar' (iter 3/3) 
INFO  [13:29:21.558] Applying learner 'classif.featureless' on task 'german_credit' (iter 1/3) 
INFO  [13:29:21.575] Applying learner 'classif.kknn' on task 'german_credit' (iter 2/3) 
INFO  [13:29:21.680] Applying learner 'classif.featureless' on task 'german_credit' (iter 3/3) 
INFO  [13:29:21.698] Applying learner 'classif.featureless' on task 'sonar' (iter 3/3) 
INFO  [13:29:21.715] Applying learner 'classif.ranger' on task 'german_credit' (iter 3/3) 
INFO  [13:29:21.834] Applying learner 'classif.ranger' on task 'sonar' (iter 2/3) 
INFO  [13:29:21.911] Applying learner 'classif.rpart' on task 'sonar' (iter 1/3) 
INFO  [13:29:21.950] Applying learner 'classif.rpart' on task 'sonar' (iter 2/3) 
INFO  [13:29:21.989] Applying learner 'classif.featureless' on task 'sonar' (iter 2/3) 
INFO  [13:29:22.007] Applying learner 'classif.rpart' on task 'sonar' (iter 3/3) 
INFO  [13:29:22.048] Applying learner 'classif.rpart' on task 'german_credit' (iter 3/3) 
INFO  [13:29:22.086] Applying learner 'classif.kknn' on task 'german_credit' (iter 1/3) 
INFO  [13:29:22.191] Applying learner 'classif.kknn' on task 'sonar' (iter 3/3) 
INFO  [13:29:22.265] Applying learner 'classif.kknn' on task 'german_credit' (iter 3/3) 
INFO  [13:29:22.397] Finished benchmark 

```
> measures <- list(msr('classif.auc', id = 'auc_train', predict_sets = 'train'), 
                               msr('classif.auc', id = 'auc_test'))

> bmr$aggregate(measures)
```
**Error: C stack usage  15923456 is too close to the limit**

```
> sessionInfo()
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlr3verse_0.1.1     paradox_0.2.0       mlr3viz_0.1.1       mlr3tuning_0.1.2   
[5] mlr3pipelines_0.1.3 mlr3learners_0.2.0  mlr3filters_0.2.0   mlr3db_0.1.5       
[9] mlr3_0.3.0         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       compiler_4.0.2     pillar_1.4.4       mlr3misc_0.3.0    
 [5] tools_4.0.2        rpart_4.1-15       digest_0.6.25      uuid_0.1-4        
 [9] lattice_0.20-41    evaluate_0.14      lifecycle_0.2.0    tibble_3.0.1      
[13] checkmate_2.0.0    gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.6       
[17] igraph_1.2.5       Matrix_1.2-18      rstudioapi_0.11    parallel_4.0.2    
[21] yaml_2.2.1         kknn_1.3.1         xfun_0.15          ranger_0.12.1     
[25] withr_2.2.0        dplyr_1.0.0        knitr_1.29         globals_0.12.5    
[29] generics_0.0.2     vctrs_0.3.1        grid_4.0.2         tidyselect_1.1.0  
[33] glue_1.4.1         data.table_1.12.9  listenv_0.8.0      R6_2.4.1          
[37] future.apply_1.5.0 rmarkdown_2.3      purrr_0.3.4        ggplot2_3.3.2     
[41] lgr_0.3.4          magrittr_1.5       mlr3measures_0.1.3 codetools_0.2-16  
[45] backports_1.1.8    scales_1.1.1       htmltools_0.5.0    ellipsis_0.3.1    
[49] future_1.17.0      colorspace_1.4-1   munsell_0.5.0      crayon_1.3.4
