### ISSUE TITLE
`<rsmp>$.combine()` has no tests

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#415]
Low prio, just a side-effect find

<img width="627" alt="Screenshot 2020-01-13 at 23 31 14" src="https://user-images.githubusercontent.com/8430564/72297785-f5fb4e00-365c-11ea-9410-7ab2aacec0ff.png">

**Comment by mllg** [comment]
This is triggered in tests. `$.combine()` is called by `$instantiate()` if the task is stratified. This is tested for all resamplings. I've also added this to `expect_resampling()` now.
