### ISSUE TITLE
predict_newdata can generate wrong row_ids

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3#418]
```r
task = tsk("mtcars")
learner = lrn("regr.featureless")
learner$train(task)
task_data = as.data.table(task)
task_data$mpg = NULL
preds = learner$predict_newdata(task_data)
preds
```
```
<PredictionRegr> for 32 observations:
                   row_id truth response
     rbind_20394c37812f_1    NA 20.09062
    rbind_20394c37812f_10    NA 20.09062
    rbind_20394c37812f_11    NA 20.09062
---                                     
     rbind_20394c37812f_7    NA 20.09062
     rbind_20394c37812f_8    NA 20.09062
     rbind_20394c37812f_9    NA 20.09062
```

The row ids are weird and in the wrong order. It does not happen with all tasks and seems to be unrelated of the learner (also tried rpart)

**Comment by mllg** [comment]
What happens here:

1. `mtcars` has row ids stored as strings
2. `task_data` does not have a row id column, so new row ids are created.
3. Unique row ids are generated. 

So everything looks good to me (unless you have a suggestion for a different approach?), except the re-ordering.

I'll look into it. Maybe allowing character row ids was not the best idea... :/

**Comment by jakob-r** [comment]
I can accept the weird row_ids (why `rbind_`?) but the reordering is fatal. Just format it with leading zeros or to save some characters as hex to have a quick fix ... idk?

**Comment by mllg** [comment]
Already started in a brach to remove the character row ids. I can't recall why I implemented them. Maybe because we did not have proper support for column roles at some point.

**Comment by pat-s** [comment]
Maybe because I had this one example task in {mlr3spatiotempcv} with character row ids? (I changed that meanwhile)

**Comment by jakob-r** [comment]
Just a reminder. If we change this, we have to update the book Task chapter
