### ISSUE TITLE
How to integrate feature selection (filtering) into tuning?

### ISSUE THREAD

**Issue by ImNotaGit** [mlr-org/mlr3#419]
Hi, I would like to tune the number of "top" features to include in a model as a hyperparameter, where the features are ranked by some importance measure as in the filtering method of feature selection. In the old mlr, I can do this by using `makeFilterWrapper()` around a learner, passing an argument like `fw.method` and then tune a corresponding hyperparameter with a name like `fw.abs`. Sorry but I haven't figured out how to do this in mlr3. I failed to find the relevant info in the documentation, and in the manual (mlr3book) it explains ways to obtain the importance measure of the features, but doesn't seem to explain how to use it during tuning. Much appreciated if any guidance could be provided on this.

**Comment by jakob-r** [comment]
This mlr3 book chapter should get you close to what you want to achieve:

https://mlr3book.mlr-org.com/pipe-modeling.html#pipe-tuning
