### ISSUE TITLE
Non-helpfull error message in `rsmp`

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#430]
The following yields an unhelpful error message:
 ``` r
library(mlr3)
rsmp("cv", iters = 3L)
#> Error in (function () : unused argument (base::quote(3))
```
<sup>Created on 2020-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It is not trivial to understand that the problem is `iters`, which is not a valid argument.
Additionally, it is not trivial to find out what the correct argument should have been (it is `folds = 3L`) because:
- `?rsmp` hints at `?mlr_resamplings` (both contain no information on how to set the number of folds, or how that argument should be named.)
- This hints at `?Resampling` (again no info)
- From there I could go to `ResamplingCV` and see the solution, but this is not trivial. 

IMHO, such a trivial thing should be better accessible.

**Comment by pat-s** [comment]
We should have a better error message for invalid args here, yes.

`?rsmp` although points to `Resampling` directly and from there you can arrive at `ResamplingCV`.

How about putting all available resampling methods via "seealso" into `?mlr_resamplings`? Currently there are only "cv" and "bootstrap".

Maybe can also change the line in `?rsmp` from

> "rsmp() for a Resampling from mlr_resamplings." 

to 

> rsmp() for a Resampling. See mlr_resamplings for a list of available resampling options and their help pages.

(this would apply to all sugar functions of course)

For us it might be intuitive meanwhile to use the sugar as a shortcut but to think of the main class explicitly. For new users this could really be a "documentation pain".

**Comment by berndbischl** [comment]
i agree with @pfistfl. this is basic funcionality and should be robust and understandable

**Comment by mllg** [comment]
This has nothing to do with the dictionary or sugar function `rsmp()`. There is an active binding `iters` in `Resampling` which is read-only. The error generated by an assignment are just very bad.

```r
r = rsmp("cv")
r$iters = 2
```
I'll include an assertion for all ABs.

**Comment by pat-s** [comment]
Should we still update the doc to make the help pages more accessible?

**Comment by mllg** [comment]
I've improved cross-references, and the error message should be more informative now.
