### ISSUE TITLE
Support 64 bit integers in tasks

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#434]
I.e., via package `bit64`. `data.table` already supports it nicely.

**Comment by pat-s** [comment]
Any examples on its effect?

**Comment by mllg** [comment]
Is needed for row ids if you have more than .Machine$integer.max rows. Alternatively also allow doubles, but this is rather ugly.

**Comment by gsenseless** [comment]
require(bit64)
task = TaskRegr$new("mc", backend = data.table(dd = bit64::as.integer64(34534543), bb = 0), target = "bb")
#Error in super$initialize(id = id, task_type = task_type, backend = backend) : 
 # Assertion on 'feature types' failed: Must be a subset of #{'logical','integer','numeric','character','factor','ordered','POSIXct'}, but is {'integer','numeric','integer64'}.

**Comment by gsenseless** [comment]
> Any examples on its effect?

require(bit64)
task = TaskRegr$new("mc", backend = data.table(dd = bit64::as.integer64(34534543), bb = 0), target = "bb")
#Error in super$initialize(id = id, task_type = task_type, backend = backend) :
#Assertion on 'feature types' failed: Must be a subset of #{'logical','integer','numeric','character','factor','ordered','POSIXct'}, but is {'integer','numeric','integer64'}.

**Comment by mllg** [comment]
I currently don't know any learner which supports this, so I'll close this for now.
