### ISSUE TITLE
Guidelines for which measure to use / Detect potentially inappropriate ones

### ISSUE THREAD

**Issue by chrarnold** [mlr-org/mlr3#435]
I am not sure how realistic this really is, but doesn't hurt to raise it and maybe open a discussion:
Let's say you have a multiclass classification problem. From my (please correct me if something is not quite right) understanding, suitable performance measures include the acc and the bacc. While the acc is commonly used, the balanced version is particularly relevant for unbalanced cases. I am wondering whether mlr3 also wants to go in a direction of alerting the user, warning the user or guiding the user of appropriate and inappropriate learners, measures, etc.Like in my case, I had highly different frequencies of the classes in the training dataset, which resulted in the acc and the bacc to be extremely different (like acc=0.7 vs bacc=0.3). First, I thought, nice acc=0,7, off you go, but then I realized that the reality, as always, seems to be more complicated. Maybe in such a case, it could be suggested via a designated suggest_measures function or whatever, which ones are appropriate, given some (hard to define, I know) rules about suitability. In the more general term, it would even help if there was a helper function that returns all currently implemented measures that can be used for multiclassification. Of course, using as.data.table(mlr_measures) can be used to find that out, but it would be even more user-friendly to provide a helper function for it. But again, this is more of a "convenience" function, and the overall question is what to focus on for now - adding learners, measures etc to match the mlr2 functionality, or making it more user-friendly already.

**Comment by berndbischl** [comment]
> I am wondering whether mlr3 also wants to go in a direction of alerting the user, warning the user or guiding the user of appropriate and inappropriate learners, measures,

i dont really know, my gut feeling says we should not do this (here). but i am also a person who teaches and writes, also online, and i think this rather belong into educational material than a compuational software. because there are no clear-cut rules for this. 



> In the more general term, it would even help if there was a helper function that returns all currently implemented measures that can be used for multiclassification. Of course, using as.data.table(mlr_measures) can be used to find that out, but it would be even more user-friendly to provide a helper function for it

i dont understand? the dictionaries are exactly for this? what do you diskike?

**Comment by berndbischl** [comment]
you simply want some sytanctic sugar, that filters the datatable for specific measures?

**Comment by berndbischl** [comment]
isnt this really so bad?

> d = as.data.table(mlr_measures)
> d[task_type == "classif" & task_properties != "twoclass", ]
               key task_type     packages predict_type task_properties
1:     classif.acc   classif mlr3measures     response                
2:    classif.bacc   classif mlr3measures     response                
3:      classif.ce   classif mlr3measures     response                
4:   classif.costs   classif                  response                
5: classif.logloss   classif mlr3measures         prob

**Comment by chrarnold** [comment]
Yeah you are right, this is totally enough, might be good to add something like this to the Docs also. I originally thought indeed about specific, commonly used filter functions, but a one-liner as you suggested should be totally fine for the (already advanced) people that use mlr3 and ML in general.

Regarding the "educational purpose", I personally feel that sometimes it can be useful to at least suggest or mention things, so users are more aware of it. Overall, this also enhances the usability of a package. But yes, this is all not well-defined and also trick in the details. I guess it is a question whether the Docs want to merely describe what the bacc stands for, or in addition also when it may be useful to actually prefer it over the acc etc. Sorry for the thoughts, might be out of scope for the "implementation" only part of the package.

**Comment by berndbischl** [comment]
> I originally thought indeed about specific, commonly used filter functions, but a one-liner as you suggested should be totally fine

we have a rule not to introduce extra sugar, UNLESS it is super clear how much we gain from this. and do this quite conservatively. in order to maintain a very clean and lean API.
so lrn() and tsk() we introduced, although you could do dict$get(). because this is such a common operation. 



> I guess it is a question whether the Docs want to merely describe what the bacc stands for, or in addition also when it may be useful to actually prefer it over the acc etc

mentioning something like bacc is good for imabalanced task, acc not so much --> i am all in favo of this. in the package code i find this harder.



> Sorry for the thoughts, might be out of scope for the "implementation" only part of the package.

pls dont be, this is all good and the discussion is appreciated
