### ISSUE TITLE
Add property "missing" and "missing_predict"

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#436]
A few learners may be able to handle missing values during prediction, but not during training, e.g. the earth learners, see https://github.com/mlr-org/mlr/issues/2108. I assume every `Learner` that handles missing during training also handles missing during prediction, so it may be sensible to have `"missing"` be a superset of `"missing_predict"`, but a `"missing_train"`, `"missing_predict"` split would also work for me.

This would be useful when considering removing unseen factor levels. If a `Learner` can handle missings during prediction, then unseen factors can be re-coded to NA, otherwise they should be imputed.

**Comment by mllg** [comment]
I agree that this is useful to have. I'm not sure about the superset stuff, but having two tags doesn't hurt.

**Comment by mllg** [comment]
See linked issue.

**Comment by mb706** [comment]
So what is the status then? There won't be a `"missing_train"` and `"missing_predict"`, learners either support missings during both training and prediction, or during neither?

**Comment by mllg** [comment]
Yep. Both steps must be supported, otherwise use a pipeop

**Comment by mb706** [comment]
I think the consequence of this is that if there is a learner that does something intelligent with missing values during prediction (although it can't handle them during training), then we are now preventing the user from making use of this feature. Instead we are forcing him to impute missing values for prediction.
