### ISSUE TITLE
predict_newdata should perhaps infer types from task.

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#447]
See https://stackoverflow.com/questions/60504843/how-to-decode-json-data-with-mlr3-package-in-the-prediction-phase#60504843

I guess a simple solution would be to ~~infer~~ convert types where trivial, and throw an error otherwise (which is already done anyways).
I guess the `numeric` <-> `integer` and `character` <-> `factor` conversion is simple
and occurs often enough to be automated away.

A case where we might also have this type of problem is when we, for example, have a `train.csv` and `test.csv`

**Comment by mllg** [comment]
Addresses in #448.
