### ISSUE TITLE
Option to merge BenchmarkResults stored in a list

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#454]
In {mlr} we had `mergeBenchmarkResults()` which accepted a list of Benchmarks.
Currently it seems the procedure in {mlr3} for merging BMRs in a list is somewhat complicated (see reprex). 

- A clone of the BMR gathering all the others is needed
- All BMRs needs to be passed in a loop

Am I overlooking something? Ideally I would like to pass a simple list containing single BMRs to `.$combine()` and have all merged into the one calling `.$combine()`.

(Note that I am aware how to merge two BMRs together using `.$combine()` but n could be Inf here)

``` r
library(mlr3)

lgr::get_logger("mlr3")$set_threshold("warn")
# benchmarking with benchmark_grid()
tasks = lapply(c("iris", "sonar"), tsk)
learners = lapply(c("classif.featureless", "classif.rpart"), lrn)
resamplings = rsmp("cv", folds = 3)

design = benchmark_grid(tasks, learners, resamplings)

bmr1 = benchmark(design[1, ])
bmr2 = benchmark(design[2, ])

bms = list(bmr1, bmr2)

final_benchmark <- bms[[1]]$clone(deep = TRUE)
for (i in tail(seq_along(bms), -1)) {
  final_benchmark$combine(bms[[i]])
}
final_benchmark
#> <BenchmarkResult> of 6 rows with 2 resampling runs
#>  nr task_id          learner_id resampling_id iters warnings errors
#>   1    iris classif.featureless            cv     3        0      0
#>   2    iris       classif.rpart            cv     3        0      0
```

<sup>Created on 2020-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by berndbischl** [comment]
No, this is how it was designed. we have a binary, in-place "plus" operation. everything on top of this, seems to go against our philosophy of having "one way" to do things.

If @mllg thinks we can / should and a combine_bmr extra function, we can add it, but its really not necessary?
Note you can also use R's functional programming function "Reduce" to avoid the loop above

**Comment by mllg** [comment]
Fixed via f0b5127faa4ccb3528ea5e8671030c7ec3fea230.

I principally agree with Bernd, there already was a reasonable way to combine multiple BMRs. OTOH, this might be a reoccurring task, so I added combine methods for this.

You can now run `c(bmr1, bmr2)`, `do.call(c, bms)` or even something like `c(resample_result, benchmark_result)`.

**Comment by pat-s** [comment]
> You can now run c(bmr1, bmr2), do.call(c, bms) or even something like c(resample_result, benchmark_result).

This is really neat and makes things a lot easier in practice. Thanks.

> No, this is how it was designed. we have a binary, in-place "plus" operation.

I see your point. Though I think requiring a `Reduce()` or a semi-complicated loop for such an essential operation is really scaring people away. This feature is really for helpful for users in their day to day tasks and I even wonder a bit why no one asked this so far.

**Comment by berndbischl** [comment]
Well, we talked about it here, and we made a careful, slow decision to add redundancy.

> OTOH, this might be a reoccurring task, so I added combine methods for this.

Good, I can see this point as well, just wanted to be "conservative". It is reoccurring and the basic data type is important. 

Just a slight comment: wouldnt "rbind" be a more natural name for the operation? It is a table, not a list?
