### ISSUE TITLE
Benchmarking {mlr} and {mlr3}

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#456]
{mlr3} is almost 10 time slower in this example. 

Attached the screenshots of the profiling. 
Sadly we do not see more after the `do.call()` in `mlr::trainLearner.regr.cvglmnet()`

<details>
<summary>mlr profile</summary>

![Screenshot 2020-03-08 at 19 32 21](https://user-images.githubusercontent.com/8430564/76168901-e0ddff80-6173-11ea-845b-a59341666d79.png)

</details>

<details>
<summary>mlr3 profile</summary>

![Screenshot 2020-03-08 at 19 30 41](https://user-images.githubusercontent.com/8430564/76168905-ec312b00-6173-11ea-94eb-b2cad466a921.png)

</details>

``` r
library(bench)

library(mlr3)
library(mlr3learners)
bench::system_time({
  lrn = mlr3::lrn("classif.glmnet")
  tsk = mlr3::tsk("spam")
  mod = lrn$train(tsk)
  pred = mod$predict(tsk)
  pred$confusion
})
#> process    real 
#>   33.8s   32.7s

suppressPackageStartupMessages(library(mlr))

bench::system_time({
  lrn = mlr::makeLearner("classif.glmnet")
  mod = mlr::train(lrn, mlr::spam.task)
  pred = predict(mod, mlr::spam.task)

  mlr::performance(pred)
})
#> process    real 
#>   3.15s   3.16s
```

<sup>Created on 2020-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mllg** [comment]
The time is spent 99% in Fortran code. I guess you are benchmarking different defaults.

**Comment by mllg** [comment]
A better comparison would be to benchmark vs. mlr's "classif.cvglmnet".

**Comment by pat-s** [comment]
> A better comparison would be to benchmark vs. mlr's "classif.cvglmnet".

Yes, that's correct. We come a bit closer with this by still have a 6 secs diff. 

``` r
library(bench)

library(mlr3)
library(mlr3learners)
bench::system_time({
  lrn = mlr3::lrn("classif.glmnet")
  tsk = mlr3::tsk("spam")
  mod = lrn$train(tsk)
  pred = mod$predict(tsk)
  pred$confusion
})
#> process    real 
#>   34.1s   32.9s

suppressPackageStartupMessages(library(mlr))

bench::system_time({
  lrn = mlr::makeLearner("classif.cvglmnet")
  mod = mlr::train(lrn, mlr::spam.task)
  pred = predict(mod, mlr::spam.task)
  mlr::performance(pred)
})
#> process    real 
#>   28.9s     29s
```

<sup>Created on 2020-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The main diffs timewise are from the glmnet call itself - so yeah probably different defaults between mlr and mlr3.
