### ISSUE TITLE
Parallel reproducibility is not given

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#459]
When performing any stochastic operation via `benchmark()` (e.g. tuning) in parallel via {future}, reproducibility is not given.

This is because `future.seed` in `future_mapply()` is not set.
Even when changing the RNG kind to `"L'Ecuyer-CMRG"` tasks are not reproducible.
To respect a user defined seed, we need to set `future.seed = TRUE` in

https://github.com/mlr-org/mlr3/blob/2d5ccce445aec6ad2d4d84164ba5298ddbd89db1/R/benchmark.R#L114-L122

However, doing so causes `future_mapply()` call to crash.
I had to remove `pb = pb` in the call, otherwise I got

```r
Error in (function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  : 
  zero-length inputs cannot be mixed with those of non-zero length
```

#### Reprex which shows non-reproducibility

``` r
library(mlr3)
library(mlr3pipelines)
library(mlr3tuning)
library(mlr3learners)
library(paradox)

lgr::get_logger("mlr3")$set_threshold("warn")

pim_tsk = tsk("pima")
ih = po("imputehist")
ps = ParamSet$new(list(
  ParamInt$new("classif.ranger.mtry", lower = 1L, upper = 3L),
  ParamDbl$new("classif.ranger.sample.fraction", lower = 0.3, upper = 0.5))
)
cv5 = rsmp("cv", folds = 5)
ranger_lrn = lrn("classif.ranger")
ranger_lrn$predict_type <- "prob"
glrn = ih %>>%
  ranger_lrn
glrn = GraphLearner$new(glrn)
glrn$predict_type = "prob"
cv5$instantiate(pim_tsk)

tuner <- TunerRandomSearch$new()
instance = TuningInstance$new(
  task = pim_tsk,
  learner = glrn,
  resampling = cv5,
  measures = msr("classif.auc"),
  param_set = ps,
  terminator = term("evals", n_evals = 5)
)
instance2 = instance$clone(deep = TRUE)

future::plan(future.callr::callr, workers = 2)

set.seed(1234567, "L'Ecuyer-CMRG")
tuner$tune(instance)

set.seed(1234567, "L'Ecuyer-CMRG")
tuner$tune(instance2)

all.equal(instance$result, instance2$result)
#> [1] "Component \"tune_x\": Component \"classif.ranger.sample.fraction\": Mean relative difference: 0.1523509"
#> [2] "Component \"params\": Component \"classif.ranger.sample.fraction\": Mean relative difference: 0.1523509"
#> [3] "Component \"perf\": Mean relative difference: 0.006161216"
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

#### Working reprex (uses patched mlr3)

Note that when having `future.seed = TRUE` set, even the standard RNG kind ensures reproducibility.

``` r
library(mlr3)
library(mlr3pipelines)
library(mlr3tuning)
library(mlr3learners)
library(paradox)

lgr::get_logger("mlr3")$set_threshold("warn")

pim_tsk = tsk("pima")
ih = po("imputehist")
ps = ParamSet$new(list(
  ParamInt$new("classif.ranger.mtry", lower = 1L, upper = 3L),
  ParamDbl$new("classif.ranger.sample.fraction", lower = 0.3, upper = 0.5))
)
cv5 = rsmp("cv", folds = 5)
ranger_lrn = lrn("classif.ranger")
ranger_lrn$predict_type <- "prob"
glrn = ih %>>%
  ranger_lrn
glrn = GraphLearner$new(glrn)
glrn$predict_type = "prob"
cv5$instantiate(pim_tsk)

tuner <- TunerRandomSearch$new()
instance = TuningInstance$new(
  task = pim_tsk,
  learner = glrn,
  resampling = cv5,
  measures = msr("classif.auc"),
  param_set = ps,
  terminator = term("evals", n_evals = 5)
)
instance2 = instance$clone(deep = TRUE)

future::plan(future.callr::callr, workers = 2)

set.seed(1234567)
tuner$tune(instance)

set.seed(1234567)
tuner$tune(instance2)

all.equal(instance$result, instance2$result)
#> [1] TRUE
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Summary

- suggest to `future.seed = TRUE` to every {future} call
- figure out why the `pb` argument causes the call to fail when `future.seed  = TRUE`

---

- Thanks to the initial report by @missuse
- Note that `resample()` might face the same issue
- Further reference: https://pat-s.me/post/reproducibility-when-going-parallel/

**Comment by mllg** [comment]
Blocked by https://github.com/HenrikBengtsson/future.apply/issues/51.

**Comment by pat-s** [comment]
@mllg future.apply v1.5.0 is on CRAN. Can we proceed here? If you have no time, let me know if I should do it.
