### ISSUE TITLE
task_cbind changes break mlr3pipelines tests

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#461]
The following change in `task_cbind ` (commit: 913d0fff91c562795cffc2d4c1ec4e038c42bb29) 
broke  a few tests in `mlr3pipelines`, as we often cbind a data.frame with 0 rows in order to add columns.

```r
if (is.data.frame(backend)) {
  if (any(dim(backend) == 0L)) {
    return(invisible(task))
  }
}
```

Is this something that could be reverted, or does this actually serve a purpose?
I guess changing `dim(backend)` to `ncol(backend)` might also work out.

Otherwise, I would need to adjust tests.

**Comment by mllg** [comment]
Should be solved.
