### ISSUE TITLE
Feature Request: NA not error on incompatible learner/measure predict_type

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#464]
This is similar to another issue I opened #357 but impacts more on benchmark experiments. This is more of a problem with `mlr3proba` because we have many different predict types but it still applies to mlr3 as in the example below. The reason this matters is because currently if I want to run a large benchmark with many different learners that have different predict types, I'd have to separate all compatible predict types into different experiments, which is inefficient. It would be much more helpful if incompatible pairings just returned NA. This is probably a one line fix and happy to PR if people agree it's useful.

Reprex:

``` r
library(mlr3)
learn = lrn("classif.featureless")
task = tsk("iris")
p = learn$train(task)$predict(task)
p$score(msr("classif.logloss"))
#> Error: Measure 'classif.logloss' requires predict type 'prob'
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by berndbischl** [comment]
we discussed this quite often. we should act therefore slowly here, please, and carefully.
using NAs can also have lot of downsides. 
after you have generated the NA, you don't often know exactly anymore WHY the NA was generated AND (worse) R then continues "calculating" on it. which is exactly what you want here.
but you certainly dont want it in cases where such a behavior "shadows" real bugs or problems.

but, much more concretely:
you code example IMHO is really not "spot on". you demonstrate effect, yes. which is not a bug, but currently defined and intended behavior. your argument is: its inconvenient (in benchmarks).
so i think we should look at SUCH an example, that demonstrates the "clunkyness" of the current system. because i am also not sure, that you are currently using every relevant feature here.

can you please post such an example?

**Comment by berndbischl** [comment]
I mean: benchmark_grid allows you to run every possible combo of tasks, learners and resamplings. thats now maximally flexible. measures are not even in there, they are computed post-hoc.

so, first of all: why would you have to separate experiments? during these exps, only predictions happens, no scoring?

**Comment by RaphaelS1** [comment]
> using NAs can also have lot of downsides.
after you have generated the NA, you don't often know exactly anymore WHY the NA was generated AND (worse) R then continues "calculating" on it. which is exactly what you want here.

Fine but even if we returned some other value, `NULL`, or even `Incompatible`, and then can add to the `log` some details.

> so, first of all: why would you have to separate experiments? during these exps, only predictions happens, no scoring?

Yes but for `aggregate` though.

> can you please post such an example?

This is best demonstrated with `mlr3proba`. So it is often the case that survival models are tested simultaneously for calibration and discrimination, but not all models can handle both. In the example below we want to assess two models for their overall predictive ability and discrimination, but `surv.svm` does not predict `distr` so fails. Now there is a bug somewhere in `mlr3proba` because the error message should be like `Error: Measure 'surv.graf' requires predict type 'distr'`, but that doesn't really matter here. The point is that if we imagine an experiment with many learners and many measures, it would be nice to `aggregate` all at the same time.

``` r
library(mlr3proba); library(mlr3)
learn = lrns(c("surv.kaplan", "surv.svm"))
task = tgen("simsurv")$generate(20)
bm = benchmark(benchmark_grid(task, learn, rsmp("cv", folds = 2)))
bm$aggregate(msrs(c("surv.graf", "surv.harrellC")))
#> Error in distribution$cdf(unique_times): attempt to apply non-function
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by berndbischl** [comment]
> Fine but even if we returned some other value, `NULL`, or even `Incompatible`, and then can add to the `log` some details.

sure. but it still adds a special case to the codebase. makes it more complicated for mlr3. also: n how many places do you now have to act on this special case? probably quite a few? where do you put the handling code? currently, we either generate a valid result or a clean error....
so, you kinda have to convince us a) its practically doable b) its really worth the effort

**Comment by RaphaelS1** [comment]
> where do you put the handling code? currently, we either generate a valid result or a clean error....
so, you kinda have to convince us a) its practically doable b) its really worth the effort

maybe I'm not familiar enough with the `aggregate` method but why is it anymore complicated than adding a single conditional `if measure_type != predict_type skip score and return NULL`

**Comment by berndbischl** [comment]
regarding your example, lets continue there please. that seems most constructive.

a) couldnt i define an easier, basic example, by having 2 classif learners. one predicts probs, the other not. i now want to aggregate the benchmark with classif.ce but also classif.auc.

```
library(mlr3)
l1 = lrn("classif.rpart")
l2 = lrn("classif.rpart", predict_type = "prob")
task = tsk("sonar")
bm = benchmark(benchmark_grid(task, list(l1, l2), rsmp("cv", folds = 2)))
bm$aggregate(msrs(c("classif.ce", "classif.auc")))
```

thats much easier to discuss / unit test in mlr3 with basics then.

b) are you mainly frustrated with aggregate then here?

**Comment by berndbischl** [comment]
> maybe I'm not familiar enough with the `aggregate` method but why is it anymore complicated than adding a single conditional `if measure_type != predict_type skip score and return NULL`

the point is, other parts in mlr3 will act on the score, right? plots? tuning? tests? 
its a different situation if the "contract" of the method is i) a valid number is ALWAYS return vs ii) hey, its either a number or NULL. you know need "handling" code in the calling-places? which can be many?

**Comment by berndbischl** [comment]
in short / summary: you do lose some "type-safety" of the result, right? and prediction score are really not "endpoints" in mlr3, they are "middle points" that many functions potentially act upon. 
in that regard, NA is probably actually better, because than you still keep the basic data type the same. this is why R returns NAs in so many cases, are close to / are actuall errors. but we also know all of the downsides connected with this

**Comment by RaphaelS1** [comment]
> thats much easier to discuss / unit test in mlr3 with basics then.

Good point.

> b) are you mainly frustrated with aggregate then here?

Yes

>  you know need "handling" code in the calling-places? which can be many?

Understood. However, my personal use-case is as follows: I want to run a very large benchmark experiment of all survival models and measures. Having to run the benchmark and then separate out models and measures is going to be frustrating. So I would like either aggregate to do this automatically for me. I see two solutions:

i) I pass one measure at a time and it only returns compatible models
ii) I pass all measures and non-compatible return NA.

Now i) does not suit me as I want to assess all measures, but I could `apply` over these (but for most users they will be frustrated. ii) does suit me as it is no extra work from my side.

I would rather see this changed and be effective in long-term, then have a headache whenever running large experiments.

**Comment by RaphaelS1** [comment]
> in that regard, NA is probably actually better, because than you still keep the basic data type the same. this is why R returns NAs in so many cases, are close to / are actuall errors. but we also know all of the downsides connected with this

My personal preference is NA + either a message or something written in the `log`

**Comment by berndbischl** [comment]
> Understood. However, my personal use-case is as follows: I want to run a very large benchmark experiment of all survival models and measures. Having to run the benchmark and then separate out models and measures is going to be frustrating. So I would like aggregate to do this automatically for me. 

I understand your point, too. and i think something (?) should be done. 
we need to involve @mllg because this is basic API.

what I could suggest now, MIGHT be:
we add an option to "aggregate" that allows the user to get the "NA" instead of the exception. by default this would be "off". we also make this clear in the docs. and might even hint at this in the error message when invalid measure are generated. or this option could even be more general for mlr3. 
it DOES not really solve "my" problem, as also with this option "on", mlr3 should be consistent and roboust. and if my fears are correct it would not be.

or we write down a general solution to handle the NA / NULL case downstream

**Comment by RaphaelS1** [comment]
I think this sounds like a good compromise, or at least it certainly satisfies my use-case and means I can access results as needed without worrying about errors

**Comment by RaphaelS1** [comment]
I'd like to re-open this issue (or rather raise it again) as it has caused some problems locally and I have noticed it is actually currently inconsistent in the current interface. See the reprex below, note that `$score` returns NA (as I want) but `$aggregate` errors. Also CCing @mllg as this is what we were discussing on mattermost.

``` r
library(mlr3)
learners = list(lrn("classif.featureless"),
                lrn("classif.featureless", predict_type = "prob", id = "feat_prob"))
measure = msr("classif.bbrier")
bm = benchmark(benchmark_grid(tsk("pima"), learners, rsmp("cv", folds = 2)))
bm$score(measure)[,c(1,5,10)]
#>    nr          learner_id classif.bbrier
#> 1:  1 classif.featureless            NaN
#> 2:  1 classif.featureless            NaN
#> 3:  2           feat_prob      0.3645833
#> 4:  2           feat_prob      0.3333333
bm$aggregate(measure)
#> Error: Measure 'classif.bbrier' needs predict_type 'prob'
```

<sup>Created on 2020-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mllg** [comment]
Related to #684 .
