### ISSUE TITLE
Errors with $aggregate() and resample()

### ISSUE THREAD

**Issue by andreassot10** [mlr-org/mlr3#471]
I'm trying to get AutoTuner to work with binary classification but resample() and $aggregate() are throwing some not very intuitive errors.

Toy examples below:

**# Example 1: $aggregate() fails with xgboost**
```
library(tidyverse)
library(data.table)
library(paradox)
library(mlr3)
library(mlr3filters)
library(mlr3learners)
library(mlr3measures)
library(mlr3misc)
library(mlr3pipelines)
library(mlr3tuning)
library(mlr3viz)

iris1 <- iris %>%
  slice(1:100) %>%
  mutate(Species = factor(Species)) %>%
  as.data.table

task <- TaskClassif$new("iris1", iris1, 
  target = "Species", positive = "setosa")

learner <- lrn("classif.xgboost", predict_type = "prob")
resampling_inner <- rsmp("cv", folds = 3)
measures <- msr("classif.ce")
tuner = tnr("grid_search", resolution = 4)
terminator <- term("evals", n_evals = 5)
param_set <- ParamSet$new(list(
  ParamFct$new("booster", levels = "gbtree"), 
  ParamInt$new("nrounds", lower = 1, upper = 10), 
  ParamInt$new("max_depth", lower = 3, upper = 10), 
  ParamInt$new("min_child_weight", lower = 0, upper = 10), 
  ParamDbl$new("subsample", lower = 0, upper = 1), 
  ParamDbl$new("eta", lower = 0.1, upper = 0.6),
  ParamDbl$new("colsample_bytree", lower = 0.5, upper = 1),
  ParamInt$new("gamma", lower = 0, upper = 5) # Is it integer or real?
))

at = AutoTuner$new(
  learner, 
  resampling_inner,
  measures = measures,
  param_set, 
  terminator, 
  tuner = tuner)

resampling_outer = rsmp("cv", folds = 2)

rr = resample(task = task, learner = at, 
  resampling = resampling_outer, store_models = TRUE)

rr$aggregate()

##Error in assert_classif(truth, response = response) : Assertion on 'truth' failed: Must have length >= 1, but has length 0.
```

**# Example 2: resample() fails with rpart**
```
library(tidyverse)
library(data.table)
library(janitor)
library(paradox)
library(mlr3)
library(mlr3filters)
library(mlr3learners)
library(mlr3measures)
library(mlr3misc)
library(mlr3pipelines)
library(mlr3tuning)
library(mlr3viz)

iris1 <- iris %>%
  slice(1:100) %>%
  mutate(Species = factor(Species)) %>%
  as.data.table

task <- TaskClassif$new("iris1", iris1, 
  target = "Species", positive = "setosa")

learner = lrn("classif.rpart")
resampling_inner <- rsmp("cv", folds = 3)
measures = msr("classif.ce")
tuner = tnr("grid_search", resolution = 4)
terminator <- term("evals", n_evals = 5)
param_set = ParamSet$new(
  params = list(ParamDbl$new("cp", lower = 0.001, upper = 0.1)))

at = AutoTuner$new(
  learner, 
  resampling_inner,
  measures = measures,
  param_set, 
  terminator, 
  tuner = tuner)

resampling_outer = rsmp("cv", folds = 2)

rr = resample(task = task, learner = at, 
  resampling = resampling_outer, store_models = TRUE)

##Error in 1:numclass : result would be too long a vector
##In addition: Warning message:
##In max(y[!is.na(y)]) : no non-missing arguments to max; returning -Inf

rr$aggregate()

##Error: object 'rr' not found
```

**Comment by missuse** [comment]
Hello

you should specify the measure to aggregate by:

`rr$aggregate(msr("classif.ce"))`

Should work

**Comment by mllg** [comment]
> EDIT: actually your example 1 works for me with fresh package versions from github. I just had to unload mlr3measures
> 
> `detach("package:mlr3measures", unload=TRUE)`
> 
> since it overrides `tnr` from `mlr3tuning`

This is something we need to communicate better -- it is probably never a good idea to attach mlr3measures. I'll update the README and add a package startup message.

**Comment by mllg** [comment]
> # Example 2: resample() fails with rpart

I have trouble reproducing this. Can you post your `sessionInfo()`?

**Comment by missuse** [comment]
> > # Example 2: resample() fails with rpart
> 
> I have trouble reproducing this. Can you post your `sessionInfo()`?

Neither could I.

**Comment by andreassot10** [comment]
> 
> 
> Hello,
> 
> For the first example you should specify the measure to aggregate by:
> 
> `rr$aggregate(msr("classif.ce"))`
> 
> Should work
> 
> EDIT: actually your example 1 works for me with fresh package versions from github. I just had to unload mlr3measures
> 
> `detach("package:mlr3measures", unload=TRUE)`
> 
> since it overrides `tnr` from `mlr3tuning`



> 
> 
> > EDIT: actually your example 1 works for me with fresh package versions from github. I just had to unload mlr3measures
> > `detach("package:mlr3measures", unload=TRUE)`
> > since it overrides `tnr` from `mlr3tuning`
> 
> This is something we need to communicate better -- it is probably never a good idea to attach mlr3measures. I'll update the README and add a package startup message.

Both,

Many thanks for the tips.

I've re-installed all mlr3 packages from GitHub, re-run the script without loading mlr3measures and everything's working just fine.

**Comment by andreassot10** [comment]
> 
> 
> Hello,
> 
> For the first example you should specify the measure to aggregate by:
> 
> `rr$aggregate(msr("classif.ce"))`
> 
> Should work
> 
> EDIT: actually your example 1 works for me with fresh package versions from github. I just had to unload mlr3measures
> 
> `detach("package:mlr3measures", unload=TRUE)`
> 
> since it overrides `tnr` from `mlr3tuning`



> 
> 
> > EDIT: actually your example 1 works for me with fresh package versions from github. I just had to unload mlr3measures
> > `detach("package:mlr3measures", unload=TRUE)`
> > since it overrides `tnr` from `mlr3tuning`
> 
> This is something we need to communicate better -- it is probably never a good idea to attach mlr3measures. I'll update the README and add a package startup message.

Both,

Many thanks for the tips.

I've re-installed all mlr3 packages from GitHub, re-run the script without loading mlr3measures and everything's working just fine.

**Comment by andreassot10** [comment]
> 
> 
> > > # Example 2: resample() fails with rpart
> > 
> > 
> > I have trouble reproducing this. Can you post your `sessionInfo()`?
> 
> Neither could I.

See below, FYI (although, as I mentioned earlier, it all works fine now):

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mlr3viz_0.1.1       mlr3tuning_0.1.2    mlr3pipelines_0.1.2 mlr3misc_0.1.8     
 [5] mlr3learners_0.1.6  mlr3filters_0.2.0   mlr3_0.1.8          paradox_0.1.0      
 [9] janitor_1.2.1       data.table_1.12.8   forcats_0.4.0       stringr_1.4.0      
[13] dplyr_0.8.4         purrr_0.3.3         readr_1.3.1         tidyr_1.0.2        
[17] tibble_2.1.3        ggplot2_3.2.1       tidyverse_1.3.0    

loaded via a namespace (and not attached):
 [1] tidyselect_1.0.0   mlr3measures_0.1.2 haven_2.2.0        lattice_0.20-38   
 [5] colorspace_1.4-1   vctrs_0.2.4        generics_0.0.2     rlang_0.4.5       
 [9] pillar_1.4.3       glue_1.3.1         withr_2.1.2        DBI_1.1.0         
[13] dbplyr_1.4.2       modelr_0.1.5       readxl_1.3.1       uuid_0.1-2        
[17] lifecycle_0.1.0    munsell_0.5.0      gtable_0.3.0       cellranger_1.1.0  
[21] rvest_0.3.5        fansi_0.4.1        broom_0.5.4        Rcpp_1.0.3        
[25] scales_1.1.0       backports_1.1.5    checkmate_1.9.4    jsonlite_1.6.1    
[29] fs_1.3.1           digest_0.6.23      hms_0.5.3          packrat_0.5.0     
[33] stringi_1.4.4      grid_3.6.2         cli_2.0.1          tools_3.6.2       
[37] magrittr_1.5       lazyeval_0.2.2     crayon_1.3.4       pkgconfig_2.0.3   
[41] xml2_1.2.2         reprex_0.3.0       lubridate_1.7.4    assertthat_0.2.1  
[45] httr_1.4.1         rstudioapi_0.10    rpart_4.1-15       lgr_0.3.3         
[49] R6_2.4.1           nlme_3.1-142       compiler_3.6.2

**Comment by mllg** [comment]
Ok, this was an issue with outdated / incompatible packages then. Glad you figured it out.
