### ISSUE TITLE
insample - resampling instance

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#472]
@berndbischl asked me to open this issue.

A cool thing to be able to do would be able to evaluate a task on the training data.

A possible idea would be to have a `rsmp("insample")`: 
where train-data = test-data = all rows

This would then, for example, be used in `PipeOpLearnerCV` on so on.

**Comment by mllg** [comment]
If I understood this issue correctly, it should be solved via 13ef8b91380b7b0eb8cc863a4580e0bb29337f3d... ?

**Comment by pfistfl** [comment]
Yes, thanks!
