### ISSUE TITLE
export auto_convert + fix ordered to factor

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#475]
I would need `auto_convert` for type conversion in `mlr3pipelines`, so exporting would be nice.

Additionally, it would be cool if factor -> ordered conversion worked without supplying levels
(this is possible as a factor already knows it's levels).

**Comment by pfistfl** [comment]
> Possible, but how can you be sure that the levels are in the right order?
I just supplied the levels in mlr3pipelines, I guess you can only make sure this holds on a case by case basis.

The last thing I currently can not do is `factor` -> `logical` conversion, if the input is a factor of 
logicals, i.e.

> [1] TRUE
> Levels: FALSE TRUE

I guess in this case, it should be possible and fail in others?

**Comment by mllg** [comment]
Should be fixed now, re-open if I missed something.
