### ISSUE TITLE
Get backend from which a column originates

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#476]
Given I have a `Task` and a column name, how do I get a reference to the `DataBackend` from which the column originates?

Purpose: Suppose I have a task `T1`, some data `D1` and some data `D2`. Some operation performs
```r
T2 = T1$clone(deep = TRUE)
T1$cbind(D1)
T2$cbind(D2)
```
I now want to merge all columns into one `Task`. I can just do something like
```r
T1$cbind(T2$backend)
```
with some more updating of col role info.

I want this merge to err out if there are name clashes between columns that do not contain identical data (i.e. columns getting overwritten). Otherwise I want to ignore name clashes since no data is getting lost.

 If  `D1` and `D2` both contain a column with the same name I would have to check for equality. If `D1` contains a column that "overwrites" a column of the original `T1` I would also have to check for equality since the offending column originates from two different backends as well. But knowing what columns in `T1` and in `T2` have the same name *and* come from the same data backend would be a quick check that would avoid comparing data most of the time.

**Comment by mllg** [comment]
Closed via #703
