### ISSUE TITLE
Nested Resampling Error

### ISSUE THREAD

**Issue by hp2500** [mlr-org/mlr3#478]
Hi there, 
I am running into errors when I try to implement nested resampling, even when I use the example form the book verbatim: 

```{r}
library("mlr3tuning")
task = tsk("iris")
learner = lrn("classif.rpart")
resampling = rsmp("holdout")
measures = msr("classif.ce")
param_set = paradox::ParamSet$new(
  params = list(paradox::ParamDbl$new("cp", lower = 0.001, upper = 0.1)))
terminator = term("evals", n_evals = 5)
tuner = tnr("grid_search", resolution = 10)

at = AutoTuner$new(learner, resampling, measures = measures,
                   param_set, terminator, tuner = tuner)

resampling_outer = rsmp("cv", folds = 3)
rr = resample(task = task, learner = at, resampling = resampling_outer)
```

This is the error I am getting: 
Error in resample(task = task, learner = at, resampling = resampling_outer) : 
  Assertion on 'resampling' failed: Must inherit from class 'ResampleInstance', but has classes 'ResamplingCV','Resampling','R6'.

Do you know what is wrong?

**Comment by mllg** [comment]
I cannot reproduce this. Can you update all packages (`update.packages()`), try again and post your `sessionInfo()`?

**Comment by hp2500** [comment]
Figured it out, thanks!

**Comment by jpconnel** [comment]
Hello, I get the same error when running the Nested Resampling example on the mlr3tuning Auto Tuner page (https://mlr3tuning.mlr-org.com/reference/AutoTuner.html#:~:text=Nested%20resampling%20is%20performed%20by,%3D%20TRUE%20(see%20examples).

````
# Nested Resampling

at = auto_tuner(
  tuner = tnr("random_search"),
  learner = learner,
  resampling = rsmp ("holdout"),
  measure = msr("classif.ce"),
  term_evals = 4)

resampling_outer = rsmp("cv", folds = 3)
rr = resample(task, at, resampling_outer, store_models = TRUE)
````

Any ideas of the errors cause?

**Comment by larskotthoff** [comment]
Can't reproduce your error. Did you accidentally overwrite `learner` with the task?

**Comment by jpconnel** [comment]
Thank you, It seems that was happening. I cleaned things up now and it works
