### ISSUE TITLE
Learners: `run_paramtest()` does not check "predict" args

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#481]
Only "train" args.
Already stumbled across an instance where "predict" args are missing.

**Comment by mllg** [comment]
`run_paramtest()` simply compares the list of parameters with the formal arguments of a single function. So yes, predict args are usually not tested if you just compare the arguments with the model-fitting function. I guess you have to call `run_paramtest()` twice then? 

@be-marc

**Comment by pat-s** [comment]
This is mostly a "ToDo" issue for me to check also the S3 predict functions of the learners in the ParamTest. Not a shortcoming of the implementation 🙂

**Comment by pat-s** [comment]
Done now for most learners. And yes, simply calling it twice is the way to go here.
