### ISSUE TITLE
Fuse mlr_task_generators and mlr_tasks

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#484]
The user does not care whether he creates a parameterized task or just a dataset.

**Comment by mllg** [comment]
I see your point. I wanted to have it separate be able to interface simulators -- or more general, any data generating processes where you are in control of the sample size. This is not used in any package yet. However, I like having everything set up for such a use case. It is only a minor inconvenience for the user, right?

**Comment by berndbischl** [comment]
i agree with michel. its different to call a function than to ask for a static object. 
yes, we could unify that. but that only changes API without any great benefit?

**Comment by berndbischl** [comment]
i would vote to close
