### ISSUE TITLE
Creating a custom measure

### ISSUE THREAD

**Issue by neverfox** [mlr-org/mlr3#490]
Is there a way currently to create a custom measure (just for local use, rather than as part of a submission to the package)? I've tried digging into how the measures are generated but can't seem to figure out how to take a custom function and make it work as an measure.

What I have so far, but `tnll` doesn't have any function for `score` and I have no idea how to give it one.
```
preds <- learner$predict(task_train)

tweedie_nloglik <- function(truth, response, p = 1.5, ...) {
  loss = -truth * response^(1 - p) / (1 - p) + response^(2 - p) / (2 - p)
  mean(loss)
}

tnll <- MeasureRegr$new(
  "tweedie_nloglik",
  range = c(0, Inf),
  minimize = TRUE
)
```
I can manually do this but wanting something I can use as the measure param of things like auto-tuning.
```
tweedie_nloglik(preds$truth, preds$response, p = 1.85)
```

**Comment by neverfox** [comment]
Is this it?

```
MeasureTweedieNLL = R6Class("MeasureTweedieNLL",
  inherit = MeasureRegr,
  public = list(
    initialize = function() {
      super$initialize(
        id = "tweedie_nloglik",
        properties = c("requires_learner"),
        predict_type = "response",
        range = c(0, Inf),
        minimize = TRUE
      )
    }
  ),

  private = list(
    .score = function(prediction, learner, ...) {
      p = learner$param_set$values$tweedie_variance_power
      tweedie_nloglik(prediction$truth, prediction$response, p)
    }
  )
)

mlr_measures$add("tweedie_nloglik", MeasureTweedieNLL)
```

**Comment by mllg** [comment]
> Is this in the right direction?

Yes, looks good!

Note to self: We need a section on this in the mlr3book... I'll open an issue over there.

Let us know if something is still missing or unclear.

**Comment by mllg** [comment]
Added some docs to the book, re-open if something is still unclear.
