### ISSUE TITLE
Groupinf information is treated as a normal feature

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr3#496]
I tried to use the goup setting in the task, and the grouping seems to work when i generate a resamoling set.

But seemingly the grouping information is seen as a normal feature even after removing it:

task =  as_data_backend(rbind(fingerprintsAll),dense = data.frame(vals = c(vals),blocks = blocks))   %>%      TaskRegr$new(id = "prints", backend = ., target = "vals")

task$col_roles$group = "blocks"
task$col_roles$feature = setdiff(task$col_roles$feature, "blocks")

So far so good but then this happens after training a model:
pred <-  predict(learner,as.data.frame(as.matrix(fingerprintsAllVal)))
Error: Cannot rbind data to task 'prints', missing the following mandatory columns: blocks

By the way it is strange that the predict function needs a data.frame while the rest of mlr3 works super well with sparse matrices. Would be great if this could be fixed.

Just to make sure:
which(task$col_roles$feature == "blocks")
gives  integer(0)

and even 
 fingerprintsAllVal <- cbind(fingerprintsAllVal,NA)
> dimnames(fingerprintsAllVal)[[2]][2258] = "blocks"
> pred <-  predict(learner,as.data.frame(as.matrix(fingerprintsAllVal)))
Error: Cannot rbind data to task 'prints', missing the following mandatory columns: blocks

does not help

**Comment by mllg** [comment]
One assertion was too strict and is now relaxed. Thanks for reporting.
