### ISSUE TITLE
Error when using  msr("oob_error")

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr3#498]
The msr("oob_error") does nor work for tuning with ranger:
 
I get the following error:
Error in super$initialize(id, special_vals = special_vals, default = default,  : 
  Assertion on 'tags' failed: Contains missing values (element 1).

measuresRF <- msr("oob_error")
resampling_opt_RF = rsmp("holdout", ratio = 0.90)
atRF = AutoTuner$new(learnerRF, resampling_opt_RF, measuresRF, param_setRF, evals, tuner)
atRF$store_tuning_instance = TRUE

atRF$train(task)
Error in super$initialize(id, special_vals = special_vals, default = default,  : 
  Assertion on 'tags' failed: Contains missing values (element 1).

If I use  measuresRF <- msr("classif.auc")
It works just fine,

oob.error = TRUE was set for Ranger

**Comment by ThomasWolf0701** [comment]
atRF
<AutoTuner:filter1.filter2.classif.ranger.tuned>
* Model: -
* Parameters: filter1.filter.frac=0.5, filter1.affect_columns=<Selector>, filter2.filter.frac=0.5, filter2.affect_columns=<Selector>,
  classif.ranger.num.trees=100, classif.ranger.splitrule=extratrees, classif.ranger.keep.inbag=TRUE, classif.ranger.num.threads=1,
  classif.ranger.oob.error=TRUE
* Packages: -
* Predict Type: prob
* Feature types: logical, integer, numeric, character, factor, ordered, POSIXct
* Properties: importance, missings, multiclass, oob_error, selected_features, twoclass, weights

**Comment by pat-s** [comment]
Can you please format the code in your issues and include a reprex? Happy to re-open if both are true.
