### ISSUE TITLE
The benchmark function does not use multiple cores

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr3#499]
I am trying this on Windows 10

Given an autotuner
atXG = AutoTuner$new(learnerXg, resampling_opt, measuresXG, param_setXg, evals, tuner)

I initialize the backend:
future::plan("multiprocess")

And parlalization works just fine.

But when using the same autotuner  in a benchmark setting only one core is being used

**Comment by ThomasWolf0701** [comment]
For clarification if I use two learners it does actually use two cores.
The inner cv loop is a  3 fold cross validation for random search the outer is a holdout resampling.
So it seems as if it only parallelizes the outer loop, but neither the tuning nor the inner resampling,
The manual says that mlr3 handles the levels of the parallelization as opposed to mlr where I had to specifiy myself.

**Comment by pat-s** [comment]
Please format the code in your issues and include a reprex.

Parallelization works just fine and is unit tested across all levels in mlr3 so the problem is on your side. We're happy to help if appropriate information is supplied.

**Comment by mllg** [comment]
Please provide a reproducible example. In particular, I need to know which tuner and which resampling is used here.

**Comment by mllg** [comment]
We exhaustively tested this for a different issue, this really should work now.
