### ISSUE TITLE
Creating a TaskClassif Leads to an Empty Object

### ISSUE THREAD

**Issue by gprinz** [mlr-org/mlr3#500]
**Environment**
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Switzerland.1252     
 ctype    German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2020-05-11 

**Packages**

- mlr3verse

**Steps to reproduce**

Follow the steps described here: [Documentation](https://mlr3book.mlr-org.com/tasks.html)

```
task_iris = mlr_tasks$get("iris")
print(task_iris)
```

Results in 

![image](https://user-images.githubusercontent.com/32190139/81568311-df140080-939d-11ea-97cc-313d01344ae5.png)

instead of

```
## <TaskClassif:iris> (150 x 5)
## * Target: Species
## * Properties: multiclass
## * Features (4):
##   - dbl (4): Petal.Length, Petal.Width, Sepal.Length, Sepal.Width
```

As a consequence, 

```
  ps <- makeParamSet(
    makeNumericParam("cp", 0.0, 1.0))
  
  control <- makeTuneControlMBO()
  
  rdesc = makeResampleDesc("CV", iters = 2L)
  
  model = tuneParams("classif.rpart", task_iris, rdesc, par.set = ps, control = control)

```

fails when combined with task_iris. The same applies if an oqn task is created with TaskClassif (see here: https://mlr3.mlr-org.com/reference/TaskClassif.html).

**Comment by mb706** [comment]
You are mixing `mlr` and `mlr3` here (ParamHelpers and mlrMBO are old-mlr), which doesn't work (sorry about that). If you want to use mlrMBO with mlr3, you can try https://github.com/mb706/mlrintermbo or just use the old `mlr`.

**Comment by mllg** [comment]
Yep, looks like ParamHelpers/mlr got loaded in your session. Reopen if this is not the case.
