### ISSUE TITLE
Problem to Generate a Benchmark Grid Design

### ISSUE THREAD

**Issue by mohammadreza-sheykhmousa** [mlr-org/mlr3#504]
I am using same example as yours when in r-studio server use:
`?benchmark_grid`
However this results an error. Here are the code and result and related session info. 
### Code:
`tasks = list(tsk("iris"), tsk("sonar"))
learners = list(lrn("classif.featureless"), lrn("classif.rpart"))
resamplings = list(rsmp("cv"), rsmp("subsampling"))
design = benchmark_grid(tasks, learners, resamplings)
bmr = benchmark(design)
bmr$aggregate(msr("classif.acc"))[,.(task_id, learner_id, classif.acc)]`

### Error:
`
> tasks = list(tsk("iris"), tsk("sonar"))
> learners = list(lrn("classif.featureless"), lrn("classif.rpart"))
> resamplings = list(rsmp("cv"), rsmp("subsampling"))
> design = benchmark_grid(tasks, learners, resamplings)
> bmr = benchmark(design)
INFO  [15:49:37.815] Benchmark with 160 resampling iterations 
Error in (function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  : 
  zero-length inputs cannot be mixed with those of non-zero length`
### session info:
`>sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.3/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] R6_2.4.1             mlr3viz_0.1.1.9002   survival_2.44-1.1    DataExplorer_0.8.0   ggplot2_3.3.0.9000  
 [6] data.table_1.12.8    glmnet_2.0-16        foreach_1.5.1        Matrix_1.2-15        paradox_0.2.0       
[11] mlr3tuning_0.1.2     mlr3filters_0.2.0    mlr3pipelines_0.1.3  mlr3learners_0.2.0   mlr3_0.2.0-9000     
[16] xda_0.2              RevoUtils_11.0.3     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5   xfun_0.6           purrr_0.3.2        listenv_0.7.0      splines_3.5.3      lattice_0.20-38   
 [7] colorspace_1.4-1   htmltools_0.3.6    rlang_0.3.4        pillar_1.3.1       glue_1.3.1         withr_2.1.2       
[13] uuid_0.1-2         networkD3_0.4      munsell_0.5.0      gtable_0.3.0       future_1.12.0      htmlwidgets_1.3   
[19] codetools_0.2-16   evaluate_0.13      knitr_1.22         parallel_3.5.3     Rcpp_1.0.1         scales_1.0.0      
[25] backports_1.1.4    checkmate_2.0.0    gridExtra_2.3      digest_0.6.18      dplyr_0.8.0.1      grid_3.5.3        
[31] tools_3.5.3        magrittr_1.5       tibble_2.1.1       mlr3misc_0.2.0     crayon_1.3.4       future.apply_1.2.0
[37] pkgconfig_2.0.2    assertthat_0.2.1   rmarkdown_1.12     rstudioapi_0.10    iterators_1.0.11   lgr_0.3.4         
[43] globals_0.12.4     igraph_1.2.5       compiler_3.5.3`

In general mlr3 works perfect with single classifier, however I have always problem when using multiple learners. I have tried with one task yet didn't work. Also maybe worths mentioning that I tried to use ensemble learner exactly the sme as [THIS](https://mlr3gallery.mlr-org.com/posts/2020-01-30-house-prices-in-king-county/) however when `:bmr$aggregate()`facing with with below error:
`> bmr$aggregate()
Error: attempt to apply non-function.` 

I deeply appreciate any help.
@mllg @berndbischl 
#mlr3 #r

**Comment by berndbischl** [comment]
I have migrated the issue to mlr3 where it belongs

**Comment by berndbischl** [comment]
Ok, i just checked your reprex. 
I check BOTH with mlr3 from Github and the Current CRAN version. Both produce no error but the correct result.

- It is very unlikely that such a basic setup / test case is not covered by our extensive unit tests
- I see you are using and outdatet version of mlr3 

> mlr3_0.2.0-9000

---->

Can you pls update and check in the same way that I did? Or provide further info?
Otherwise we would have to close here

**Comment by Geomaan** [comment]
@berndbischl, First of all, I appreciate your prompt reply. I am trying to remotely connect to my local machine and update the package as you mentioned. Will provide the result asap.

**Comment by pat-s** [comment]
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

Also please try to format your post a bit better, it is almost unreadable in its current state.

**Comment by berndbischl** [comment]
> Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example),

he did do that? it simply doesn't seem to produce the error on my side that he claims is being produced? but the code itself i could directly run

**Comment by pat-s** [comment]
Thanks, way better now.

I'd suggest updating all future* packages and trying again.

**Comment by Geomaan** [comment]
Thank you @pat-s  your solution worked. Amazing to run mlr3. I am willing to also contribute to the project. Also tnx to @RaphaelS1 @berndbischl .




``` r

library(mlr3)
library(mlr3learners)
library(mlr3pipelines)
library(mlr3filters)
library(mlr3tuning)
library(mlr3proba)
library(paradox)
library(glmnet)
#> Loading required package: Matrix
#> Loading required package: foreach
#> Loaded glmnet 2.0-16
library(data.table)
library(ggplot2)
library(DataExplorer)
library(survival)
library(mlr3viz)
library(R6)
library(reprex)

tasks = list(tsk("iris"), tsk("sonar")) 
learners = list(lrn("classif.featureless"), lrn("classif.rpart")) 
resamplings = list(rsmp("cv"), rsmp("subsampling")) 
design = benchmark_grid(tasks, learners, resamplings) 
bmr = benchmark(design) 
#> INFO  [16:08:03.721] Benchmark with 160 resampling iterations 
#> INFO  [16:08:03.922] Applying learner 'classif.rpart' on task 'sonar' (iter 20/30) 
#> INFO  [16:08:04.081] Applying learner 'classif.featureless' on task 'sonar' (iter 5/30) 
#> INFO  [16:08:04.126] Applying learner 'classif.featureless' on task 'iris' (iter 7/30) 
#> INFO  [16:08:04.170] Applying learner 'classif.featureless' on task 'iris' (iter 1/10) 
#> INFO  [16:08:04.219] Applying learner 'classif.featureless' on task 'iris' (iter 12/30) 
#> ....
#> INFO  [16:08:13.121] Finished benchmark
bmr$aggregate(msr("classif.acc"))[,.(task_id, learner_id, classif.acc)]
#>    task_id          learner_id classif.acc
#> 1:    iris classif.featureless   0.1933333
#> 2:    iris classif.featureless   0.2733333
#> 3:    iris       classif.rpart   0.9333333
#> 4:    iris       classif.rpart   0.9373333
#> 5:   sonar classif.featureless   0.5330952
#> 6:   sonar classif.featureless   0.5053140
#> 7:   sonar       classif.rpart   0.6828571
#> 8:   sonar       classif.rpart   0.6956522
```

<sup>Created on 2020-06-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pat-s** [comment]
I don't think there is a relation to the R version or operating system.

I do not get the error for myself in RStudio.
The reprex package runs the code in a fresh R session.
I am not fully sure but I think reprex's are not run in the RStudio console but in a separate fresh background process.

I assume there were some conflicts in the current session when both of you tried it (maybe mlr was loaded before?).
Anyway, as long as the reprex in a fresh session runs fine, we should not worry further.
Also, we have a lot of tests - and many other users running RStudio :)

**Comment by pfistfl** [comment]
So, running in a **clean, new** session from within RStudio (executing line by line @berndbischl) 

The following code runs fine: 
```
library(reprex)
reprex({
  library(mlr3)
  library(mlr3learners)
  design = benchmark_grid(tasks = list(tsk("iris"), tsk("german_credit")),learners = list(lrn("classif.ranger"), lrn("classif.rpart")),resamplings = list(rsmp("cv")))
  bmr = benchmark(design)
  bmr$aggregate(msr("classif.acc"))[,.(task_id, learner_id, classif.acc)] 
})
```

Running the code inside the `reprex` crashes my RSession. (I do not get any errors, just the R Session aborted screen). 

I'll re-install a few libraries and see whether I can find the culprit.

**Comment by berndbischl** [comment]
> if there is some problem in the interaction between mlr3 and something in RStudio, we would not detect it.

sure, but I have ABSOLUTELY no idea why there should be. And I have never heard as a recommendation for package devs to test against RStudio....

**Comment by pfistfl** [comment]
I seem to be unable to reproduce this anywhere else, so I would take it down as "some weird config".

**Comment by berndbischl** [comment]
> I seem to be unable to reproduce this anywhere else, so I would take it down as "some weird config".

probably.

**Comment by pat-s** [comment]
From my exp so far session crashes/segfaults in RStudio were most often related to some weird C errors in compiled packages when some underlying libraries or compilers changed/were updated.

Maybe you can try reinstalling all mlr3 deps again with `remotes::install_github("mlr-org/mlr3", dependencies = TRUE, force = TRUE)` and try again. @pfistfl
