### ISSUE TITLE
`score()` a ResampleResult on specific data segments

### ISSUE THREAD

**Issue by JazzyPierrot** [mlr-org/mlr3#505]
Hi, I am rather new to mlr3, sorry in advance if my question is out of place.

When I have a ResampleResult (or a BenchmarkResult), I sometimes want to inspect the score of my model on specific data segments; let's say for instance I have several clusters and I would like to know on which the model performs the worse. My first instinct was to `rr$clone()$filter(ids)$score()` but the filter method filters iterations, not data. I noticed as well that a Prediction object has no filter method which could help for this. 

Is there an elegant way to do this inside mlr3 ? If not, this feature would be of great help to me (and maybe to others). 

Thank you for your great work.

**Comment by berndbischl** [comment]
> Hi, I am rather new to mlr3, sorry in advance if my question is out of place.

stackoverflow is also possible, maybe preferred, but i guess we answer quicker here, and this is an OK question for here i guess - especially if we figure out that our docs / examples are not good enough.

> When I have a ResampleResult (or a BenchmarkResult), I sometimes want to inspect the score of my model on specific data segments; let's say for instance I have several clusters and I would like to know on which the model performs the worse. My first instinct was to `rr$clone()$filter(ids)$score()` but the filter method filters iterations, not data. I noticed as well that a Prediction object has no filter method which could help for this.

are you aware of the rr$prediction(s) accessor functions?

```
library(mlr3)
task = tsk("iris")
ll = lrn("classif.rpart")
rs = rsmp("cv", folds = 2L)
rr = resample(task, ll, rs)
p = rr$prediction()
print(p)
```

the above joins all press from the CV into a nice DT. and ids are there. now simply work on the DT as you are used to with tabular data - mlr3's basic philosophy.

```
<PredictionClassif> for 150 observations:
    row_id     truth  response
         2    setosa    setosa
         4    setosa    setosa
         6    setosa    setosa
---
       147 virginica virginica
       148 virginica virginica
       150 virginica virginica
>

```

**Comment by berndbischl** [comment]
if you want to have one DT per fold use "$predictions" (mind the plural-s)

**Comment by berndbischl** [comment]
ah, wait or are you asking about the POINT-WISE LOSSES on all of these points?

**Comment by JazzyPierrot** [comment]
Thank you for your quick reply ! 
I am not sure about what you exactly mean with point-wise losses, but what I was thinking of is about evaluation metrics (for instance from mlr3_measures) on subsets, not only predictions.

For instance, let's say that I am particularly interested in the performance of the model of all even IDs on the iris task. 
One way to do it is of course to extract predictions in a DT, subset, transform back to a prediction and use measures  (I actually did not immediately thought about that - that happens when you can do so many things without leaving the mlr3 framework). 
```
library(mlr3)
library(data.table)
task = tsk("iris")
ll = lrn("classif.rpart")
rs = rsmp("cv", folds = 2L)
rr = resample(task, ll, rs)
p = as.data.table(rr$prediction())

## Define a new Prediction for even ids 
sub_dt = p[row_id %/% 2]
sub_p = PredictionClassif$new(
  row_ids =sub_dt$row_id,
  truth = sub_dt$truth,
  response = sub_dt$response
)

## And finally evaluate
eval = msr("classif.acc")$score(sub_p)
```
This is however a bit tedious, especially if the same is needed for benchmarks, several measures, etc. Maybe I am still missing something here, but I was hoping for something more direct, without transforming back and forth, for instance like a direct:
```
ids = 2* (1:74)
rr$score(msr("classif.acc"), subset = ids)
# or 
rr$aggregate(msr("classif.acc"), subset = ids)
```
