### ISSUE TITLE
Can training data be extracted from learner?

### ISSUE THREAD

**Issue by hkren** [mlr-org/mlr3#516]
I would like to share a trained model with someone else such that they can check wheather or not the model works for their data. However, they are not(!) allowed see the data that I used to train the model due to data privacy issues. So my question is: if I am saving a trained learner as rds file and send it to someone, can the person extract the original training data from that object somehow?

**Comment by mllg** [comment]
mlr3 does not store the training data itself (except for knn which does not have a training step other than storing the data), **but** the model we fit may hold a copy of it. So it boils down to whether or not you would be fine sharing a "manually" fitted model or not.

**Comment by mllg** [comment]
I might be able to help if you specify which learner you want to train.

**Comment by hkren** [comment]
Thanks for the answer. I am working with the classification learners glmnet, log_reg, svm and ranger. It would be important that the shared models do not hold a copy of the data. Sharing the weights (e.g. of the logistic regression) would be fine however. I am not sure what you mean with a "manually" fitted model, since I compute the models within the MLR3 environment.

**Comment by mllg** [comment]
I'm pretty sure that ranger does not store the data. I'm unsure about glmnet. Logistic regression and SVM store a copy of the training data.

This is a simplified version of what mlr3 does internally:
```r
fit_log_reg = function(data, target) {
  formula = reformulate(setdiff(names(data), target), target)
  model = glm(formula, data = data, family = "binomial", model = FALSE)
}

model = fit_log_reg(Sonar, "Class")
```
The data is stored as element `data` of `model`:
```r
str(model$data)
```


Same for the SVM, but harder to find:

```r
fit_svm = function(data, target) {
  formula = reformulate(setdiff(names(data), target), target)
  model = e1071::svm(formula, data = data)
}

model = fit_svm(Sonar, "Class")
str(environment(model$terms)$data)
```


You can try your luck with the `butcher` package. It is intended to strip not required objects from the returned model. To apply it to mlr3 models, call something like this prior to saving the learner:

```r
learner$state$model = butcher::axe_env(learner$model)
learner$state$model = butcher::axe_call(learner$model)
```

mlr3 will probably support something similar in the future (https://github.com/mlr-org/mlr3/issues/404), but we are not there yet.

**Comment by hkren** [comment]
This is already helping me a lot. Thanks for the explanation!
