### ISSUE TITLE
prediction objects

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr3#52]
What always disliked in mlr is that manually creating prediction objects was always difficult.
Currently, it seems that we can only create prediction objects by passing a task.
Suppose I have a vector of predictions and a vector of true values. It would be great if I could use mlr3 to construct a prediction object just using this (+ possibly other information such as predict.type...). 
Any thoughts?

**Comment by berndbischl** [comment]
I think it is important that something like this works in order to allow for multiple entry points into the package

**Comment by berndbischl** [comment]
Each class should if possible have a well documented constructor that allows manual construction of the object. And not only construction through an mlr function call as predict

**Comment by mllg** [comment]
With c757a10193c826354a568c9e84019451946a4f56 you can now construct prediction objects with `truth` and `response`.
