### ISSUE TITLE
Issue in `mlr3 v0.4.0` predict in case of integer features  

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr3#533]
This issue occurs only with the new mlr3 v0.4.0 and breaks a lot of things in, e.g., the `iml` package.
A model trained on an **integer** feature can not make predictions if the test data stores this feature as **double**.

```r
library("mlr3")
library("mlr3learners")
library("iml")

credit.task = tsk("german_credit")
lrn = lrn("classif.ranger", predict_type = "prob")

set.seed(123)
model = lrn$train(credit.task)
data = credit.task$data()
class(data$duration)
# [1] "integer"
data$duration = data$duration + 0.001
class(data$duration)
# [1] "numeric"
predict(model, newdata = data)
# Fehler: Incompatible types during auto-converting column 'duration': failed to convert from class 'numeric' to class 'integer'
```

Not sure if it makes sense to enforce that a feature must be an integer if it was trained on an integer feature. Sometimes it is required to e.g., compute derivatives where it is necessary to make predictions for `feature + epsilon`.
In the `iml` package the issue is that an equidistant grid of a feature is computed (which also contains **double** values even if the original feature is an integer), see also https://github.com/christophM/iml/issues/138

**Comment by berndbischl** [comment]
Your example is less than ideal, as ist shows the underlying problem but not the concrete usecase?

**Comment by berndbischl** [comment]
I think I agree with GC. THis shouldn't be an an error?

**Comment by mllg** [comment]
AFAICT this is fixed. Added a unit test.
