### ISSUE TITLE
Is there any way to change objective for classif.xgboost in mlr3

### ISSUE THREAD

**Issue by raulfernandezn** [mlr-org/mlr3#535]
Hi all. I was using `mlr3` for extreme gradient boosting in `R` but I noticed that `objective` is set to `binary:logistic`.

Is there any way I could change to `multi:softprob`. I tried but the methods of `mlr3` does not allow `ParamUty`.

Many thanks for your help.

**Comment by berndbischl** [comment]
you dont have to do that? 
we autodetect the nr of classes from the task, then set it 
have a look at line 182 here
https://github.com/mlr-org/mlr3learners/blob/master/R/LearnerClassifXgboost.R

**Comment by berndbischl** [comment]
nevertheless, you can set the hyperpar "objective" to any value you want

```
ll = lrn("classif.xgboost")
ll$param_set$values$objective = "foo"
ll$train(tsk("iris"))
```

of course, with this setting of "foo", underlying xgb errors with

```
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [00:53:06] amalgamation/../src/objective/objective.cc:23: Unknown objective function foo
```
