### ISSUE TITLE
mlr3 learner train / predict timeout

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#542]
When using "callr" encapsulation for learners, `callr::r` is used so we should in be able to have a training / prediction timeout for that learner. This would be necessary to make mlr3automl (which @a-hanf is working on) more robust against timeouts / stalling `Learner`s.

**Comment by RaphaelS1** [comment]
I'm not sure if this is related or a separate issue, but a time-out feature could also help in situations such as #501 where benchmarking is crashing due to conflicting parallelisation methods

**Comment by mllg** [comment]
Timeout now supported in mlr3misc's `invoke()` and `encapsulate()`. I will implement it here once mlr3misc is on CRAN.

**Comment by RaphaelS1** [comment]
> Timeout now supported in mlr3misc's `invoke()` and `encapsulate()`. I will implement it here once mlr3misc is on CRAN.

Will this detect timeouts due to parallelisation? I know the logger doesn't handle this well which is why I'm checking

**Comment by jakob-r** [comment]
@mllg What's the current status?

**Comment by mllg** [comment]
It is possible to set `learner$timeout`. Not yet possible on the resample/benchmark level (#576).
