### ISSUE TITLE
mismatch of slot name in as.data.table(prediction) intentional?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#547]
`as.data.table(prediction)` has column `row_id`, but the slot in the `Prediction` / `PredictionData` object is `row_ids`, is that intentional? What is the naming rule here?

**Comment by RaphaelS1** [comment]
Very slightly off topic *but* I get very confused when to use `rows` and when to use `row_ids`. Picking one of the three and being consistent would make things much easier

**Comment by mllg** [comment]
The refactoring went wrong here. I agree that we should stick to row **or** row_id, but I'm unsure what would be a good rule for singular and plural.
