### ISSUE TITLE
mlr3 and install_github

### ISSUE THREAD

**Issue by nipnipj** [mlr-org/mlr3#560]
Am I the only one having issues when installing from github --- `devtools::install_github("mlr-org/mlr3")`?

```
Downloading GitHub repo mlr-org/mlr3@master

   checking for file 'C:\Users\CuysauruS\AppData\Local\Temp\RtmpyAiVgp\remotes148c32843848\mlr-org-mlr3-c10c6b0/DESCRIPTION' ...
  
   checking for file 'C:\Users\CuysauruS\AppData\Local\Temp\RtmpyAiVgp\remotes148c32843848\mlr-org-mlr3-c10c6b0/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\CuysauruS\AppData\Local\Temp\RtmpyAiVgp\remotes148c32843848\mlr-org-mlr3-c10c6b0/DESCRIPTION' (446ms)
  
-  preparing 'mlr3': (560ms)
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information

  -  installing the package to process help pages (713ms)
         -----------------------------------

    installing *source* package 'mlr3' ...
   ** using staged installation
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
     converting help for package 'mlr3'
       finding HTML links ... done
       BenchmarkResult                         html  
       DataBackend                             html  
       DataBackendDataTable                    html  
       finding level-2 HTML links ...
   Error: unknown input format
-  removing 'C:/Users/CUYSAU~1/AppData/Local/Temp/Rtmp4ChNve/Rinst1e347a9540ab/mlr3'
         -----------------------------------
   ERROR: package installation failed

Error: Failed to install 'mlr3' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>   converting help for package 'mlr3'
E>     finding HTML links ... done
E>     BenchmarkResult                         html  
E>     DataBackend                             html  
E>     DataBackendDataTable                    html  
E>     finding level-2 HTML links ...
E> Error: unknown input format
E> * removing 'C:/Users/CUYSAU~1/AppData/Local/Temp/Rtmp4ChNve/Rinst1e347a9540ab/mlr3'
E>       -----------------------------------
E> ERROR: package installation failed
```

I can install other packages trought `install_github` function, tho.

**Comment by mllg** [comment]
No problems on my side. https://github.com/rstudio/packrat/issues/379 popped up in google. Have you tried setting `options(pkgType = "source")` temporarily?

**Comment by nipnipj** [comment]
Oh. it is just me then. I'll try to solve this. Thanks for answering.

`options(pkgType = "source")` didn't work in my case.

**Comment by mllg** [comment]
Please report back if you have found a solution.

**Comment by nipnipj** [comment]
Is it possible to compile `mlr3` with microsoft visual studio?

**Comment by mllg** [comment]
Visual Studio is an IDE. This should be independent of the package installation. CCing @pat-s who is or has been as VS user.

**Comment by pat-s** [comment]
visual studio != visual studio code (which I use)

There, R just runs in the terminal and has no relation to the IDE.

Have not seen this error before but I guess some issues in the Rtools setup on Win. Try reinstalling Rtools and see if you can install other packages from source.

**Comment by nipnipj** [comment]
I meant something like [this](https://xgboost.readthedocs.io/en/latest/build.html#installing-the-development-version-with-visual-studio). Do you think something similar is possible with `mlr3`?

**Comment by pat-s** [comment]
What do you mean with "is possible"?

Not sure what visual studio does with Rtools. Try installing mlr3 using the R console in a terminal.

**Comment by nipnipj** [comment]
I do not have any issues installing mlr3 with `install.packages()` and using it after ´library(mlr3)´, if that what you're asking. I'm looking for an alternative way to install mlr3 from github, since trying to install it through `install_github()` doesn't work for me.

**Comment by pat-s** [comment]
> I do not have any issues installing mlr3 with install.packages() and using it after ´library(mlr3)´, if that what you're asking. 

`install.packages("mlr3")` installs a binary. `install.packages("mlr3", type = "source")` installs from source and errors in your case.

If you install from GH the package is compiled from source which requires compilation. For this, you need a working Rtools installation.

The error is thrown after trying to find some HTML links at the very end. I have never seen this so far.
On the side your username has a `~` in it which also could cause issues.

I can only again suggest to fix your toolchain/rtools. We are checking the package on Windows constantly and everything is fine.
