### ISSUE TITLE
MeasureOOBError  minimize not defined

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr3#562]
When I call msr("oob.error")  to define a measure for tuning a Random Forest model i get an error,
as minimize is NA as seen below:

<MeasureOOBError:oob_error>
* Packages: -
* Range: [-Inf, Inf]
* Minimize: NA
* Properties: na_score, requires_learner
* Predict type: response

But when i call with msr("oob.error", minimize = TRUE) it´s fine and for an error measure
it seems sensible to have minimize = TRUE as the standard.

**Comment by mllg** [comment]
You are right, this is fixed now in master.
