### ISSUE TITLE
Better document the use case of a model with weighted observations

### ISSUE THREAD

**Issue by harell** [mlr-org/mlr3#563]
Hi

Thank you for the great work on mlr3.

When I create a task and set one of the backend columns to serve as weights, the default configuration of `set_col_role` fails during new predictions. The solution is to set `exclusive = FALSE` in `set_col_role` public method (see snippet).

```
################################################################################
## mlr3 weighted observation
################################################################################
# Creating tasks and learners ---------------------------------------------
ml_task <-  mlr3::TaskRegr$new(id = "mtcars", backend = mtcars, target = "mpg")
ml_task$set_col_role(cols = "wt", new_roles = "weight", exclusive = FALSE)

# Training and predicting -------------------------------------------------
library(mlr3learners)
learner <- mlr3::mlr_learners$get("regr.lm")

learner$train(ml_task, row_ids = 01:30)
print(learner$model)

preds <- learner$predict(ml_task, row_ids = 31:32)
print(preds)

preds <- learner$predict_newdata(mtcars[31:32,])
print(preds)
```

I can suggest the following (these are not mutually exclusive suggestions):

## 1st Suggestion: Documentation

Using weight needs better documentation, especially telling users to set exclusive = FALSE;

## 2nd Suggestion: Default weights for unseen observations

In many cases there are not known weights for unseen observations. Passing new data without the weights is currently failing:

```
preds <- learner$predict_newdata(mtcars[31:32,] %>% dplyr::select(-wt))
```

Thus, in real usage, the user has to add a dummy weights column to make `predict_newdata` work. For example:

```
preds <- learner$predict_newdata(mtcars[31:32,] %>% dplyr::select(-wt) %>% tibble::add_column(wt = 1))
```

My suggestion is to add default weights of 1 to unseen observation somewhere in mlr3 methods.

---

Many thanks

**Comment by harell** [comment]
Given a model that was trained with observation weights (i.e. `ml_task$set_col_role(cols = "wt", new_roles = "weight")`
When I removed the role of the weight (i.e.`ml_task$set_col_role(ml_task$col_roles$weight, character(0))`) 
Then I can predict new data

Is that a feature or a bug? see code snippets for working and not working functions.

```
# Creating tasks and learners ---------------------------------------------
ml_task <-  mlr3::TaskRegr$new(id = "mtcars", backend = mtcars, target = "mpg")
ml_task$set_col_role(cols = "wt", new_roles = "weight")

# Training and predicting -------------------------------------------------
library(mlr3learners)
learner <- mlr3::mlr_learners$get("regr.lm")

learner$train(ml_task, row_ids = 01:30)
print(learner$model)

preds <- learner$predict(ml_task, row_ids = 31:32)
print(preds)

# DOESN'T WORK
# Error: Cannot rbind data to task 'mtcars', missing the following mandatory columns: wt
preds <- learner$predict_newdata(mtcars[31:32,], ml_task)

## WORKS
ml_task$set_col_role(ml_task$col_roles$weight, character(0))
preds <- learner$predict_newdata(mtcars[31:32,], ml_task)
preds <- learner$predict_newdata(mtcars[31:32,] %>% dplyr::select(-wt), ml_task)
```

**Comment by MislavSag** [comment]
I have these same problem. If I save the model, than load it and try to make new predictions like these:
```
model <- readRDS('myfile')
test_data_table <- data.table(0.7, 0.8, 0.7, 0.6, 1)
colnames(test_data_table) <- model$model$learner$state$train_task$feature_names
model$model$learner$predict_newdata(test_data_table)
```
I am getting an error:
```
Error: Cannot rbind data to task 'mlfinance', missing the following mandatory columns: weights
```
Why do I need a weight column for prediction? Don't we need weights only for training?
Second, if I add random weight to the `test_data_table` it doesn't work either.

**Comment by mllg** [comment]
> Using weight needs better documentation, especially telling users to set exclusive = FALSE;

Not sure where to put this; `set_col_roles` have also been refactored, so this should be less error-prone now.

> Thus, in real usage, the user has to add a dummy weights column to make `predict_newdata` work.

Done.
