### ISSUE TITLE
Compat with upcoming major update of lgr

### ISSUE THREAD

**Issue by s-fleck** [mlr-org/mlr3#565]
Dear mlr3 maintainers.

I am filing this issue because ml3 has a dependency on lgr. lgr will receive a major upgrade in the next weeks.

There are no breaking changes to the core features of lgr, but Appenders that are difficult to maintain or have heavy dependencies are moved to a separate package (lgrExtra). This notably includes database appenders and stuff like AppenderSyslog, AppenderSendmail and AppenderPusbullet. If you are using any of the more esoteric appenders of lgr, please let me know.

otherwise you can just close this issue,
thanks

**Comment by mllg** [comment]
AFAICT we never explicitly used them in one of our packages or in the book.

Thanks for the heads up nevertheless.

**Comment by s-fleck** [comment]
ok thanks!
