### ISSUE TITLE
Failing test due to bugfix in lgr 

### ISSUE THREAD

**Issue by s-fleck** [mlr-org/mlr3#566]
revdep check found an issue with the new lgr version `@test_lgr.R#10`. The naming when querying appenders in the old lgr version was broken:

```
  lg$inherited_appenders$appenders.console$set_threshold(th2) 
```
should actually be
```
lg$inherited_appenders$console$set_threshold(th2) 
```

The superfluous `appenders.` was never intended and can be considered a bug. Could you please update the test to something like:

```
if (packageVersion("lgr") >= "0.4.0"){
   lg$inherited_appenders$console$set_threshold(th2)   
} else {
  lg$inherited_appenders$appenders.console$set_threshold(th2) 
}
```

**Comment by mllg** [comment]
Fixed now, I'll upload a new version tomorrow.

**Comment by s-fleck** [comment]
Thanks for the quick response!
