### ISSUE TITLE
Test failures with upcoming version of R6

### ISSUE THREAD

**Issue by wch** [mlr-org/mlr3#568]
I'm planning on submitting a new version of R6 (2.5.0) to CRAN soon, and I'm getting failures from packages that depend on mlr3. I don't understand how the tests work for these packages so I can't say why they're happening, but here's some example output from mlr3proba when I run tests locally.

```
> test()
Loading mlr3proba
Testing mlr3proba
✔ |  OK F W S | Context
✖ |   5 2 1   | test_PredictionDens [0.2 s]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_PredictionDens.R:10: error: Internally constructed Prediction
could not find function ".__Task__row_roles"
Backtrace:

test_PredictionDens.R:16: error: c
could not find function ".__Task__feature_types"
Backtrace:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ | 192       | TaskDens [0.3 s]ens
✔ |  60       | TaskSurv
✔ |   5       | helpers
✖ |  13 2 1   | test_mlr_learners_density_hist [0.2 s]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_mlr_learners_density_hist.R:5: error: autotest
could not find function ".__Task__select"
Backtrace:
 1. global::run_autotest(learner, check_replicable = FALSE) tests/testthat/test_mlr_learners_density_hist.R:5:2
 3. global::generate_tasks.LearnerDens(learner, N = N) /Users/winston/R/4.0/mlr3/testthat/helper_autotest.R:97:2
 4. global::generate_generic_tasks(learner, task) inst/testthat/helper_autotest.R:6:2
 5. proto$clone()$select(sel) /Users/winston/R/4.0/mlr3/testthat/helper_autotest.R:22:6
```

Full error results here: https://gist.github.com/wch/e6326fe92b58d2a538c320ada877d66f

The errors started occurring after this PR in R6 was merged. It fixed a bug in cloning R6 objects:
  https://github.com/r-lib/R6/pull/215

Can you take a look? It's possible that the tests in the mlr3-related packages are relying on some old buggy behavior in R6. It's also possible I introduced a bug in R6, but as I mentioned earlier, I don't understand how the test system works in mlr3 so it's difficult to even know where to start looking.

**Comment by mllg** [comment]
Ok, I'll try to sum up what seems to be happening here:

We have the following in mlr3: Class `Task` with method `$print()` (and lots of other stuff, but we can ignore it). `Task$print()` calls a (non-exported) function from the mlr3 namespace: `mlr3:::.__Task_print__()`.

We have a second class in mlr3cluster: Class `TaskClust` which inherits from class `Task`. Method `Task$print()` is also inherited and not overloaded by `TaskClust`. The parent env of the print method is the package where the method was defined, i.e. `mlr3`:

```r
library(mlr3cluster)
task = TaskClust$new("usarrests", USArrests)

task$print
> function (...)
> .__Task__print(self = self, private = private, super = super,
>    ... = ...)
> <environment: 0x55cbe8759168>

parent.env(environment(task$print))
> <environment: namespace:mlr3>
```

After cloning `task`, the parent environment of `task$print` is not the namespace of `mlr3` anymore and thus the lookup of the internal function `.__Task_print__()` fails with the reported error.

```r
new_task = task$clone(deep = TRUE)
parent.env(environment(new_task$print))
> <environment: 0x55b2dc716908>
ls(parent.env(environment(new_task$print)))
> [1] "private" "self"    "super"
```

Let me know if you need more info.

**Comment by mb706** [comment]
If cloning objects that inherit from another package's class changes the namespace that an inherited method lives in, then this would be a newly introduced bug in R6 imho.

**Comment by wch** [comment]
Thanks for looking into it! It appears the issue was a bug in cloning objects with inherited methods, which I fixed in https://github.com/r-lib/R6/pull/218.
