### ISSUE TITLE
New method for deprecated `set_col_roles` less robust

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#571]
Using the deprecated `set_col_roles` correctly moves features so that they are not included in `feature_names` or `data()` however manually setting the `col_roles` field does not do this, which may lead to unintended consequences (e.g. weights being included in features) and requires more work from the user to prevent this. Would it be possible to edit the active binding for `col_roles` so the result is the same as `set_col_roles`?

``` r
library(mlr3)

task = TaskRegr$new("w", data.frame(x = 1:10, weights = 1:10, y = 1:10), target = "y")
task$set_col_role("weights", "weight")
task$feature_names
#> [1] "x"
task$data()
#>      y  x
#>  1:  1  1
#>  2:  2  2
#>  3:  3  3
#>  4:  4  4
#>  5:  5  5
#>  6:  6  6
#>  7:  7  7
#>  8:  8  8
#>  9:  9  9
#> 10: 10 10

task = TaskRegr$new("w", data.frame(x = 1:10, weights = 1:10, y = 1:10), target = "y")
task$col_roles$weight = "weights"
task$feature_names
#> [1] "weights" "x"
task$data()
#>      y weights  x
#>  1:  1       1  1
#>  2:  2       2  2
#>  3:  3       3  3
#>  4:  4       4  4
#>  5:  5       5  5
#>  6:  6       6  6
#>  7:  7       7  7
#>  8:  8       8  8
#>  9:  9       9  9
#> 10: 10      10 10
```

<sup>Created on 2020-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mllg** [comment]
Not sure if you discovered a bug or if this is just a coincidence, but I decided yesterday to not deprecate `set_col_role`/`set_row_role` but instead provide an extended version of them (https://github.com/mlr-org/mlr3/commit/80b8eed0e5e7a0d3c9747ccb867c229d8fec8dc0).

So you have two ways to modify the roles: via the setter or via a list-like active binding in `task$row_roles`/`task$col_roles`. I don't think that we should aim for a behavior which is differnt from a list, this would be confusing.

**Comment by RaphaelS1** [comment]
Oh cool that's just a coincidence.
But that still means users can incorrectly have duplicated features across `task$col_roles` right? Even if we don't automate the process it would be good to at least have a warning or something. Also I like the more flexible implementation but it still implies that users would need to know that, e.g. weights should be *moved* from feature to weights right?

**Comment by mllg** [comment]
I'm actually not sure about this. I had data sets where it made sense that the weights are also features (the performance measure used the sales price as weights, so you want to weight your products with the price and the price was also a helpful feature).

**Comment by mllg** [comment]
However, I get your point. We should probably switch to promoting the setter instead of the list.

**Comment by mllg** [comment]
I've improved the man pages and will start to update the book and gallery to promote the (more intuitive) setters.
