### ISSUE TITLE
Benchmark fails when untyped parameter value is a function with different class

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#581]
```r
l <- lrn("classif.debug")
l$param_set$add(ParamUty$new("z"))
l$param_set$values$z = identity
class(l$param_set$values$z) = "x"
benchmark(benchmark_grid(tsks("iris"), list(l), rsmps("holdout")))
```
gives error
```
Error in as.vector(x, "list") : 
  cannot coerce type 'closure' to vector of type 'list'
```

It is a bit far-fetched, but benchmark shouldn't fail for anything that is in a `ParamUty`, right?

**Comment by mllg** [comment]
Seems to be a data.table bug:

```r
f = function(x) x^2
class(f) = "foo"

dt = data.table(id = 1, funs = list(f))
dt[, list(funs), by = "id"]
```

**Comment by mllg** [comment]
Do you want to report this upstream?

**Comment by mb706** [comment]
Reported it: https://github.com/Rdatatable/data.table/issues/4814

**Comment by Coorsaa** [comment]
While this is fixed in https://github.com/Rdatatable/data.table/pull/4815,
a similar error occurs if the untyped param is an environment:
```
library(data.table)
library(keras)
f = optimizer_adam()

dt = data.table(id = 1, funs = list(f))
dt[, list(funs), by = "id"]
```
tested on data.table branch `runlock-function`, which solves this original issue here.

**Comment by Coorsaa** [comment]
made a comment in mb706's issue (https://github.com/Rdatatable/data.table/issues/4814)

**Comment by mb706** [comment]
is fixed in data.table and seems to work now in mlr3 as well.

**Comment by mllg** [comment]
Reopened to remind me to increase the required version in the description (currently waiting for CRAN's response for 0.10.0).
