### ISSUE TITLE
Error with resampling on iris dataset

### ISSUE THREAD

**Issue by timothyjgraham** [mlr-org/mlr3#588]
I run the following code from the help file:

```
task = tsk("iris")
learner = lrn("classif.rpart")
resampling = rsmp("cv")

# Explicitly instantiate the resampling for this task for reproduciblity
set.seed(123)
resampling$instantiate(task)

rr = resample(task, learner, resampling)
```

I get this error:
```
Error in UseMethod("value") : 
  no applicable method for 'value' applied to an object of class "list"
```

This error is also occurring for any other datasets I use. Any help much appreciated.

Tim

**Comment by berndbischl** [comment]
no, this works, i just tested with the latest CRAN version. 

this is not reproducible if you don't provide a sessionInfo. 

you likely either have non-cran versions of packages for mlr3 or are additionally creating problems in the namespace by loading something else (which we currently cannot see)

also note that what you are posting here is covered by our unit tests

**Comment by berndbischl** [comment]
PS: 
also a traceback would be useful

**Comment by timothyjgraham** [comment]
Thanks for the swift response and these suggestions. My apologies for the lack of correct information, but this is helpful - it turned out to be a namespace issue.

**Comment by berndbischl** [comment]
no prob, i have run into the same issue 1000 times
