### ISSUE TITLE
Enhance validation in Learners and Task

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#597]
Now I've looked at documentation in more detail. I'd like to suggest two minor enhancements for `validation` in `Task` and `Learner`:

1. There are many cases where a validation dataset may be required by a learner in order to make use of internal processes such as early stopping (e.g. GBMs, NNs). As validation is a common use-case, it may be worthwhile adding a simple public method to `Task` that creates arbitrary train/validation splits that can be passed to learner hyper-parameters, e.g.

```R
split_validation = function(prob) {
  self$row_roles$validation = sample(seq(self$nrow), self$nrow * prob)
}
```

Whilst this is clearly a thin wrapper around a basic function that could be performed by a user, it still requires user knowledge about `row_roles` and where to find validation splits (which aren't too well documented).

Alternatively if you don't agree this is worthwhile then I'd suggest adding an example to https://github.com/mlr-org/mlr3book/pull/201, e.g.

```R
> set.seed(1)
> t = tsk("mtcars")
> t$row_roles$validation = sample(seq(t$nrow), t$nrow * 0.3)
> t$row_roles$validation
[1] 25  4  7  1  2 23 11 14 18
```

2. Add 'validation' to learner and task properties (similar to 'weights'). Doing so would allow a more efficient method of implementing validation datasets in learners that can handle them, as currently we assume the user will pass in the validation data in the correct format, which is inconsistent with the general task interface, i.e. it is inconsistent for a user to pass `Task` for training data but a data object for validation data. This would also highlight to users when they can/cannot set the `validation` role.

EDIT: Fixed examples.

**Comment by sebffischer** [comment]
this is implemented
