### ISSUE TITLE
Provide task construction functions?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#598]
Task creation is probably the only step in a (usual) data analysis where the user needs to know details about R6. We could ease the first experience with mlr3 and provide functions for this, e.g. one of 

```r
new_task("classif", data = iris, target = "Species")
new_task_classif(data = iris, target = "Species")
```

Waiting for feedback from @berndbischl @mb706 @pfistfl @RaphaelS1 @be-marc @jakob-r

**Comment by RaphaelS1** [comment]
Would it be possible to overload `tsk` depending on number of arguments?
e.g.
`tsk("iris")` - Works as usual
`tsk("iris", data = iris, target = "Species")` - Construct new task with id iris

Optionally could check manually created tasks don't use pre-existing task names

**Comment by mllg** [comment]
I think this will get ambiguous as you already can pass down values for fields. Still possible to handle this, e.g. by querying if data is provided, but could also be quite confusing?

**Comment by RaphaelS1** [comment]
I think named arguments would be simpler, so `tsk = function(id, data, target, ...)` but I agree I see how this could be confusing to users

**Comment by jakob-r** [comment]
As we talk about sugar I think `tsk("iris", data = iris, target = "Species", type = "classif")` would be nicest, whereas `type` can be autodetected. If we can handle it internally - we should. The user just needs to know one function and there everything can be stated in the help.

**Comment by RaphaelS1** [comment]
@jakob-r how could type be autodetected? E.g. how to autodetect between TaskRegr and TaskDens?

**Comment by jakob-r** [comment]
First, we don't have to detect all types. Second, just use some simple heuristic and document(!) it. It does not have to be perfect. I don't care if somebody gets a wrong task type. She/he will notice once resampling does not work with the supplied learner. That's fine. Even if it goes unnoticed it would be ok for me. It's the users problem.

**Comment by RaphaelS1** [comment]
I don't know that doesn't seem fair to users given this is to make things as easy as possible for them

**Comment by jakob-r** [comment]
Well, you were the one who suggested the signature without giving the type ;) I don't actually care that much.

**Comment by RaphaelS1** [comment]
> Well, you were the one who suggested the signature without giving the type ;) I don't actually care that much.

Oh haha you're right! This was just a mistake from my side! I actually agree with your suggestion to include `type`. We could also have a 'guess if NULL' function, so `tsk = function(id, data, target, type = NULL ...)` and `type` is guessed (as either regr, classif, or surv (which is easy to guess)) if NULL. 

Actually this makes me realise it would actually have to be `tsk = function(id, data, type = NULL ...)` as `target` is not used for all task types (e.g. `TaskSurv` uses `time` and `event`)

**Comment by mllg** [comment]
I'm not really convinced about extending `tsk()` for this. Putting everything into the same function makes it pretty hard to document and understand, and the task constructor is one of the first function a user has to learn.

**Comment by mllg** [comment]
I've added `new_task_classif()` and `new_task_regr()` to mlr3. If anyone has objections, contact me before the next release ;)

**Comment by mllg** [comment]
Turns out that there already were some task construction functions: `as_task_classif()` and `as_task_regr()` with S3 methods for data.frames. I've removed the `new_task_*()` functions in favor of the converters.
