### ISSUE TITLE
Benchmark with tuning and holdout with splits

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3#599]
Hi,

I am new to mlr3 framework. Last 2 days I wast reading the book. 

I have 2 questions:

1. I understand how benchmark works and understand how tuning works, but I am not sure is it possible to combine those 2. That is is it possible to train benchmark models with different parameters. For example, if I want to train random forest and xgboost where parameters are generated on some random set, how can I do that (something like AutoTuner with benchmark)?

2. There is the `holdout` resample option and `CV` resample option. But most of the time we want to apply CV on train set and predict on the test. That is we want holdout and CV at the same time. Is it better to manually contract train and test as and than applying CV on it or is there some more mlr3'sh approach to this

**Comment by MislavSag** [comment]
I have just found that the answer on 2. is nested resampling (https://mlr3book.mlr-org.com/nested-resampling.html).

Actually, it seemsthat `AutoTuner` can handle both of the above. It can train multiple tasks with multiple learners on different search space. Great function!

**Comment by MislavSag** [comment]
Now I am not sure, can autotuner contain more than on learner? It should be only one learner.

**Comment by MislavSag** [comment]
Here is the code:
```
task = tsk('iris')
learner = lrn("classif.ranger")
resampling = rsmp('holdout')
measure = msr("classif.acc")
search_space = ParamSet$new(
  params = list(
    ParamInt$new("max.depth", lower = 2, upper = 6),
    ParamInt$new("min.node.size", lower = 3, upper = 6)
    
  ))
terminator = trm('evals', n_evals = 20)
tuner = tnr("grid_search", resolution = 1)
at = AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  search_space = search_space,
  terminator = terminator,
  tuner = tuner,
  store_models = TRUE
)

# banchmark
grid = benchmark_grid(
  task = task,
  learner = list(at, lrn("classif.nnet")),
  resampling = rsmp("cv", folds = 5)
)
bmr = benchmark(grid)
```

**Comment by mllg** [comment]
I'm not sure if I understand the question. The AutoTuner takes one (base) learner or pipeline and tunes it.
