### ISSUE TITLE
extract and model from banchmark

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3#601]
If I train several models through benchmark function like this:
```
# mlr outer resmaling, main measure, terminators, type of search
# same for all models!
resampling = rsmp('forecastHoldout', ratio = 0.7)
measure = msr("classif.auc")
terminator = trm('evals', n_evals = 20)
tuner = tnr("grid_search", resolution = 1)

# random forest
learner = lrn("classif.ranger", predict_type = "prob", predict_sets = c("train", "test"))
rf_params = ParamSet$new(
  params = list(
    ParamInt$new("max.depth", lower = 2, upper = 6),
    ParamInt$new("min.node.size", lower = 3, upper = 6)
    
  ))
rf_at = AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  search_space = rf_params,
  terminator = terminator,
  tuner = tuner,
  store_models = TRUE
)

# random forest with features selection
learner = lrn("classif.ranger", predict_type = "prob", predict_sets = c("train", "test"))
rf_fs <- AutoFSelector$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  terminator = terminator,
  fselector = fselector
)

# xgboost
learner = lrn("classif.xgboost", predict_type = "prob", predict_sets = c("train", "test"))
rf_params = ParamSet$new(
  params = list(
    ParamInt$new("max_depth", lower = 2, upper = 6),
    ParamDbl$new("colsample_bytree", lower = 0.1, upper = 0.7)
    
  ))
xgboost_at = AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  search_space = rf_params,
  terminator = terminator,
  tuner = tuner,
  store_models = TRUE
)

# learners used for benchmarking
featureless = lrn("classif.featureless", predict_type = "prob", predict_sets = c("train", "test"))

# set benchmark
grid = benchmark_grid(
  task = tsk('iris'),
  learner = list(rf_at, rf_fs, xgboost_at, featureless),
  resampling = rsmp("cv", folds = 5)
)
bmr = benchmark(grid)

# results by mean
bmr_results <- bmr$clone(deep = TRUE)
measures = list(
  msr("classif.acc", id = "acc_train", predict_sets = 'train'),
  msr("classif.acc", id = "acc_test", predict_sets = 'test'),
  msr("classif.auc", id = "auc_train", predict_sets = 'train'),
  msr("classif.auc", id = "auc_test", predict_sets = 'test')
  
)
bmr_results$aggregate(measures)
```
Now, I would like to extract best (or any other) model and save it using save function. There are lots of methods and field and I can't find the right way to extrct best model from `bmr_result object`.

I would lke to see important featues for that model too.

**Comment by mllg** [comment]
To retrieve the models:

```{r}
#' tasks = lapply(c("iris", "sonar"), tsk)
#' learners = lapply(c("classif.featureless", "classif.rpart"), lrn)
#' resamplings = rsmp("cv", folds = 3)
#'
#' design = benchmark_grid(tasks, learners, resamplings)
#' print(design)
#'
#' set.seed(123)
#' bmr = benchmark(design, store_models = TRUE)
#'
#' mlr3misc::map(as.data.table(bmr)$learner, "model")
```

Note that these are the models for individual resampling iterations. Although it is possible to determine the best learner w.r.t. its aggregated predictive performance, the aggregated performance is the result from multiple fitted models.

**Comment by MislavSag** [comment]
Thanks @mllg 

I get it. These are all models trained in benchmark mode where total models = number of models * number of CV folds  (if task is 1).

If I want to extract learner by `learner_id` and save best model of all tuned is something like this good approach:
```
measures = list(
  msr("classif.acc", id = "acc_train", predict_sets = 'train'),
  msr("classif.acc", id = "acc_test", predict_sets = 'test'),
  msr("classif.auc", id = "auc_train", predict_sets = 'train'),
  msr("classif.auc", id = "auc_test", predict_sets = 'test')
)
best_xgboost <- bmr$score(measures)[learner_id == 'classif.xgboost.tuned', ][acc_test == max(acc_test)]$learner[[1]]
```
And than if I want to save them model and use it in production, something like:
```
save(best_xgboost)
# later
load(best_xgboost)
best_xgboost$predict_newdata()
```

These are all deeply nested lists so I have to get used to all methods and fields :)

By the way, I have used sklearn before and skimmed tidymodels and find your package the best. 

The only addition I would like to see for now, except adding more learners, measures etc., is easy model deployment. Something like serving a TensorFlow model. Most times you want to move the model to production if it is good enough and make it available for every language...

**Comment by MislavSag** [comment]
One addition, when I recommend deploying the models, I was thinking something like two functions:
1. `save_model` which would create the folder (with hash as name) and inside it would save the model object and possible additional tables as db which, later, can be seen through GUI. Also plumber file would be great.
2. `deploy_model` function for deploying the model on the server (say Azure ot Digital ocean), which would include sending folder from 1 to the server like and make it available through API.

**Comment by MislavSag** [comment]
One more thing. I don't understand how can I predict with new data. When I load the model:
```
model <- readRDS(my_model)
```
and than try:
```
model$predict_newdata(newdata = test_data_table)
```
I get an error:
```
Error: No task stored, and no task provided
```
Why do I need task to make predictions on new data?

**Comment by MislavSag** [comment]
I figure out the last part, I have to extract learner from the the model which is extracted from the model! So, it is not:
```
model <- readRDS(my_model)
model$predict_newdata(newdata = test_data_table)
```
but:
```
model <- readRDS(my_model)
model$model$learner$predict_newdata(newdata = test_data_table)
```
but now I have problems because I used weights in training: https://github.com/mlr-org/mlr3/issues/563

**Comment by mllg** [comment]
The weight issue is fixed in the main branch, re-open if there are more problems.
