### ISSUE TITLE
task_rm_backend and all.equal  on r-devel

### ISSUE THREAD

**Issue by be-marc** [mlr-org/mlr3#602]
It works on r 4.0.3 but not on r-devel.

```r
library(mlr3)

task1 = tsk("iris")
task2 = tsk("iris")

all.equal(task1, task2)
# > [1] TRUE

task1 = mlr3:::task_rm_backend(task1)
task2 = mlr3:::task_rm_backend(task2)

all.equal(task1, task2)

# > Error: The backend of Task 'iris' has been removed. Set `store_backends` to `TRUE` during model fitting to conserve it.
```

**Comment by mllg** [comment]
Do you have an outdated version of r-devel? CRAN checks look fine. Or is this not covered in the tests?

**Comment by be-marc** [comment]
There is no unit test for this. I used one of the rocker docker images to test this. The unit test in my PR #554 fail on r-devel because this assertion does not work anymore

```r
assert_continuable_task = function(train_task, continue_task) {
  continue_task = task_rm_backend(continue_task$clone(deep = TRUE))
  train_task = task_rm_backend(train_task$clone(deep = TRUE))
  if(!isTRUE(all.equal(train_task, continue_task))) {
    stop("Supplied task does not allow to continue training.")
  }
}
```

**Comment by mllg** [comment]
This is the relevant part from the NEWS file: 

    > • all.equal(f, g) for functions now by default also compares their
    > environment(.)s, notably via new all.equal method for class
    > function.  Comparison of nls() fits, e.g., may now need
    > all.equal(m1, m2, check.environment=FALSE).

So `all.equal()` is right, the two objects are not the same because they are different environments?

**Comment by mllg** [comment]
Funnily, `check.environment` is introduced in the same version where the default has changed. So it's best to write a small wrapper function which only passes `check.environment` for R >= 4.1.0.

**Comment by be-marc** [comment]
We get the same error message with `check.environment=FALSE`. The error message is part of `assert_has_backend()`. Don't know why this is even called when using `all.equal(task1, task2)`.

**Comment by mllg** [comment]
I guess `all.equal()` walks through the elements of the environment and triggers some active binding.

**Comment by be-marc** [comment]
It works if we apply this [fix](https://github.com/mlr-org/mlr3pipelines/blob/157e8d36b28214b909fe38dcdba5c51826ad1e3f/tests/testthat/helper_functions.R#L493-L523) by @mb706 and add `check.environment = FALSE`.

**Comment by be-marc** [comment]
@mb706 told me we should not use his fix because the `R6` class does not belong to our package. He reported the issue [here](https://github.com/r-lib/R6/issues/208)

Simplified issue:

``` r
test = R6::R6Class("test", 
  active = list(
    error = function() {
      stop("Stop")
    }
  ))

t1 = test$new()
t2 = test$new()

all.equal(t1, t2)
# > Error in (function ()  : Stop
```

**Comment by mllg** [comment]
Can we, for now, just implement a helper `all_equal()` which has `check_environment` set to `FALSE` and then replace this helper with `all_equal = all.equal` in a future version?

**Comment by mllg** [comment]
@be-marc does the discussed solution work for you? can we close here?
