### ISSUE TITLE
More task mutators

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#61]
See https://github.com/mlr-org/mlr3pipelines/issues/19

* [x] `$remove_rows()`
* [x] `$remove_cols()`
* [ ] `$replace_backend()`

**Comment by mllg** [comment]
`remove_rows()` and `remove_cols()` is kind of already there: `$select()` and `$filter()`.

**Comment by mllg** [comment]
I believe that completely replacing the backend is never required. I cannot think of an operation which discards all data from the task. Even a PCA keeps at least the target column.

Therefore I think we are good here. To replace all features, you can do something like this:
```r
task$select(task$target_names)
task$cbind(newdata)
```
I'll frequently check the operations needed in mlr3pipelines and will add more mutators if required.

**Comment by pfistfl** [comment]
Can we reopen this? 
There is at least one case where this is required. 
sparsePCA transforms a MatrixBackend to a data.tableBackend.

**Comment by pfistfl** [comment]
Additionally some convenience funs w.r.t the primary keys would be nice.

**Comment by mllg** [comment]
> Can we reopen this?
> There is at least one case where this is required.
> sparsePCA transforms a MatrixBackend to a data.tableBackend.

We first need to agree how we deal with the different formats in general before we can proceed here. 

> Additionally some convenience funs w.r.t the primary keys would be nice.

Sure. Suggestions welcome.

**Comment by pfistfl** [comment]
Basically, what happens when I get the task from one Backend and need to create a new backend,
that has the same primary key. (E.g Matrix to DT, see "PipeOpSparsePCA$train()$ for more infos)

What I currently do: 
```
d = data.table(transformed_data)
# Add old primary key:
d[, task$backend$primary_key] = task$backend$data(paste0("row_", seq_len(nrow(d))), task$backend$primary_key)
 db = DataBackendDataTable$new(d, primary_key = task$backend$primary_key)
```

Solutions would be to either 
- construct backends from another backend that allows me to keep the primary key
- better getter for a task's primary keys

**Comment by pfistfl** [comment]
So basically, what we might want to work, but currently does not is
```task = mlr_tasks$get("iris")
d = task$data()
task$overwrite(d)
```
> Error: Cannot cbind task: Missing primary key column '..row_id'

**Comment by mllg** [comment]
Try this:
```r
task = mlr_tasks$get("iris")
d = task$data()
task$overwrite(cbind(task$row_ids, d)
```
Too complicated?

**Comment by berndbischl** [comment]
> Too complicated?

looks good?

**Comment by pfistfl** [comment]
I guess we can use this. Thanks

**Comment by pfistfl** [comment]
I was asking for this, because I think we will have to use this a lot.
A concise, short solution like this is definitely important.

**Comment by mllg** [comment]
Feel free to re-open if something is still missing.
