### ISSUE TITLE
Relax assertions on feature names: allow non-ascii

### ISSUE THREAD

**Issue by kweinert** [mlr-org/mlr3#610]
Hi, great project! 

I am learning your framework and try to do some text mining. The document-term-matrix serves as feature matrix. Some column names have special characters (like "é"). Would be nice if TaskClassif$new would accept these column names.

Currently it says:  Assertion on 'feature names' failed: Must have names according to R's variable naming conventions, but element 106 does not comply. (It seems the index is one off, it is column 105 which does not comply to the naming convention.)

Kind regards,
Karsten

**Comment by mllg** [comment]
I get your point, but you are opening a can of worms. Many learners rely on the formula interface or call `model.matrix` internally. Both are not guaranteed to work with utf8 chars.

I've introduced a temporary option to relax the assertions. If you set `options(mlr3.allow_utf8_names = TRUE)` you can try your luck.

**Comment by kweinert** [comment]
That's great. Thank you!
