### ISSUE TITLE
Task$uris is suboptimal

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#614]
I have gotten around to work with the new `uri` feature. 
This is really not optimal for multiple reasons. 

1. I might have several **uri** features:
  ```r
  library(mlr3)
  t = tsk("iris")
  t$set_col_roles(c("Sepal.Length", "Sepal.Width"),"uri")
  ```

  now `t$uris` fails with 
  > Error in setnames(data, c("row_id", "uri")) : 
    Can't assign 2 names to a 3 column data.table

2. URI's **are** features
  Printing the task does not show the existing URI's. I would expect them to be shown and treated as features.
  In contrast to `weights`, `strata` etc. URI's are actually features and should perhaps not be hidden away. 
  

3. We might want to work with **typed** uris: 
  Depending on the `type` of the URI, I might need to work with different e.g. Keras architectures. 
  If we ever want to automate anything, we will perhaps require types.

4. The current solution is a little intransparent, especially from a user's perspective. 
  After creating the task I need to set the feature(s) as URI, but then the feature is not shown anymore.
  I can for example not select/deselect **uri** in a `PipeOp` in a common way but would instead need to change 
  the row_roles. 

I am in favour of reverting to something like #592 
- We have a base datatype for a file on the system: `uri`
- We have specialized data types for e.g. `image`: `imageuri`
- Those are treated as features,  shown in the task print and can be selected/de-selected by pipeops.

**Comment by mllg** [comment]
Regarding (2) and (4):

`t$set_col_roles(cols, add_to = "uri")` should do what you are requesting?

**Comment by pfistfl** [comment]
Yeah, but then we wouldn't really need the **uri** (If I keep stuff as a feature anyway) ? 

What is the downside to treating things as features?

**Comment by mllg** [comment]
goes back to keras
