### ISSUE TITLE
Probability modelling with ranger failing on data with many classes

### ISSUE THREAD

**Issue by mcoghill** [mlr-org/mlr3#615]
I have a dataset with a large number of variables and classes for probability prediction, but some classes are not well represented. When I try to resample the data, I am getting an error that the prediction dataset must have exactly n columns, but it only has x columns. For example:

```
library(mlr3)
library(mlr3learners)
library(mlbench)

data("Soybean")
soy <- Soybean[complete.cases(Soybean), ]

# Adjust a class to have low representation
soy2 <- rbind(
  soy[soy$Class != "downy-mildew", ],
  soy[soy$Class == "downy-mildew", ][1, ]
)
tsk <- TaskClassif$new("soybean", backend = soy2, target = "Class")$droplevels()

lrn <- lrn("classif.ranger", predict_type = "prob", num.threads = 1)
rsp <- rsmp("repeated_cv", folds = 10, repeats = 5)
design <- benchmark_grid(tsk, lrn, rsp)
bmr <- benchmark(design, store_models = TRUE)
# INFO  [13:11:09.304] [mlr3]  Benchmark with 50 resampling iterations 
# INFO  [13:11:09.320] [mlr3]  Applying learner 'classif.ranger' on task 'soybean' (iter 29/50) 
# INFO  [13:11:09.508] [mlr3]  Applying learner 'classif.ranger' on task 'soybean' (iter 19/50) 
# Error in check_prediction_data.PredictionDataClassif(pdata) : 
#   Assertion on 'pdata$prob' failed: Must have exactly 15 cols, but has 14 cols.
# In addition: Warning message:
# Dropped unused factor level(s) in dependent variable: downy-mildew. 
```

I know that the last warning message is directly from the `ranger` package, which can be seen when running the following line:

```
rgr <- ranger::ranger(Class ~ ., data = soy, probability = TRUE, num.threads = 1)
# Warning message:
# Dropped unused factor level(s) in dependent variable: 2-4-d-injury, cyst-nematode, diaporthe-pod-&-stem-blight, herbicide-injury. 
```

Sometimes, it seems that the lines of code will run but other times it won't and I'm not sure how to fix that. I know that the problem is likely due to having low representation of one or more predicted classes, but is there a way to make it so that columns for all classes are produced in each resampling iteration, even when ranger drops unused classes?

Thank you for all of the hard work!

**Comment by mllg** [comment]
Thanks for the detailed report and analysis. I'm trying to fix this #619, but still need to figure out how to properly unit test this.

**Comment by mllg** [comment]
It should work now. Re-opening as a reminder to write some unit tests.

**Comment by mcoghill** [comment]
Awesome! Thank you so much. I know this is a bit of an edge case so I really appreciate the fix.
