### ISSUE TITLE
Why check whether there are missing values in the pdata? 

### ISSUE THREAD

**Issue by melonki** [mlr-org/mlr3#620]
Dear Contributors and Members,
I really appreciate your efforts in developing this great package. Recently I encountered an error message when using the prediction function on new data:

> Error in check_prediction_data.PredictionDataRegr(pdata) : 
  Assertion on 'pdata$response' failed: Contains missing values (element 48144).

This error seemed to be saying that there were missing values in the predictions (or "response"), which surpassed my understanding of the random forest model. So I checked the source code, there is such a function:

`check_prediction_data.PredictionDataRegr = function(pdata) { # nolint
  pdata$row_ids = assert_row_ids(pdata$row_ids)
  n = length(pdata$row_ids)

  assert_numeric(pdata$response, len = n, any.missing = FALSE, null.ok = TRUE)
  assert_numeric(pdata$se, len = n, lower = 0, any.missing = FALSE, null.ok = TRUE)

  if (!is.null(pdata$distr)) {
    assert_class(pdata$distr, "VectorDistribution")

    if (is.null(pdata$response)) {
      pdata$response = unname(pdata$distr$mean())
    }

    if (is.null(pdata$se)) {
      pdata$se = unname(pdata$distr$stdev())
    }
  }

  pdata
}`

[https://github.com/mlr-org/mlr3/blob/main/R/PredictionDataRegr.R](url)

So my question is why such a check function is needed, and under what circumstances will it produce missing values. I would greatly appreciate any explanation or suggestions in this matter.

With kind regards,
Melonki

**Comment by mllg** [comment]
If I understand you correctly, you are asking why we need this particular line:

```r
assert_numeric(pdata$response, len = n, any.missing = FALSE, null.ok = TRUE)
```

This check is not required for well behaving learners. But some learners predict NA values, e.g., if new factor levels are encountered in the test data. We simply try to catch this here to make sure that such predictions don't slip through accidentally which could lead to wrong performance scores.
Also, it is possible to create predictions manually, and giving a direct feedback in the form of an exception is usually a good thing.

**Comment by mllg** [comment]
Re-open if this blocks you in any way or if you have additional questions.
