### ISSUE TITLE
Target column 'target' must have at least two levels

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlr-org/mlr3#629]
Hallo! 

when I want to create a very basic classification task
dt <- data.table(a = c(1, 2, 3, 4), target = c(1, 1, 0, 1))
task <- TaskClassif$new(id='XX', backend = dt, target = 'target') 

I get the error:
#Error: Target column 'target' must have at least two levels
After searching one hour I found out that target must be a factor. I dont feel like this is very convenient, but maybe there is a reason to this behaviour!

Just a remark. 

Dankeschön!

**Comment by mllg** [comment]
The error message is improved in #632. We will not auto-convert the input to factors though, this should be taken care of by the user prior to creating the task.
