### ISSUE TITLE
Benchmark result order of learners

### ISSUE THREAD

**Issue by MarcelMiche** [mlr-org/mlr3#635]
# Question: What am I getting wrong here:
# According to bmr$score, I can see that the order of the learners is congruent with the order the learners are passed to benchmark_grid, that is, logreg, glmnet (lasso), randomForest, xgBoost. I assumed that the sequence in bmr$score is the same as in bmr$data$predictions, which is why I am confused why my manual calculation, using the for loop on bmr$data$predictions, returns the correct results (for recall and precision) in a different order than the mlr3-function aggregate, see resulting tables A and B.
# Furthermore, when I re-run the code, the incongruence of rows in table A and B is always there, but the pattern of incongruence is not always the same. I re-ran it four times.

# A
# mlr3 aggregate -----------------------------------
# --------------------------------------------------
#         learner_id recall_test precision_test prauc_test
# 1: classif.log_reg   0.5516278      0.7106599  0.7043386
# 2:  classif.glmnet   0.5435772      0.7156917  0.7109030
# 3:  classif.ranger   0.5885680      0.6950425  0.7292258
# 4: classif.xgboost   0.6063638      0.5980462  0.6501185
# --------------------------------------------------

# B
# Manual computation -------------------------------
# --------------------------------------------------
# modFac recalllMn precisionMn   praucMn
# <fct>      <dbl>       <dbl>     <dbl>
# 1 logreg 0.5885680   0.6950425 0.7290484
# 2 lasso  0.5516278   0.7106599 0.7037593
# 3 rf     0.5435772   0.7156917 0.7102854
# 4 xg     0.6063638   0.5980462 0.6656686
# --------------------------------------------------

library(mlr3verse)
library(dplyr)
library(yardstick)  # for function pr_auc

options(pillar.sigfig = 7)

# pima data.frame for binary outcome classification.
pimaDf0 <- as.data.frame(tsk("pima")$data())
# In this(!) script, use only rows without missing values.
idxNoNA <- apply(pimaDf0, 1, function(x) {all(!is.na(x))})
# pimaDf: dataset pima with complete observations.
pimaDf <- pimaDf0[idxNoNA,]
# class distribution of outcome
prop.table(table(pimaDf$diabetes))

# Set up task for this demo:
task <- TaskClassif$new("PimaCompleteObs", backend = pimaDf, target="diabetes", positive="pos")

# Benchmark design; learners: logreg, lasso, randomForest, xgBoost
design = benchmark_grid(
    tasks = task,
    learners = list(
        lrn("classif.log_reg", predict_type = "prob"),
        lrn("classif.glmnet", alpha=1, predict_type = "prob"),
        lrn("classif.ranger", predict_type = "prob"),
        lrn("classif.xgboost", predict_type = "prob")),
    resamplings = rsmp("repeated_cv", folds = 3, repeats=2)
)
measures = list(
    msr("classif.recall", id = "recall_test"),
    msr("classif.precision", id = "precision_test"),
    msr("classif.prauc", id = "prauc_test")
)
bmr <- benchmark(design, store_models = TRUE)

bmr$score()[,c("nr", "task_id", "learner_id", "iteration")]

bmr$data$predictions()

# Manually compute recall, precision, pr_auc, and F1Score
recl <- prec <- prauc <- F1scores <- c()
for(i in 1:length(bmr$data$predictions())) {
    # Confusion matrix
    confTemp <- bmr$data$predictions()[[i]]$confusion
    # Recall (Sensitivity, TPR)
    recallTemp <- confTemp[1,1]/sum(confTemp[1:2,1])
    recl <- c(recl, recallTemp)
    # Precision (PPV)
    precisionTemp <- confTemp[1,1]/sum(confTemp[1,1:2])
    prec <- c(prec, precisionTemp)
    F1scores <- c(F1scores, (2*precisionTemp*recallTemp)/(precisionTemp+recallTemp))
    # Area under precision-recall curve: pr_auc (pkg yardstick)
    praucTemp <- pr_auc(data.frame(as.data.table(bmr$data$predictions()[[i]])), truth, prob.pos)
    prauc <- c(prauc, praucTemp[[".estimate"]])
}

# Set numResample, which depends on applied resampling specification in benchmark_grid (here: "repeated_cv", folds = 3, repeats=2):
numResample <- length(bmr$data$predictions())/4
modName=rep(c("logreg", "lasso", "rf", "xg"), each=numResample)
modFac <- factor(modName, levels=c("logreg", "lasso", "rf", "xg"))
checkManual <- tibble(modFac, recall=recl, precision=prec, F1scores, prauc)

# mlr3 aggregate function:
bmr$aggregate(measures)[,c("learner_id", "recall_test", "precision_test", "prauc_test")]

# Manual computation of mean performance:
checkManual %>% group_by(modFac) %>% summarise(recalllMn = mean(recall), precisionMn = mean(precision), praucMn = mean(prauc))

**Comment by mllg** [comment]
There is no implicit order of the results in a BenchmarkResult. If you just called `benchmark()` on a grid, you can probably assume that the order remains unchanged. However, if you construct your BMR out of multiple resample results, things get more complicated. 

Internally, we store the data in multiple relational tables to avoid duplication of certain objects. Note that `BenchmarkResult$data` is an **internal** field. The predictions are sorted by a hash value, and this is why you get a different order here. If you want to access the individual predictions, use `bmr$score()$prediction`,`as.data.table(bmr)$prediction`, or extract them from the resample results in `bmr$resample_results`/`bmr$aggregate()$resample_result`. These have the same order as in `score()` or `aggregate()`.
