### ISSUE TITLE
Change objective function and combo terminator

### ISSUE THREAD

**Issue by phisanti** [mlr-org/mlr3#637]
Rather than a bug, this is more a learning question. I have been using for few weeks and there are few things that I would like to learn.

First, I am training an `xgboost `model, but I got all the time this error message:
`[19:58:53] WARNING: amalgamation/../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.`

I suspect it is a normal warning because it also appears in the MLR3 support book. However, I would like to know how could I explicitly use `"logloss"` so that the error is gone.

 Second, I would like to build a combo terminator with two parameters, a total of 10 training rounds OR end if classif.acc is ~0.9. I saw the example with the clock but no idea of how to add a the parameter.
 
Thanks for your help in advance.

**Comment by be-marc** [comment]
> However, I would like to know how could I explicitly use "logloss" so that the error is gone.

```r 
lrn("classif.xgboost", eval_metric = "logloss")
```

> Second, I would like to build a combo terminator with two parameters, a total of 10 training rounds OR end if classif.acc is ~0.9

```r
trm("combo", terminators = list(
  trm("evals", n_evals = 10),
  trm("perf_reached", level = 0.9)))
```

Or do you mean boosting rounds?

**Comment by phisanti** [comment]
That's it! Thank you!
