### ISSUE TITLE
Get more than one metric

### ISSUE THREAD

**Issue by phisanti** [mlr-org/mlr3#638]
I was wondering if it is possible to configure a tuning instance for one target metric but calculating at the same time other metrics. Something like using `"classif.ce"` but reporting `"sensitivity"` and `"specificity"`.

**Comment by be-marc** [comment]
```r
instance$archive$benchmark_result$aggregate(msr("classif.sensitivity"))
```

See https://mlr3book.mlr-org.com/tuning.html
