### ISSUE TITLE
Make benchmark_grid() robust to errors?

### ISSUE THREAD

**Issue by lindeloev** [mlr-org/mlr3#639]
I've made a function that runs `benchmark_grid()` on all learners that match the features of a particular task. This is useful to get a first indication, what type of models are fit for this problem.

However, quite often several learners fail, e.g., because of missing factor levels when using CV resampling. This breaks the whole benchmark and nothing is returned. Would it make sense to add an argument `benchmark_grid(error_action = "skip")` that wraps the resampling in a `try` block? Of course, it would default to the current behavior: `error_action = "stop"` for backwards compatibility.

**Comment by mllg** [comment]
This is already possible through enabling encapsulation for the learners: https://mlr3book.mlr-org.com/error-handling.html

I have to admit that the interface still feels a bit clunky if you want to set up error handling for multiple learners at once. Automatically setting this during `resample()`/`benchmark()` or `benchmark_grid()` seems like a good addition.

**Comment by lindeloev** [comment]
Wow, nice, @mllg! Looking forward to trying this out.
