### ISSUE TITLE
Error: Assertion on 'feature names' failed:  Must have names according to R's variable naming conventions 

### ISSUE THREAD

**Issue by vikram-rawat** [mlr-org/mlr3#646]
Hi,

I am trying to convert one of the NLP model I wrote in quanteda to mlr3 framework. First of all it's very hard to port a dfm or a sparse matrix directly into a task... This is the code that I am using after creating a dfm or a sparseMatrix and a datatable.

```
topics_bck <- as_data_backend(
  data = topic_dfm,
  dense = main_dt,
  primary_key = "doc_id"
)

topics_tsk <- TaskClassif$new(
  id = "topics",
  backend = topics_bck,
  target = "topics"
)

```
I get this error...

```
Error in .__Task__initialize(self = self, private = private, super = super,  : 
  Assertion on 'feature names' failed: Must have names according to R's variable naming conventions, but element 19 does not comply.

```
while all the columns are according to R's naming conventions but in UTF-8 as I am working with german text.

```
topics_bck$colnames[
  !topics_bck$colnames == make.names(
    topics_bck$colnames,
    unique = TRUE
    )
]

## character(0)
```

While the error on column 19 is nothing but a normal string But a UTF-8 one.

```
topics_bck$colnames[19]
[1] "gegen"

```
Just to be double sure even the base matrix column are compatible with base R
```
> colnames(topic_dfm)[
+   ! colnames(topic_dfm) == make.names(
+     colnames(topic_dfm),
+     unique = TRUE
+   )
+ ]

## character(0)
```
Is there an easier way to create a task directly from Matrix...
I found this answer online: https://stackoverflow.com/questions/65669017/how-to-change-column-names-to-comply-to-mlr3s-naming-convention

But it doesn't seem to be a perfect solution, So Please allow german and other UTF-8 text to be directly applicable in the Tasks.

**Comment by mllg** [comment]
> while all the columns are according to R's naming conventions but in UTF-8 as I am working with german text.

Having the column names encoded in UTF8 is no problem, but I guess you are having some German umlauts in there which, to the best of my knowledge, do not comply to the naming convention. From `?make.names()`:
> A syntactically valid name consists of letters, numbers and the dot or underline characters and starts with a letter or the dot not followed by a number. Names such as ".2way" are not valid, and neither are the reserved words. 

Not sure what the problem with your column names is. If you can provide the data I can have a closer look. You can disable the name check if you want though: I have added an answer to the stackoverflow question.

**Comment by vikram-rawat** [comment]
Thanks a lot for this option... I really appreciate your response... Just a comment: data backend for matrix is not easy to work with... So many errors and so less documentation... 

Thank you very much for this wonderful framework 😍😍
