### ISSUE TITLE
Prominently mention mlr3extralearners

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#649]
- mlr3extralearners is IMHO not really linked in the README
-  We should perhaps also link to the  [learner overview](https://mlr3extralearners.mlr-org.com/articles/learners/list_learners.html)
   (next to the cheatsheets?)

**Comment by RaphaelS1** [comment]
Agreed, I've had this on the core agenda for ages.

**Comment by berndbischl** [comment]
why dont we simply do this? why do we need a core agenda point?

**Comment by berndbischl** [comment]
just do it?

**Comment by RaphaelS1** [comment]
I think it was an agenda point because it turned into a long discussion about how best to style the mlr3 homepage with many opinions

**Comment by berndbischl** [comment]
öhm, i dont remember this exactly? i mean nobody can be reasonably against linking to the 2 points in your OP?

**Comment by RaphaelS1** [comment]
Happy with this @berndbischl  @pfistfl  https://github.com/mlr-org/mlr3/pull/650 ?

**Comment by berndbischl** [comment]
will merge it in, really (!!!) stupid not top have had this before.....

**Comment by berndbischl** [comment]
done
