### ISSUE TITLE
Support for custom, factor-based resampling

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#651]
As discussed in Mattermost.

Something along the lines of

```
rsmp("custom", split = <factor>)
```

where `<factor>` is a factor vector or a variable name from the task.

**Comment by mllg** [comment]
Will https://github.com/mlr-org/mlr3/blob/main/R/ResamplingCustomCV.R suffice?

**Comment by mllg** [comment]
Solved via #654.
