### ISSUE TITLE
Support `base_learner()` 

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#653]
- [x] Add method in mlr3tuning for AutoTuner
- [ ] Add method in mlr3pipelines for GraphLearner
- [x] Add method in mlr3fselect for AutoFSelector
- [x] Update the filter in mlr3filters to call base_learner()

**Comment by berndbischl** [comment]
can we pls list here more usecases, so one can better check how this would look like

**Comment by sebffischer** [comment]
this is implemented for `GraphLearner`
