### ISSUE TITLE
predicting with test data gives error.

### ISSUE THREAD

**Issue by Nehagupta90** [mlr-org/mlr3#656]
Hello everyone

I divided the data in train/test, then train the model with train portion and when I predict with test set, it gives error.
Error in UseMethod("as_task") : 
  no applicable method for 'as_task' applied to an object of class "data.frame"

What is the problem? 

data = readARFF("bug.arff")

index= sample(1:nrow(data), 0.7*nrow(data))
train= data[index,]
test= data[-index,]

task = TaskClassif$new("data", backend = train, target = "bug")

learner= lrn("classif.randomForest", predict_type = "prob")

model= learner$train(task)
learner$predict(test )

**Comment by mllg** [comment]
To predict on new data given as a `data.frame`, use the `predict_newdata()` method instead of `predict()`. The error message was not very good for this case, I've tried to improve it.
