### ISSUE TITLE
Do we need to always use a resampling/validation method?

### ISSUE THREAD

**Issue by Nehagupta90** [mlr-org/mlr3#657]
Hi, if I split the data in train/test sets and then directly train the model on train data and predict on test data (i.e. do not use ant cross validation methods), do any validation methods are applied by default? 

I mean what happens if we do not use any resampling/validation method?

Warm regards

**Comment by larskotthoff** [comment]
Not sure what you mean -- a train/test split is a resampling method, so if you're applying that it's easier than manually splitting, training, and testing.

If you're asking about whether you always need a resampling method of some kind, the short answer is yes.

**Comment by larskotthoff** [comment]
Can you point us to some of those examples please? Unless you use a resampling, mlr3 doesn't automatically split the data.

**Comment by berndbischl** [comment]
Can you please make the question more precise? I have a super-hard time understanding what you would like to find out. A concrete example usually helps....

Also this really is more a user question than a  bug report, so it would be better to ask this on stackoverflow than in the tracker. But if you can make it concrete we can briefly keep this open to see if we can help

**Comment by berndbischl** [comment]
> In mlr3, I have seen a lot of examples where the authors didn't use any validation method. In fact, in majority of the examples, they even didn't divide the data into train and test.. 

What examples, where? How about a link?

> They train and predict on same data but I assumed that if we train on the same data, mlr3 (automatically in the background) will make sure that the model is not predicted on the same data on which it is trained.

mlr3 usually does what you tell the package to do ;-) It train, predicts and resamples as you request in your code...

**Comment by berndbischl** [comment]
> Can you point us to some of those examples please? Unless you use a resampling, mlr3 doesn't automatically split the data.

For completeness sake (more for you than the OP, Lars):
Don't forget that "row_roles" in "Task" exists. That does influence data handling / usage....

**Comment by Nehagupta90** [comment]
Hi Bischl, thanks for your comments.

I mean in the mlr3 book (https://mlr3book.mlr-org.com/train-predict.html)
and in the mlr3 gallery (
https://mlr3gallery.mlr-org.com/posts/2020-03-18-iris-mlr3-basics/), the
authors did not use any resampling methods like holdout, cv etc..  Divide
the data, train it and test it, no ramp() used.

My two questions are:

(1) Is it optional to use these resampling methods like we do here (
https://mlr3book.mlr-org.com/resampling.html)

(2) I read some examples where the data is divided into 80:20 ratio (like
here https://mlr3book.mlr-org.com/train-predict.html) and some examples
which dynamically divide data in the train() and predict () like here (
https://mlr3gallery.mlr-org.com/posts/2020-03-18-iris-mlr3-basics/)...
Which of the methods is a preferred method while dividing our data?
Moreover, sometime we use this method for prediction  preds = learner1$
predict(task, row_ids = 121:150)

and sometime we use preds = learner1$predict_newdata(newdata = iris[121:150,
])

Both these are correct and recommended ways for prediction?

Warm regards

**Comment by larskotthoff** [comment]
The mlr3 book chapter you link to is on how to train and predict, that's why there's no resampling in it -- there are later chapters on resampling though. The mlr3 gallery post you link to does talk about resampling.

In general, the resampling methods are provided so you don't have to do a (repeated) splitting into training and test yourself -- it's a single line of code rather than a few dozen (and of course it's easier to get the resampling right this way). Technically, they are certainly optional, but unless you need to do a very specific evaluation, you probably want to use the provided methods.

I would recommend a 10-fold cross-validation for evaluation. The two ways you give for predicting data are equivalent; you can use either (depending on how you set up the task to train on).

**Comment by Nehagupta90** [comment]
Thank you again

So for a reliable evaluation, it is recommended to use the resampling
method (and the preferred way is to use 10-fold CV) ?

Technically, they are certainly optional, but unless you need to do a very
specific evaluation, you probably want to use the provided methods.

Since I am very beginner to the mlr3, and I am not sure when to use the
resampling method ans when not to use, do you recommend for me (as a
beginner) to use the resampling method in every scenario i.e. in simple as
well as large problems ?

Warm regards

**Comment by larskotthoff** [comment]
Yes, you should always use the resampling methods.

**Comment by berndbischl** [comment]
Please, these questions are very orthogonal to mlr3 as a software and concern ML evaluation in general.

They cannot be answered in generality and without context.

And they clearly show that you should invest some time into theory and concepts. Take a proper course, do a lecture, read a book or tutorial paper on the topic.

I cannot highly recommend this enough. Evaluation in ml and data science is non trivial. If you don't do this you will run into ugly problems later

**Comment by Nehagupta90** [comment]
Thanks you Lars and Bernd, I got your points..

Take a proper course, do a lecture, read a book or tutorial paper on the
topic.

I am doing that as time passes but sometimes I am forced to perform the
code by my tutor and  I have to ask questions in this forum, which is the
only mlr3 forum I found active (I did not find stackoverflow that much
active).

Thanks again and warm regards

**Comment by berndbischl** [comment]
if shameless selfplugging is allowed:
my intro lecture on ML is also on github and free.

https://introduction-to-machine-learning.netlify.app/

and deals with eval too. if you are a little bit "lazy" and wait for about 3 weeks: 
we are currently improving exactly that section even more.

**Comment by Nehagupta90** [comment]
Thanks for your link, I am certainly interested in it.. One thing another,
plz include something about deep learning in mlr3..

Warm regards
