### ISSUE TITLE
Could not find function ".__LearnerClassifC50__.predict"

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3#659]
Hi,

I am not sure if this is rgiht place to post issue, but you can move to another mlr3 package if necessary.

I have trained and saved set of models using benchmark. I saved the results to R object.

Then I have loaded the saved results, extract the model I wnat to use and tried to makepredictions, but I got an error:

```
Error in .__LearnerClassifC50__.predict(self = self, private = private,  : 
  could not find function ".__LearnerClassifC50__.predict"
```
Here is the code I used to predict from saved models:
```
bmr_results <- readRDS("MYPATH")
measures = list(
  msr("classif.acc", id = "acc_train", predict_sets = 'train'),
  msr("classif.acc", id = "acc_test", predict_sets = 'test')
)
classif_C50_tuned <- bmr_results$score(measures)[learner_id == "classif.C50.tuned", ][acc_test == max(acc_test)]$learner[[1]]
classif_C50_tuned$state$model$learner$state$train_task$feature_names
feature_names <- model$model$learner$state$train_task$feature_names

# test data for prediciton
predict_data <- A[, ..feature_names]
predict_data <- na.omit(predict_data)
task <- Task$new(predict_data, id = "test", task_type = "classif")
classif_C50_tuned$learner$predict_newdata(newdata = predict_data) # one try
classif_C50_tuned$model$learner$predict(task)                     # second try
```
UDATE:
If I extract model raw object ()C50 object:
```
x <- classif_C50_tuned$model$learner$model
```
and if I than apply prdict fucntion, it returns predictions as expected:
```
predict(x, as.data.frame(predict_data))
[1] -1 -1 1  1  0  0  -1 -1 -1
Levels: -1 0 1
```

**Comment by MislavSag** [comment]
I have found the error. I have to choose learner from list of learners. I will close the issue.

**Comment by mllg** [comment]
> I have found the error. I have to choose learner from list of learners. I will close the issue.

Can you elaborate?
