### ISSUE TITLE
format arg for task$data()

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#66]
`task$data()`currently only returns `data.table`'s.
In cases where the backend is a sparse matrix, we would like to supply a `format = sparse` arg, so the data is returned in sparse-matrix format.

```
  requireNamespace("Matrix")
  data = Matrix::Matrix(sample(0:1, 30, replace = TRUE), ncol = 3, sparse = TRUE)
  colnames(data) = c("x1", "x2", "target")
  rownames(data) = paste0("row_", 1:10)
  b = as_data_backend(data)
  task = TaskRegr$new(id = "spmat", b, target = "target")
```

Instead of:
```
 
  d = task$data()
  task$backend$data(paste0("row_", seq_len(nrow(d))), colnames(d), format = "sparse")
```

i would like to do:

```
task$data(format = "sparse")
``` 

I can try to create a PR, if required.

**Comment by mllg** [comment]
That should be easy, I think I just need to pass down the argument. Will implement this tomorrow.

**Comment by krltrl** [comment]
> I just noticed that the sparse backend is still lacking some important features. Currently, we cannot store categorical features in it naturally (we could store integers and translate, but that is pretty ugly?). I will come up with a solution where we can at least store the classification target column it the backend.
> Would be best if you don't invest too much time into the sparse stuff now.

Hi @mllg, is there any progress on using sparse matrices in mlr3? I wanted to use a large dgCMatrix for text classification and ran into exactly the same problem: the otherwise logical target column has to be stored as integers in this format and therefore cannot be used for classification tasks.

**Comment by mllg** [comment]
The backend now supports mixing sparse and dense parts, but the task and learners are not ready yet.

```r 
library(Matrix)
library(mlr3)

# sparse part
m = Matrix(c(0, 0, 2:0), 3, 5)
colnames(m) = letters[1:5]

# dense part
dense = data.frame(
  target = factor(c("a", "b", "b")),
  row_id = 1:3
)


# construct backend
b = DataBackendMatrix$new(m, dense, primary_key = "row_id")

b$data(rows = 1:3, cols = "a", data_format = "Matrix")
b$data(rows = 1:3, cols = "a", data_format = "data.table")

# use backend in TaskClassif
task = TaskClassif$new("sparse_demo", b, target = "target")
print(task)
```

Some operations are undefined here. E.g., do we want to represent factors as dummy encoding or encoded as integers? Do we need to treat the target column differently -- probably yes?

I can put this topic on the agenda for the next mlr3 core meeting.

**Comment by krltrl** [comment]
That would be awesome. Thanks!

Another essential feature for text classification or any NLP task would be
to include text-preprocessing in PipeOps like tokenization, stemming,
lemmatization, stopword-filtering etc. But that's maybe another topic.

Michel Lang <notifications@github.com> schrieb am So., 24. Jan. 2021, 22:08:
