### ISSUE TITLE
What is the recommended way to store Benchmark Containers?

### ISSUE THREAD

**Issue by hrvg** [mlr-org/mlr3#664]
Hi,

I am trying to figure out if there is a recommended way to store the [Container for Benchmarking Results](https://mlr3.mlr-org.com/reference/BenchmarkResult.html).

My use case is the following:

1. train a model on a local machine with `bmr = benchmark(...)`.
2. save the Benchmarking Results with `saveRDS(bmr, "data/bmr.Rds")`.
3. create a `docker` container that contains and reads `data/bmr.Rds` and serve a `shiny` dashboard of the results.

If I read the `Rds` on my machine, I get the expected:

```
> readRDS("data/bmr.Rds")
<BenchmarkResult> of 90 rows with 3 resampling runs
 nr task_id         learner_id resampling_id iters warnings errors
  1 test   regr.featureless   repeated_cv    30        0      0
  2 test  regr.ranger.tuned   repeated_cv    30        0      0
  3 test regr.xgboost.tuned   repeated_cv    30        0      0
```

If I read the `Rds` on the `docker` container (from the command line), it throws the following error:

```
readRDS("data/bmr.Rds")
Error in .__BenchmarkResult__data(self = self, private = private, super = super,  : 
  could not find function ".__BenchmarkResult__data"
```
Here is the `sessionInfo()` from the container:

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] lgr_0.4.2            paradox_0.7.1        mlr3misc_0.9.2      
 [4] palmerpenguins_0.1.0 crayon_1.4.1         parallelly_1.26.1   
 [7] R6_2.5.0             mlr3measures_0.3.1   backports_1.2.1     
[10] mlr3learners_0.4.5   uuid_0.1-4           data.table_1.14.0   
[13] rstudioapi_0.13      bbotk_0.3.2          checkmate_2.0.0     
[16] mlr3_0.11.0          tools_4.1.0          parallel_4.1.0      
[19] compiler_4.1.0       mlr3tuning_0.8.0  
```

and the `traceback()`:

```
> traceback()
7: (function (rhs) 
   .__BenchmarkResult__data(self = self, private = private, super = super, 
       rhs = rhs))()
6: .__BenchmarkResult__aggregate(self = self, private = private, 
       super = super, measures = measures, ids = ids, uhashes = uhashes, 
       params = params, conditions = conditions)
5: self$aggregate(measures = list(), conditions = TRUE)
4: .__BenchmarkResult__print(self = self, private = private, super = super)
3: .subset2(x, "print")(...)
2: print.R6(x)
1: (function (x, ...) 
   UseMethod("print"))(x)

```

I am aware that there are some issues with serialization of R6 objects as detailed in #482 (and also maybe in [#36](https://github.com/mlr-org/mlr3keras/issues/36)). Hopefully, I am missing something dumb, but I expect that this might a common issue to distribute or deploy artifacts from `mlr3`.

I thought that a possible work-around was to save the `BenchmarkResult` to a `data.table::data.table` with `mlr3::as.data.table()` but `mlr3::as_benchmark_result()` does not convert back from `data.table` to `BenchmarkResults` which prevents this solution (and the use of the R6 methods).

**Comment by be-marc** [comment]
Hey, are you using mlr3 0.11.0 also on your local machine? I usually get these errors when loading an object created with an old mlr3 version.

**Comment by hrvg** [comment]
I thought about it when reading one of the issues here but:

local machine:
```
> packageVersion("mlr3")
[1] ‘0.11.0.9000’
```

docker container:
```
> packageVersion("mlr3")
[1] ‘0.11.0
```

**Comment by be-marc** [comment]
`.9000` indicates that you are using the development version on your local machine and the stable version in the docker container.

**Comment by hrvg** [comment]
I am closing this issue as downgrading to `0.11.0` on the local machine, re-training and re-building the `docker` container worked. 

However, I did not expect this upgrade to the development version with the same minor version to break like this. It might make the reproducibility and re-usability of `mlr3` code limited if it is _that_ brittle.

For now, and for my use case, a solution is to train models within a container or with a `renv` artiffact as to retain the environment and the functionalities associated with a given version of the R6 objects. Is there a slot on `mlr3` objects that indicates which version of `mlr3` they have been built with, or depend on? This would be useful for accessing deprecated/changed slots, re-building appropriate environments and troubleshooting.
