### ISSUE TITLE
Implement parallel predict functions for learners

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#668]
Which do not parallelize internally (e.g. SVM).

cc @be-marc

**Comment by pat-s** [comment]
Yes but we need to add the capabilities for the specific learners to the learners in {mlr3learners}, aren't we?

**Comment by mllg** [comment]
Haven't fleshed this out completely yet, but this should go into the base class.

**Comment by mllg** [comment]
So in principle you can already do this like this (code not tested, but I hope you get the idea):

```r
parts = split(newdata, 1:nrow(newdata) %/% 4)
predictions = mclapply(parts, learner$predict_newdata)
do.call(c, predictions)
```
