### ISSUE TITLE
Automatically unname and convert classification predictions

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3#681]
Sorry I can't provide a reprex but here's the error: https://github.com/mlr-org/mlr3extralearners/runs/3433309735?check_suite_focus=true#step:10:30

Basically the autotest fails for classification learners if 'response' is not an unnamed character. I think this is a coercion we can safely make ourselves so when creating a PredictionClassif object would it be possible to include `unname(as.character(response))` (https://github.com/mlr-org/mlr3extralearners/pull/101/commits/9394b43538ce921a0b5fcc2fb245360689521059#diff-a3f2eaa1baa74d24dea1e4555604bbee9599257431dae8ac9788764e2184f778R204)?

**Comment by mllg** [comment]
Should be fixed now.

**Comment by RaphaelS1** [comment]
Thanks!
