### ISSUE TITLE
Add option to disable assertions

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#694]
Not sure if this is really a good idea. Maybe collect examples here when this would be useful?

**Comment by berndbischl** [comment]
reasons for this:
* at some point these data checks can cost time
* these checks always carry the risk that mlr3 simply doesnt allow the user to do what she wants. disable might increase flexibility

**Comment by berndbischl** [comment]
maybe simply learner$disable_propery_checks = TRUE?

**Comment by mllg** [comment]
I don't see any performance problems currently, and I have the impression that being overly strict here often helps to catch user errors. If a good case for disabling assertions comes up again, I will reconsider, but close for now.
