### ISSUE TITLE
mlr3.allow_utf8_names = TRUE breaks Task printer

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#697]
```r
options(mlr3.allow_utf8_names = TRUE)
ts <- TaskRegr$new("test", data.table(`%^` = 1:3, t = 3:1), target = "t")
print(ts)
#> <TaskRegr:test> (3 x 2)
#> * Target: t
#> * Properties: -
#> * Features (1):
#> Error in sprintf(msg, ...) : unrecognised format specification '%^'
```
We probably shouldn't put feature names in the `fmt` part of `sprintf`; besides the `%`-issue, the `fmt` part is also limited to 8192 bytes in length.

**Comment by mllg** [comment]
0099ccccc8c8657d4fbd5aeba4b2827561529192 addresses '%' in feature names. Not sure in which case the limit of 8192 bytes would be the problem. You have 8192 bytes for the format string, not the resulting string, right?

**Comment by mllg** [comment]
Note that it might be possible to allow `%`, but I'm really not sure if we can test this properly ...

**Comment by mb706** [comment]
The format string max length is 8192 bytes. I don't know what you are doing with feature names that it ends up on the `fmt`-end of `sprintf()`, but it could be a problem if a combination of a few feature names together has a length more than that?

**Comment by mllg** [comment]
Ah ok, the `catf` is problematic... I've replaced the call.
