### ISSUE TITLE
DataBackendRename ignores when primary_key gets renamed

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#702]
```r
dbdt <- DataBackendDataTable$new(data.table(id = 1L, a = 1, b = 2), primary_key = "id")
dbr <- DataBackendRename$new(dbdt, "id", "id2")
dbr
#> <DataBackendRename> (1x3)
#>  id2 a b
#>    1 1 2
dbr$primary_key
#> [1] "id"
```
`$primary_key` should be `"id2"` here. IDK if renaming primary keys should be allowed, but we are (1) allowing primary keys to have different names, so why not allow renaming them, and (2) forbidding `DataBackendCbind`ing `DataBackends` with different `$primary_key`s, so there is even a usecase where one would need to rename a primary key.

**Comment by mllg** [comment]
994e67e throws an error instead of silently renaming the primary key. I don't see a usecase where this would be important.
