### ISSUE TITLE
Filters for survival analysis

### ISSUE THREAD

**Issue by mbostanara** [mlr-org/mlr3#717]
I want to run a number of machine learning algorithms with different feature selection methods on survival data using the MLR3 package. For that, I am using the Benchmark() function of MLR3.

Unfortunately, filter feature selection methods of MLR3 do not support survival, yet. However, MLR package supports survival filters.

I can fuse MLR learners with an MLR filter method. After that, I need to convert them to a learner in MLR3 in order to be able to use banchmark_grid() function of MLR3.

I would like to know if there is any way to use MLR survival filters in MLR3? Or is there any way that I can convert MLR filters to MLR3 filters?

Thank you

**Comment by RaphaelS1** [comment]
Hi, I'll let someone else answer the direct question but I think the deeper point is that we need to implement the `surv` task type in mlr3filters. I can try look into this when I have some time but that's quite limited now, can I suggest you open an issue in [mlr3filters](https://github.com/mlr-org/mlr3filters) requesting support for `surv` task type?
