### ISSUE TITLE
model deployment tools

### ISSUE THREAD

**Issue by topepo** [mlr-org/mlr3#718]
RStudio is creating some R packages and other tools for model deployment (and eventually monitoring and so on). @juliasilge is the main person working on this. 

The main package, [`vetiver`](https://vetiver.tidymodels.org/), will go to CRAN soon with S3 methods for `lm` models. We have already built S3 methods for tidymodels, `caret`, and others that will be in subsequent releases. `vetiver` is fairly very simple and new models require some S3 methods. 

Would you be interested in contributing to `vetiver` for `mlr3` models? `mlr3` would be good to have so that just about any R model can be deployed and, as a side bonus, would help us determine if our APIs are general enough. 

If you would rather not, I can list some items to get guidance from you. This is mostly related to ancillary information that is required for deployment (e.g. extracting required packages for the model object, training data attributes, etc).

**Comment by be-marc** [comment]
> It would be great to know if you have any problems building support for mlr3 based on this info.

You could add more information on `handler_predict`.  I wasn't sure about the right return type. The other functions were easy to implement with the information from the PRs on `caret` and `tidymodels`.

**Comment by juliasilge** [comment]
@be-marc Thank you for that feedback. 🙏 

I added some more detail to [this documentation page](https://vetiver.tidymodels.org/reference/handler_startup.html), specifically this:

> A `handler_startup` function should return invisibly, while a `handler_predict` function should return a function with the signature `function(req)`. The request body (`req$body`) consists of the new data at prediction time; this function should return predictions either as a tibble or as a list coercable to a tibble via `tibble::as_tibble()`.
