### ISSUE TITLE
Error when using the predict function

### ISSUE THREAD

**Issue by phisanti** [mlr-org/mlr3#747]
I had an script where I had the following line:
```R

d[datetime > "2021-01-01", 
  c("pred_class_a", 
    "pred_class_b") := .(model_a$predict_newdata(.SD) %$% 
                      prob %>%
                      .[, 2],
                    model_b$predict_newdata(.SD) %$% 
                      prob %>%
                      .[, 2]
    ), 
  .SDcols = c(predictors_cols)]

```
Then, I updated to the latest version of mlr3 this morning and now I have the following error:

```
Error in .__TaskClassif__data(self = self, private = private, super = super,  : 
  could not find function ".__TaskClassif__data"

```
The model is based on `xgboost `classifier. I also tried to export separately the `xgboost `model, but when I predict new data using the `xgboost `and the `xgb.DMatrix`, I get completely different probabilities. Is there a reason for that?

EDIT: I can confirm that with version 0.12.0 the error is gone.

**Comment by mllg** [comment]
This is a version conflict, but should be resolved after `update.packages()` and restarting the session. I'm not sure at this point if the models need to be refitted though. Removing the `$data()` method from `TaskClassif` might have been a breaking change.
