### ISSUE TITLE
we need to document what happens in cases of learner error

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#75]
this should probably be done in a vignette

**Comment by berndbischl** [comment]
our mechanism should probably be:
run with callr in an external process (user has to select this), then we capture the fail.
if that happens, we can use a dummy predictor. 
if the user does that, he needs to be able to transparently see (at the end) that that has happened and due to what error

**Comment by mllg** [comment]
There is a vignette now. We have a fallback learner which you can define per learner. Calls to learners are encapsulated via `evaluate` or `callr` (more overhead, but guards against segfaults) if enabled via `mlr_control()`. Corresponding logs are stored in the experiment. 

Default: Exception is raised, no error handling.
