### ISSUE TITLE
Improve printing of data.tables when new data.table version is on CRAN 

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#752]
data.table now provides the possibility to write S3 methods `format_col.X` to modify the printing of data.tables (see [here](https://github.com/Rdatatable/data.table/blob/master/NEWS.md)). 

We could use that for e.g. improving the printing of benchmark designs once the new data.table version is on CRAN

**Comment by mllg** [comment]
This is partly already implemented:

https://github.com/mlr-org/mlr3/search?q=format_list_item

You can try to improve it further if you like.
