### ISSUE TITLE
ParameterSet not an exported object from  namespace:distr6  

### ISSUE THREAD

**Issue by Ppower123** [mlr-org/mlr3#754]
ParameterSet not an exported object from  namespace:distr6

**Comment by RaphaelS1** [comment]
I assume this relates to mlr3proba, if you confirm I'll transfer the issue.

Please provide some more detail as there is no useful information above that we can address..

**Comment by RaphaelS1** [comment]
Closed here as you've posted in proba as well https://github.com/mlr-org/mlr3proba/issues/241
