### ISSUE TITLE
Learners not loaded properly

### ISSUE THREAD

**Issue by ramtinz** [mlr-org/mlr3#764]
Learners cannot be loaded. 
R version 4.1.2 (2021-11-01)
OS: Windows
Here is the issue:
```
learner = mlr3::lrn("classif.rpart")
learner$param_set
[1] "Empty parameter set."
(.packages())
 [1] "mlr3verse"    "mlr3misc"     "mlr3learners" "mlr3"         "stats"        "graphics"     "grDevices"    "utils"        "datasets"     "methods"     
[11] "base" 

packageVersion("mlr3")
[1] ‘0.13.1’
packageVersion("mlr3learners")
[1] ‘0.5.2’
packageVersion("mlr3verse")
[1] ‘0.2.2’
```
Is there something I'm missing here?

**Comment by mllg** [comment]
This should work, and most unit tests would fail if this would be broken. Please update all packages (`update.packages()`).

If you still encounter problems, please re-open and provide a `sessionInfo()`.

**Comment by ramtinz** [comment]
Right, the issue came most likely because there was a file (r codes) in the project with a previous version of mlr. Once I open the file, this behavior appeared and when it wasn't there there was no such problem.

**Comment by ramtinz** [comment]
so my understanding is that mlr and mlr3 cannot be used at the same time

**Comment by mllg** [comment]
> so my understanding is that mlr and mlr3 cannot be used at the same time

Yes, that's right. The devel version now signals a warning if both packages are loaded in the same session.
