### ISSUE TITLE
HOW to get model coefficient from mlr3

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [mlr-org/mlr3#778]
Hi 
@adibender 
````
measure = msr("surv.uno_auc")
learners = lrns(worked.surv) 
bmr = benchmark(benchmark_grid(task, learners, rsmp("cv", folds = 3)), store_models = TRUE)
# https://mlr3.mlr-org.com/reference/benchmark.html
bmr$aggregate(measure)
autoplot(bmr, measure = measure)
````
I successfully ran the benchmark for survival analysis.
BUT I need the model information. HOW to get model coefficient or importance from mlr3
Best,
Jian-Guo

**Comment by mllg** [comment]
`as.data.table(bmr)` has column `learner` which contains all fitted learners and models (`$model` / `$importance()`). You can also go through results grouped by resample via `bmr$resample_results` -> `resample_result` -> `learners`.

 Don't how what learners you have trained, maybe `coef()` is helpful.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @mllg 
Thanks for your reply.

I tried it based on what you said.
bmr$resample_results$resample_result[[1]][["learner"]][["model"]]
````
a<-bmr$resample_results$resample_result
> View(a)
> a[[1]][["learner"]]
<LearnerSurvAkritas:surv.akritas>
* Model: -
* Parameters: list()
* Packages: mlr3, mlr3proba, mlr3extralearners, survivalmodels, distr6
* Predict Type: crank
* Feature types: logical, integer, character, numeric, factor
* Properties: -
Warning messages:
1: '.__ResampleResult__data' is deprecated.
Use 'as.data.table(resample_result)' instead.
See help("Deprecated") 
2: '.__ResampleResult__data' is deprecated.
Use 'as.data.table(resample_result)' instead.
See help("Deprecated") 
> a[[1]][["learner"]][["model"]]
NULL
> bmr$resample_results$resample_result[[1]][["learner"]][["model"]]
NULL
> coef(bmr)
NULL
> a[[1]][["learners"]][[1]]
<LearnerSurvAkritas:surv.akritas>
* Model: akritas
* Parameters: list()
* Packages: mlr3, mlr3proba, mlr3extralearners, survivalmodels, distr6
* Predict Type: crank
* Feature types: logical, integer, character, numeric, factor
* Properties: -
````
But still did not find the model and coef.
Best,
Jian-Guo

**Comment by mllg** [comment]
All should work:

```r
model = as.data.table(bmr)$learner[[1]]$model
model = bmr$resample_results$resample_result[[1]]$learners[[1]]$model
model = bmr$resample_result(1)$learners[[1]]$model
```

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @mllg Now it's worked.
![image](https://user-images.githubusercontent.com/20199977/156152339-f8d0ef1a-b59c-4ad6-a8a9-e93acdad1079.png)
But I still can not find the coefficient of the related model. I understand some models based on non-liner but should have important performance.
Best,
Jian-Guo
