### ISSUE TITLE
Problem when using a GPU trained model on a CPU only computer

### ISSUE THREAD

**Issue by phisanti** [mlr-org/mlr3#794]
I have finally managed to use the GPU of my system. However, when I take the model back from the cluster to my computer I am encountered the following error
code:
```r
modelup$predict_newdata(d)
```
error print:
```
[20:44:33] WARNING: amalgamation/../src/gbm/gbtree.cc:386: Loading from a raw memory buffer on CPU only machine.  Changing tree_method to hist.
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  [20:44:33] amalgamation/../src/tree/tree_updater.cc:20: Unknown tree updater grow_gpu_hist
```

**Comment by sebffischer** [comment]
Please provide more information and ideally a minimal reproducible example using https://github.com/tidyverse/reprex

**Comment by mllg** [comment]
Looks like if you fit a model on a GPU, it is not compatible anymore with a CPU-only installation. There is little we can do about it, maybe you can also compile with GPU support locally or ask upstream for advice?

**Comment by pat-s** [comment]
@phisanti Can this be closed? The issue seems to originate from the GBM/XGBoost learner itself and hence is not in control by us. 

We don't have any measures to control what learners do with the GPU.

**Comment by phisanti** [comment]
yes, thanks for the help!
