### ISSUE TITLE
`as_data_backend` creates a `..row_id` variable that does not meet R's naming convention

### ISSUE THREAD

**Issue by Fred-Wu** [mlr-org/mlr3#804]
I used `as_data_backend()` to store a sparse matrix, and passed it to `as_task_classif()`. 
However,  `as_data_backend()` creates a `..row_id` variable, which does not meet R's naming convention, so creating the task failed.  Element 2 is the variable named `..row_id`. 

```
dense <- df[, "disposition"]
data_store <- as_data_backend(matData, dense = dense)
data_store$colnames[1:10]
 [1] "disposition" "..row_id"    "dep_name_C"  "dep_name_B"  "dep_name_A"  "esi_1"      
 [7] "esi_2"       "esi_3"       "esi_4"       "esi_5"      

task <- as_task_classif(data_store, target = "disposition", positive = "Admit")
Error in .__Task__initialize(self = self, private = private, super = super,  : 
  Assertion on 'feature names' failed: Must have names according to R's variable naming conventions, but element 2 does not comply.
```

However, using the example from the reference seems to have no issue. 

```
requireNamespace("Matrix")
#> Loading required namespace: Matrix
data = Matrix::Matrix(sample(0:1, 20, replace = TRUE), ncol = 2)
colnames(data) = c("x1", "x2")
dense = data.frame(
  fact = factor(sample(c("a", "b"), 10, replace = TRUE), levels = c("a", "b"))
)

b = as_data_backend(data, dense = dense)

task <- as_task_classif(b, target = "fact", positive = "a")
```

**Comment by mllg** [comment]
I'm having trouble to reproduce this. Can you provide a reproducible example which triggers the error message?

Note that `b` in your 2nd example also has a column "..row_id", so this should not be an issue. I've refactored the assertions in the Task constructor, the index (2) was referring to the sorted column names, i.e. a different name. I suspect that one of your column names accidentally contains a non-ascii characters.

**Comment by Fred-Wu** [comment]
> I'm having trouble to reproduce this. Can you provide a reproducible example which triggers the error message?
> 
> Note that `b` in your 2nd example also has a column "..row_id", so this should not be an issue. I've refactored the assertions in the Task constructor, the index (2) was referring to the sorted column names, i.e. a different name. I suspect that one of your column names accidentally contains a non-ascii characters.

I think `..row_id` may not be the culprit. 
I have removed all symbols from variable names, and tested for non-ascii characters. 
There is none of them in the variable names. 

This time, the error indicates a different feature column as the source of error. 

```
col_rename <- str_replace_all(colnames(matData), c("\\s" = "", "\\-" = "", 
                                                   "\\/" = "", "\\`" = "", 
                                                   "\\." = "", "\\_" = ""))
colnames(matData) <- col_rename

test_nonascii <- sapply(col_rename, function(x) length(tools::showNonASCII(x)))

> sum(test_nonascii)
[1] 0
```
In case 'feature names' means other than 'target', which is the first column, here are column 107 and 108 in the data. 
```
> task <- as_task_classif(data_store, target = "disposition", positive = "Admit")

Error in .__Task__initialize(self = self, private = private, super = super,  : 
  Assertion on 'feature names' failed: Must have names according to R's variable naming conventions, but element 107 does not comply.

> data_store$colnames[c(1, 107, 108)]
[1] "disposition"             "ccabdominalpain"        
[3] "ccabdominalpainpregnant"
```

Just by the way, this data actually worked when I ran it last time. Due to the non-ascii issue as well last time, I did enable the ascii feature from the option, but not this time. However, there appears no non-ascii character in the variable names at all.

**Comment by Fred-Wu** [comment]
> I'm having trouble to reproduce this. Can you provide a reproducible example which triggers the error message?
> 
> Note that `b` in your 2nd example also has a column "..row_id", so this should not be an issue. I've refactored the assertions in the Task constructor, the index (2) was referring to the sorted column names, i.e. a different name. I suspect that one of your column names accidentally contains a non-ascii characters.

I think you are right. I have found the issues after rereading your comments, and sorted the variable names. Those errors were caused by the character such as `>` in the name. 

I will close this now. Thanks.
