### ISSUE TITLE
[Question] Is `h2o` Supported

### ISSUE THREAD

**Issue by rsangole** [mlr-org/mlr3#834]
Hello,

Is the `{h2o}` package supported? I searched the `mlr3learners` and `mlr3extraleaners` and couldn't find it there. Since I'm new to this ecosystem, does that imply `{h2o}` is current _not_ supported, or can I still use it in some way?

Cheers!

**Comment by sebffischer** [comment]
Hey @rsangole  currently they are not available but we are discussing whether we should add (some of) them. Is there any specific learner that you are missing?

**Comment by rsangole** [comment]
I see. 

Two reasons I've used h2o in the past: Isolation Forests, and GPU support for Xgboost models.

**Comment by rsangole** [comment]
Thanks Sebastian. I'll give the xgboost GPU a try.

On these lines - is it possible to integrate keras deep learning models within mlr3?

**Comment by sebffischer** [comment]
There is https://github.com/mlr-org/mlr3keras/ and we are working on https://github.com/mlr-org/mlr3torch/

If there is ever something you don't have, you can also implement a learner yourself, see https://mlr3book.mlr-org.com/07-extending-learners.html (some info is a little outdated here but there is already an open PR that updates it and is just waiting for it to be reviewd)

**Comment by rsangole** [comment]
Thanks for these resources. Looks like there's an autoencoder PR in mlr3keras, which is exactly the deep learning model I need at the moment. Appreciate it.
