### ISSUE TITLE
as_task_xxx should enable setting weights ect

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#839]
I think making this work would be a good user-friendly change, what do you think?  

```r
iris$weight = runif(150)
task = as_task_classif(iris, target = "Species", weight = "weight")
```

**Comment by sebffischer** [comment]
@mllg What do you think? 
 It might be a little tricky with column roles that can (meaningfully) have more than 1 role.

**Comment by mllg** [comment]
What about the other column roles like order, stratum, group or name?

**Comment by sebffischer** [comment]
See my comment above. I think this is actually not a great idea.

**Comment by mllg** [comment]
But weight can also be a feature?

**Comment by sebffischer** [comment]
yes, my comment was in general that this is not really a good idea. I am closing
