### ISSUE TITLE
Text view of help for learner classes is messed up

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#843]
Help for learner classes, e.g. `?LearnerClassifRpart`, contains a section about parameters. However, the text-view of that does not look pretty:

![image](https://user-images.githubusercontent.com/15801081/181723454-d06a4d03-eb13-4081-89c7-ee73a28d262e.png)

**Comment by mllg** [comment]
@sebffischer ...?

**Comment by sebffischer** [comment]
This part is being generated in paradox via rd_info.ParamSet. Apparently the current docs were generated using a version of paradox before the fix was mergerd.

**Comment by sebffischer** [comment]
See https://github.com/mlr-org/paradox/commit/3ce3c7742cdc52bfd7a59cfc74fa5001e44a905b

**Comment by mllg** [comment]
can you prepare a release (test on winbuilder, run revdep checks)?
