### ISSUE TITLE
Default return / improved error message for rr$experiment()

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3#87]
When calling `rr$experiment()` or  `rr$experiments()` without an argument, we should either have a default way (e.g. iter = 1) including a message or print a custom error message.

``` r
library(mlr3)
task = mlr_tasks$get("iris")
learner = mlr_learners$get("classif.rpart")

resampling = mlr_resamplings$get("cv")
resampling$param_vals = list(folds = 3)
rr = resample(task, learner, resampling)
#> INFO [mlr3] Running learner 'classif.rpart' on task 'iris (iteration 1/3)' ...
#> INFO [mlr3] Running learner 'classif.rpart' on task 'iris (iteration 2/3)' ...
#> INFO [mlr3] Running learner 'classif.rpart' on task 'iris (iteration 3/3)' ...

rr$experiment()
#> Error in assert_int(iter, lower = 1L, upper = nrow(self$data), coerce = TRUE): argument "iter" is missing, with no default
```

<sup>Created on 2018-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mllg** [comment]
I guess by adding a default, the error message is okay. I'll look into extending checkmate to give better messages if an argument is missing.

**Comment by mllg** [comment]
I'm against a default here, the user should be forced to think about which iteration to request. The error is also okay (now?).
