### ISSUE TITLE
col roles printer bug

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#877]
### Description

The new printer for col_roles does not work as intended.
I would expect it to print the column name, but instead, it prints "weight".

### Reproducible example

``` r
library(mlr3)
a = tsk("iris")
a$col_roles$weight = "Petal.Width"
print(a)
#> <TaskClassif:iris> (150 x 5): Iris Flowers
#> * Target: Species
#> * Properties: multiclass, weights
#> * Features (4):
#>   - dbl (4): Petal.Length, Petal.Width, Sepal.Length, Sepal.Width
#> * Weights: weight
```

<sup>Created on 2022-11-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mllg** [comment]
Fixed in f3836306925159d182763be4e9d7096fad88ca0e
