### ISSUE TITLE
Error for LearnerClassifMultinom when predicting prob for single x

### ISSUE THREAD

**Issue by dandls** [mlr-org/mlr3#883]
### Description

I trained a mlr3 LearnerClassifMultinom model on the iris dataset under predict_type = "prob". 
If I want to predict class probabilities for a single instance using `predict_newdata()`, I receive an error.  

```
Error in `colnames<-`(`*tmp*`, value = lvls) : 
 attempt to set 'colnames' on an object with less than two dimensions
```

### Reproducible example

library(mlr3)
library(mlr3learners)

task <- TaskClassif$new(id = "iris", backend = iris, target = "Species")
lrn <- lrn("classif.multinom", predict_type = "prob")
lrn$train(task)
#> # weights:  18 (10 variable)
#> initial  value 164.791843 
#> iter  10 value 16.177348
#> iter  20 value 7.111438
#> iter  30 value 6.182999
#> iter  40 value 5.984028
#> iter  50 value 5.961278
#> iter  60 value 5.954900
#> iter  70 value 5.951851
#> iter  80 value 5.950343
#> iter  90 value 5.949904
#> iter 100 value 5.949867
#> final  value 5.949867 
#> stopped after 100 iterations
lrn$predict_newdata(iris)
#> <PredictionClassif> for 150 observations:
#>     row_ids     truth  response  prob.setosa prob.versicolor prob.virginica
#>           1    setosa    setosa 1.000000e+00    1.526406e-09   2.716417e-36
#>           2    setosa    setosa 9.999996e-01    3.536476e-07   2.883729e-32
#>           3    setosa    setosa 1.000000e+00    4.443506e-08   6.103424e-34
#> ---                                                                        
#>         148 virginica virginica 1.470964e-14    1.023609e-03   9.989764e-01
#>         149 virginica virginica 6.009635e-17    4.504137e-06   9.999955e-01
#>         150 virginica virginica 2.726745e-14    2.243538e-02   9.775646e-01
lrn$predict_newdata(iris[1, ])
#> Error in `colnames<-`(`*tmp*`, value = lvls): attempt to set 'colnames' on an object with less than two dimensions

sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.5 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] mlr3oml_0.5.0      mlr3learners_0.5.5 mlr3_0.14.1       
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.1.1       highr_0.9            R.methodsS3_1.8.2   
#>  [4] mlr3misc_0.11.0-9000 R.utils_2.12.2       tools_4.1.1         
#>  [7] uuid_1.1-0           digest_0.6.31        evaluate_0.19       
#> [10] checkmate_2.1.0      R.cache_0.16.0       rlang_1.0.6         
#> [13] reprex_2.0.1         cli_3.5.0            rstudioapi_0.14     
#> [16] yaml_2.3.6           parallel_4.1.1       xfun_0.30           
#> [19] fastmap_1.1.0        withr_2.5.0          styler_1.8.1        
#> [22] stringr_1.4.0        knitr_1.36           fs_1.5.0            
#> [25] vctrs_0.5.1          globals_0.16.2       nnet_7.3-16         
#> [28] glue_1.6.2           data.table_1.14.6    listenv_0.9.0       
#> [31] R6_2.5.1             parallelly_1.33.0    rmarkdown_2.14      
#> [34] sessioninfo_1.1.1    lgr_0.4.4            purrr_0.3.4         
#> [37] magrittr_2.0.3       backports_1.4.1      codetools_0.2-18    
#> [40] htmltools_0.5.2      palmerpenguins_0.1.1 future_1.30.0       
#> [43] paradox_0.11.0       stringi_1.7.6        crayon_1.5.1        
#> [46] R.oo_1.25.0

**Comment by mllg** [comment]
The multinom learner seems to drop the dimension of the probability matrix. I did not find any documentation on the prediction function, but the behaviour seems to be intentional: https://github.com/cran/nnet/blob/9fbb319554f08c9c43b772ed70122c124b5a0c67/R/multinom.R#L203

I've added a workaround in https://github.com/mlr-org/mlr3learners/pull/263.

Thanks for the report.
