### ISSUE TITLE
Accessing the trained model of RPART in the benchmark design

### ISSUE THREAD

**Issue by redecker-m** [mlr-org/mlr3#884]
### Description

I am still quite new to mlr3 and have some difficulties to get the model coefficients from a benchmark design. 
I use 4 different learners (RPART, LogReg, LDA, RandomForest), each with 3-fold CV.
In my case the model from RPART is not accessable, model, for LDA and LogReg it works with circumstances.

I have previously tested RPART with a normal learner$train setup outside the benchmard design, where the access via learner$model$classif.rpart$model works. Here shortly the design:

### Reproducible example

```r
lrn1 <- lrn("classif.rpart", cp=0.0001, minsplit=20, keep_model= TRUE, predict_type = "prob")
graph_rpart <- po("encode") %>>%  po("imputemode") %>>% po("filter", filter = flt("importance", learner = lrn1), filter.frac = 0.5) %>>% po("learner", lrn1)
learner1 <-  GraphLearner$new(graph_rpart)
learner1$id <- "RPART"

learners <- list(learner1,learner2,learner3,learner4)
resampling <- rsmp("cv", folds=3)
design <- benchmark_grid(tasks_second, learners, resampling)
bmr <- benchmark(design, store_models=TRUE)
```

> coef1 <- bmr$score()$learner[[1]]
> coef1$model$importance$scores
<<< Works fine

> coef1$model$classif.rpart$model
Error in tfun(frame$yval2, ylevel, digits, nsmall) : 
  unused argument (nsmall)

In comparison: accessing the estimators from LogReg (learner2) works fine:
> coef2 <- bmr$score()$learner[[4]]
> summary(coef2$model$classif.log_reg$model)
<<< Works fine

Does it has to do with the cross-validation or the pre-filtering (I also used filtering for LogReg) or with the hyperparameters setup?
Is there an easier direct way to compare the models from different learners in a benchmark design?
Is there a way to access the model coefficients via bmr$score or bmr$aggregate - so far, I understand that the $model information cannot be stored there (although store_models=TRUE is set)?

Best regards
Matthias

**Comment by be-marc** [comment]
You code does not run. However, this works for me.

```r
library(mlr3)
library(mlr3pipelines)
library(mlr3filters)

lrn1 <- lrn("classif.rpart", cp=0.0001, minsplit=20, keep_model= TRUE, predict_type = "prob")
graph_rpart <- po("encode") %>>%  po("imputemode") %>>% po("filter", filter = flt("importance", learner = lrn1), filter.frac = 0.5) %>>% po("learner", lrn1)
learner1 <-  GraphLearner$new(graph_rpart)
learner1$id <- "RPART"

learners <- list(learner1)
resampling <- rsmp("cv", folds=3)
design <- benchmark_grid(tsk("pima"), learners, resampling)
bmr <- benchmark(design, store_models=TRUE)

gl_rpart_1 = bmr$score()$learner[[1]]
gl_rpart_1$model$classif.rpart$model
```

**Comment by redecker-m** [comment]
Thanks Marc, for checking on your data/machine.
I have retrained the benchmark and now it works on my machine as well.
