### ISSUE TITLE
BenchmarkResult add getter for fitted models

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#887]
I keep getting the question on how to get the fitted models out from a `BenchmarkResult`. 
The documentation on this is not very helpful (something about looking at the score) and I think this is
something that is needed fairly often, e.g. for post-hoc visualizations or interpretabiltiy. 

I would suggest to offer a getter function that makes this easily accessible.

**Comment by be-marc** [comment]
We will add no getter but updated the documentation to do it via `$resample_result(i)`.
