### ISSUE TITLE
benchmark: Allow re-running jobs

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#890]
Currently, if jobs in a `benchmark()` call fail, e.g. due to communication loss when parallelizing on a cluster it's unclear how to restart single lost jobs. I think we should either
- be able to restart some runs (e.g. a row in the benchmark design) 
- tell people to use the batchtools backend for such cases

But in any way, how this is done should be documented a) in the `benchmark` docs and b) the appropriate section in the book.

**Comment by be-marc** [comment]
Added a reference for mlr3batchmark to `benchmark()` function
