### ISSUE TITLE
`task$truth()` doesn't respect row order after filtering task

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3#896]
Is the following expected behavior?

``` r
library(mlr3)

spam = tsk('spam')
all(spam$truth() == spam$truth(rows = 1:spam$nrow)) # ok
#> [1] TRUE

spam$filter(rows = sample(1:spam$nrow, 42))
all(spam$truth() == spam$truth(rows = 1:spam$nrow)) # not ok!
#> [1] FALSE
```

<sup>Created on 2023-02-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by be-marc** [comment]
If `rows = NULL`, rows are set to `$row_roles$use`. `Task$filter()` sets `$row_roles$use`. `spam$truth(rows = 1:spam$nrow)` retrieves from the complete data set.  `spam$data(rows = 1:spam$nrow)` is doing the same. `spam$data()` and `spam$truth()` use `$row_roles$use`.  I think that the behavior is correct.

**Comment by be-marc** [comment]
My first comment was wrong. Looks like a bug. I'll take a look. Thanks for letting us know.

**Comment by be-marc** [comment]
Okay no bug. After calling `spam$filter(rows = sample(1:spam$nrow, 42))`, `spam$truth(rows = 1:spam$nrow)` still retrieves from the complete data set i.e rows 1 to 42. `spam$truth()` retrieves from the rows set in `$row_roles$use`.

```r
spam = tsk('spam')

spam$filter(rows = sample(1:spam$nrow, 42))
spam$row_roles$use
#>  [1]  152  154  323  352  384  467  706  915  925 1191 1226 1294 1448 1492 1613 1707 1881 1962 2005 2060 2108 2211 2304 2357 2455 2656 3213 3362 3378 3438 3675 3713 3743 3823 3890 3942 3984 4065 4186 4383 4472 4516

all(spam$truth() == spam$truth(rows = spam$row_roles$use))
#> [1] TRUE
```
The behavior is correct.

**Comment by be-marc** [comment]
The assumption that `rows = 1:spam$nrow` refers to the filtered data set is wrong. `rows` always refers to the whole data set even after filtering.

**Comment by bblodfon** [comment]
I see, thanks for the explanation! The same is true (`rows` and `row_ids` refer to the whole dataset) when doing something along the lines of: `learner$train(task, row_ids = 1:42)$predict(task, row_ids = 42:50)`.

Maybe this needs to be clarified in the documentation somewhere? (I got really confused about it)

**Comment by be-marc** [comment]
Done
