### ISSUE TITLE
Possibility to save / access models via callbacks during resample

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#899]
In some cases, users might want to fit large models on large datasets using `resample()`.
In this case [here](https://stackoverflow.com/questions/75405217/no-model-stored-with-mlr3), 
the person was unable to fit the models into RAM when specifying `store_models = TRUE`, but he still wanted access to the models, or rather the impurity scores from the models. 

I have to suggestions to make these things more flexible: 
1. Adding callbacks in `resample()` would allow to save these models to disk during `resample()`. 
2. Can we somehow score some measures that depend on the model on the workers? So that measures that require the model can still be evaluated when `store_models = FALSE`?

**Comment by be-marc** [comment]
Same as #1013.

**Comment by be-marc** [comment]
Closed by #1214
