### ISSUE TITLE
Measure to retrieve the number of selected features

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#937]
requested by Bernd to support e.g. multicrit optimization of no of features and classification accuracy.

**Comment by mllg** [comment]
There is already a measure for this ("selected_features").

**Comment by sebffischer** [comment]
Can we maybe rename the measure, e.g. `"n_selected_features"` 
The name suggests that it returns the selected features (I guess this is why Bernd and Martin were not aware of it).
