### ISSUE TITLE
encapsulate option "try" is not documented?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3#938]
part from the current version of the book:

> We also set a featureless baseline as a fallback learner (@sec-fallback) and set `"try"` as our encapsulation method, which logs errors/warnings to an external file that can be read by `batchtools` (we will return to this in @sec-batchtools-monitoring).
>
>    ```{r large_benchmarking-002, warning = FALSE}
>    # featureless baseline
>    lrn_baseline = lrn("classif.featureless", id = "featureless")
>
>    # logistic regression pipeline
>    lrn_lr = lrn("classif.log_reg")
>    lrn_lr = as_learner(ppl("robustify", learner = lrn_lr) %>>% lrn_lr)
>    lrn_lr$id = "logreg"
>    lrn_lr$fallback = lrn_baseline
>    lrn_lr$encapsulate = c(train = "try", predict = "try")
>    
>    ```

**Comment by mllg** [comment]
Documented in the last release.
