### ISSUE TITLE
Tests / Checks for flipped factors

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#943]
I can imagine that some learner's don't handle factors with flipped levels perfectly. 
A proposal would be to add an autotest that checks whether predictions are equivalent irrespective of the underlying factor representation.
Then, there could be a learner property that indicates whether the learner can deal with flipped factor levels.
In the `$predict_newdata()` and the `$predict()` method we could then (depending on whether this property is present) throw an error.

**Comment by sebffischer** [comment]
Decision:  We add it as an autotest (whether a learner can handle it) and then check where we have to fix stuff

**Comment by berndbischl** [comment]
Please either show a reprex where this breaks the package or close during the workshop

**Comment by sebffischer** [comment]
``` r
library(mlr3)
library(mlr3learners)
#> Warning: package 'mlr3learners' was built under R version 4.3.3
library(mlr3extralearners)

learner = lrn("classif.ksvm")

x = sample(c("a", "b"), 100, replace = TRUE)
y = x
y[sample(1:100, 10)] = sample(c("a", "b"), 10, replace = TRUE)

d = data.table(
  x = factor(x, levels = c("a", "b")),
  y = factor(y)
)

dflip = data.table(
  x = factor(x, labels = c("b", "a"), levels = c("b", "a")),
  y = factor(y)
)

stopifnot(all(d$x == dflip$x))
stopifnot(!all(as.integer(d$x) == as.integer(dflip$x)))

task = as_task_classif(d, target = "y")
task_flip = as_task_classif(dflip, target = "y")

learner$train(task)

p1 = learner$predict(task)
p2 = learner$predict(task_flip)

stopifnot(all(p1$response == p2$response))
#> Error: all(p1$response == p2$response) is not TRUE
```

<sup>Created on 2024-08-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
