### ISSUE TITLE
rpart fails to predict on titanic task

### ISSUE THREAD

**Issue by QuayAu** [mlr-org/mlr3#97]
````
task = mlr_tasks$get("titanic")
learner = mlr_learners$get("classif.rpart")
resampling = mlr_resamplings$get("cv")

resample(task, learner, resampling)
````

throws:

````
 Error in model.frame.default(Terms, newdata, na.action = na.action, xlev = attr(object,  : 
  factor Cabin has new levels A14, A21, B101, B39, B69, B78, C104, C106, C116, C28, C49, C7, C82, C86, C95, D19, D9, F, T 
````

**Comment by mllg** [comment]
Titanic needs preprocessing, better don't use it for automatic tests.

**Comment by mllg** [comment]
You could create a preprocessed version and add it to the package, though.

**Comment by berndbischl** [comment]
@QuayAu  really dont use titanic, for what we discussed yesterday. seems a bad choice

@mllg isnt the posted issue at leats relevant?

**Comment by mllg** [comment]
rpart breaks, there is nothing I can do about it. You need to merge levels or use stratification.

**Comment by berndbischl** [comment]
> rpart breaks, there is nothing I can do about it. You need to merge levels or use stratification.

bah, i hate this issue. does anyone know what they are doing in other toolboxes? 

it is possible to have a "fallback"? that would only work if the fallback is only on the observations where we break, which would imply testing them all one-by-one. which is totally infeasible as too expensive?

**Comment by berndbischl** [comment]
well. we DO know which levels a learner has seen during training? so we DO know on which observations i WILL break? even without calling it?

**Comment by berndbischl** [comment]
in any case, this does not seem like an mlr3 issue, and if somebody does not post otherwise, i dont see a simple solution here. i will try to think about this further in pipelines

**Comment by berndbischl** [comment]
i tried to outline a solution in the issue here:

PipeOp to try repair predicting with unseen factor levels #71
