### ISSUE TITLE
fallback learner should maybe be a warning

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#972]
Currently, the fallback learner log info is only shown during debug mode: 

https://github.com/mlr-org/mlr3/blob/dc2a983fb5b59dd0a009727b193227857cb7b9ea/R/worker.R#L94-L102

maybe this should be a warning?

**Comment by mb706** [comment]
Maybe relates more to the 'encapsulate' machinery than the fallback learner -- what to do if something that was encapsulated fails? Or is there a way for the fallback learner to be invoked without the encapsulation noticing?

**Comment by sebffischer** [comment]
make this info

**Comment by be-marc** [comment]
```r
learner = lrn("classif.debug", error_train = 1, fallback = lrn("classif.featureless"))

learner$train(tsk("spam"))
```
