### ISSUE TITLE
arg cloning: can we please document and unit tests if args are cloned for the most important function?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#98]
that seems to be
Experiment$new
resample
benchmark

the user should not be able to modify contained results by posthoc messing around with the passed reference

**Comment by mllg** [comment]
There are already quite some tests for this in place. 

All user input is cloned (task/learner in Experiment$new, everything you put into resample/benchmark). If you access objects from results, you get a reference. Yes - we rely here on the user not to do stupid things, but there is no practical way around this.
