### ISSUE TITLE
predict_time can be (kind of) wrong

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#992]
When calling `learner_predict()`, the `predict_time` in the state is overwritten. 
When doing a resampling and making predictions for different sets (in my case the holdout set and the test set), the `time_predict` is not (as I expected) the total prediction time, but only the prediction time for one of the predictions.

It would be great to have access to the different prediction times.

**Comment by mllg** [comment]
Store cumulative time for all predict sets + document.
